// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/mesh/landuses/v1/land_uses.proto

package landusesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/mesh/landuses/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LandUsesServiceName is the fully-qualified name of the LandUsesService service.
	LandUsesServiceName = "civil.mesh.landuses.v1.LandUsesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LandUsesServiceGetLandUsesProcedure is the fully-qualified name of the LandUsesService's
	// GetLandUses RPC.
	LandUsesServiceGetLandUsesProcedure = "/civil.mesh.landuses.v1.LandUsesService/GetLandUses"
	// LandUsesServiceGetLandUseTypesProcedure is the fully-qualified name of the LandUsesService's
	// GetLandUseTypes RPC.
	LandUsesServiceGetLandUseTypesProcedure = "/civil.mesh.landuses.v1.LandUsesService/GetLandUseTypes"
)

// LandUsesServiceClient is a client for the civil.mesh.landuses.v1.LandUsesService service.
type LandUsesServiceClient interface {
	GetLandUses(context.Context, *connect.Request[v1.GetLandUsesRequest]) (*connect.Response[v1.GetLandUsesResponse], error)
	GetLandUseTypes(context.Context, *connect.Request[v1.GetLandUseTypesRequest]) (*connect.Response[v1.GetLandUseTypesResponse], error)
}

// NewLandUsesServiceClient constructs a client for the civil.mesh.landuses.v1.LandUsesService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLandUsesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LandUsesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	landUsesServiceMethods := v1.File_civil_mesh_landuses_v1_land_uses_proto.Services().ByName("LandUsesService").Methods()
	return &landUsesServiceClient{
		getLandUses: connect.NewClient[v1.GetLandUsesRequest, v1.GetLandUsesResponse](
			httpClient,
			baseURL+LandUsesServiceGetLandUsesProcedure,
			connect.WithSchema(landUsesServiceMethods.ByName("GetLandUses")),
			connect.WithClientOptions(opts...),
		),
		getLandUseTypes: connect.NewClient[v1.GetLandUseTypesRequest, v1.GetLandUseTypesResponse](
			httpClient,
			baseURL+LandUsesServiceGetLandUseTypesProcedure,
			connect.WithSchema(landUsesServiceMethods.ByName("GetLandUseTypes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// landUsesServiceClient implements LandUsesServiceClient.
type landUsesServiceClient struct {
	getLandUses     *connect.Client[v1.GetLandUsesRequest, v1.GetLandUsesResponse]
	getLandUseTypes *connect.Client[v1.GetLandUseTypesRequest, v1.GetLandUseTypesResponse]
}

// GetLandUses calls civil.mesh.landuses.v1.LandUsesService.GetLandUses.
func (c *landUsesServiceClient) GetLandUses(ctx context.Context, req *connect.Request[v1.GetLandUsesRequest]) (*connect.Response[v1.GetLandUsesResponse], error) {
	return c.getLandUses.CallUnary(ctx, req)
}

// GetLandUseTypes calls civil.mesh.landuses.v1.LandUsesService.GetLandUseTypes.
func (c *landUsesServiceClient) GetLandUseTypes(ctx context.Context, req *connect.Request[v1.GetLandUseTypesRequest]) (*connect.Response[v1.GetLandUseTypesResponse], error) {
	return c.getLandUseTypes.CallUnary(ctx, req)
}

// LandUsesServiceHandler is an implementation of the civil.mesh.landuses.v1.LandUsesService
// service.
type LandUsesServiceHandler interface {
	GetLandUses(context.Context, *connect.Request[v1.GetLandUsesRequest]) (*connect.Response[v1.GetLandUsesResponse], error)
	GetLandUseTypes(context.Context, *connect.Request[v1.GetLandUseTypesRequest]) (*connect.Response[v1.GetLandUseTypesResponse], error)
}

// NewLandUsesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLandUsesServiceHandler(svc LandUsesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	landUsesServiceMethods := v1.File_civil_mesh_landuses_v1_land_uses_proto.Services().ByName("LandUsesService").Methods()
	landUsesServiceGetLandUsesHandler := connect.NewUnaryHandler(
		LandUsesServiceGetLandUsesProcedure,
		svc.GetLandUses,
		connect.WithSchema(landUsesServiceMethods.ByName("GetLandUses")),
		connect.WithHandlerOptions(opts...),
	)
	landUsesServiceGetLandUseTypesHandler := connect.NewUnaryHandler(
		LandUsesServiceGetLandUseTypesProcedure,
		svc.GetLandUseTypes,
		connect.WithSchema(landUsesServiceMethods.ByName("GetLandUseTypes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.mesh.landuses.v1.LandUsesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LandUsesServiceGetLandUsesProcedure:
			landUsesServiceGetLandUsesHandler.ServeHTTP(w, r)
		case LandUsesServiceGetLandUseTypesProcedure:
			landUsesServiceGetLandUseTypesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLandUsesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLandUsesServiceHandler struct{}

func (UnimplementedLandUsesServiceHandler) GetLandUses(context.Context, *connect.Request[v1.GetLandUsesRequest]) (*connect.Response[v1.GetLandUsesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.landuses.v1.LandUsesService.GetLandUses is not implemented"))
}

func (UnimplementedLandUsesServiceHandler) GetLandUseTypes(context.Context, *connect.Request[v1.GetLandUseTypesRequest]) (*connect.Response[v1.GetLandUseTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.landuses.v1.LandUsesService.GetLandUseTypes is not implemented"))
}
