// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/parcels/v1/parcels.proto

package parcelsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/parcels/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ParcelsServiceName is the fully-qualified name of the ParcelsService service.
	ParcelsServiceName = "civil.public.parcels.v1.ParcelsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure is the fully-qualified name of
	// the ParcelsService's GetParcelsWithImprovementSummaryByParcelId RPC.
	ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetParcelsWithImprovementSummaryByParcelId"
	// ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure is the fully-qualified name of
	// the ParcelsService's GetParcelsWithImprovementSummaryByFeatureId RPC.
	ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetParcelsWithImprovementSummaryByFeatureId"
	// ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure is the fully-qualified name of the
	// ParcelsService's GetNumericalParcelAttributeStatsById RPC.
	ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetNumericalParcelAttributeStatsById"
	// ParcelsServiceGetCategoricalParcelAttributeStatsByIdProcedure is the fully-qualified name of the
	// ParcelsService's GetCategoricalParcelAttributeStatsById RPC.
	ParcelsServiceGetCategoricalParcelAttributeStatsByIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetCategoricalParcelAttributeStatsById"
	// ParcelsServiceGetEquityComparablesProcedure is the fully-qualified name of the ParcelsService's
	// GetEquityComparables RPC.
	ParcelsServiceGetEquityComparablesProcedure = "/civil.public.parcels.v1.ParcelsService/GetEquityComparables"
	// ParcelsServiceGetSalesComparablesProcedure is the fully-qualified name of the ParcelsService's
	// GetSalesComparables RPC.
	ParcelsServiceGetSalesComparablesProcedure = "/civil.public.parcels.v1.ParcelsService/GetSalesComparables"
	// ParcelsServiceGetParcelIdsByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetParcelIdsByFeatureId RPC.
	ParcelsServiceGetParcelIdsByFeatureIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetParcelIdsByFeatureId"
	// ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure is the fully-qualified name of the
	// ParcelsService's GetEstimatedParcelsExtentWGS84 RPC.
	ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure = "/civil.public.parcels.v1.ParcelsService/GetEstimatedParcelsExtentWGS84"
	// ParcelsServiceUpdateParcelProcedure is the fully-qualified name of the ParcelsService's
	// UpdateParcel RPC.
	ParcelsServiceUpdateParcelProcedure = "/civil.public.parcels.v1.ParcelsService/UpdateParcel"
)

// ParcelsServiceClient is a client for the civil.public.parcels.v1.ParcelsService service.
type ParcelsServiceClient interface {
	GetParcelsWithImprovementSummaryByParcelId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error)
	GetParcelsWithImprovementSummaryByFeatureId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetNumericalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error)
	// Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
	GetCategoricalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetCategoricalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelAttributeStatsByIdResponse], error)
	GetEquityComparables(context.Context, *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error)
	GetSalesComparables(context.Context, *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error)
	GetParcelIdsByFeatureId(context.Context, *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error)
	GetEstimatedParcelsExtentWGS84(context.Context, *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error)
	UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error)
}

// NewParcelsServiceClient constructs a client for the civil.public.parcels.v1.ParcelsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewParcelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ParcelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	parcelsServiceMethods := v1.File_civil_public_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	return &parcelsServiceClient{
		getParcelsWithImprovementSummaryByParcelId: connect.NewClient[v1.GetParcelsWithImprovementSummaryByParcelIdRequest, v1.GetParcelsWithImprovementSummaryByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getParcelsWithImprovementSummaryByFeatureId: connect.NewClient[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest, v1.GetParcelsWithImprovementSummaryByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getNumericalParcelAttributeStatsById: connect.NewClient[v1.GetNumericalParcelAttributeStatsByIdRequest, v1.GetNumericalParcelAttributeStatsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetNumericalParcelAttributeStatsById")),
			connect.WithClientOptions(opts...),
		),
		getCategoricalParcelAttributeStatsById: connect.NewClient[v1.GetCategoricalParcelAttributeStatsByIdRequest, v1.GetCategoricalParcelAttributeStatsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetCategoricalParcelAttributeStatsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetCategoricalParcelAttributeStatsById")),
			connect.WithClientOptions(opts...),
		),
		getEquityComparables: connect.NewClient[v1.GetEquityComparablesRequest, v1.GetEquityComparablesResponse](
			httpClient,
			baseURL+ParcelsServiceGetEquityComparablesProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetEquityComparables")),
			connect.WithClientOptions(opts...),
		),
		getSalesComparables: connect.NewClient[v1.GetSalesComparablesRequest, v1.GetSalesComparablesResponse](
			httpClient,
			baseURL+ParcelsServiceGetSalesComparablesProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetSalesComparables")),
			connect.WithClientOptions(opts...),
		),
		getParcelIdsByFeatureId: connect.NewClient[v1.GetParcelIdsByFeatureIdRequest, v1.GetParcelIdsByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelIdsByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelIdsByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getEstimatedParcelsExtentWGS84: connect.NewClient[v1.GetEstimatedParcelsExtentWGS84Request, v1.GetEstimatedParcelsExtentWGS84Response](
			httpClient,
			baseURL+ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetEstimatedParcelsExtentWGS84")),
			connect.WithClientOptions(opts...),
		),
		updateParcel: connect.NewClient[v1.UpdateParcelRequest, v1.UpdateParcelResponse](
			httpClient,
			baseURL+ParcelsServiceUpdateParcelProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("UpdateParcel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// parcelsServiceClient implements ParcelsServiceClient.
type parcelsServiceClient struct {
	getParcelsWithImprovementSummaryByParcelId  *connect.Client[v1.GetParcelsWithImprovementSummaryByParcelIdRequest, v1.GetParcelsWithImprovementSummaryByParcelIdResponse]
	getParcelsWithImprovementSummaryByFeatureId *connect.Client[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest, v1.GetParcelsWithImprovementSummaryByFeatureIdResponse]
	getNumericalParcelAttributeStatsById        *connect.Client[v1.GetNumericalParcelAttributeStatsByIdRequest, v1.GetNumericalParcelAttributeStatsByIdResponse]
	getCategoricalParcelAttributeStatsById      *connect.Client[v1.GetCategoricalParcelAttributeStatsByIdRequest, v1.GetCategoricalParcelAttributeStatsByIdResponse]
	getEquityComparables                        *connect.Client[v1.GetEquityComparablesRequest, v1.GetEquityComparablesResponse]
	getSalesComparables                         *connect.Client[v1.GetSalesComparablesRequest, v1.GetSalesComparablesResponse]
	getParcelIdsByFeatureId                     *connect.Client[v1.GetParcelIdsByFeatureIdRequest, v1.GetParcelIdsByFeatureIdResponse]
	getEstimatedParcelsExtentWGS84              *connect.Client[v1.GetEstimatedParcelsExtentWGS84Request, v1.GetEstimatedParcelsExtentWGS84Response]
	updateParcel                                *connect.Client[v1.UpdateParcelRequest, v1.UpdateParcelResponse]
}

// GetParcelsWithImprovementSummaryByParcelId calls
// civil.public.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByParcelId.
func (c *parcelsServiceClient) GetParcelsWithImprovementSummaryByParcelId(ctx context.Context, req *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error) {
	return c.getParcelsWithImprovementSummaryByParcelId.CallUnary(ctx, req)
}

// GetParcelsWithImprovementSummaryByFeatureId calls
// civil.public.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByFeatureId.
func (c *parcelsServiceClient) GetParcelsWithImprovementSummaryByFeatureId(ctx context.Context, req *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error) {
	return c.getParcelsWithImprovementSummaryByFeatureId.CallUnary(ctx, req)
}

// GetNumericalParcelAttributeStatsById calls
// civil.public.parcels.v1.ParcelsService.GetNumericalParcelAttributeStatsById.
func (c *parcelsServiceClient) GetNumericalParcelAttributeStatsById(ctx context.Context, req *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error) {
	return c.getNumericalParcelAttributeStatsById.CallUnary(ctx, req)
}

// GetCategoricalParcelAttributeStatsById calls
// civil.public.parcels.v1.ParcelsService.GetCategoricalParcelAttributeStatsById.
func (c *parcelsServiceClient) GetCategoricalParcelAttributeStatsById(ctx context.Context, req *connect.Request[v1.GetCategoricalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelAttributeStatsByIdResponse], error) {
	return c.getCategoricalParcelAttributeStatsById.CallUnary(ctx, req)
}

// GetEquityComparables calls civil.public.parcels.v1.ParcelsService.GetEquityComparables.
func (c *parcelsServiceClient) GetEquityComparables(ctx context.Context, req *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error) {
	return c.getEquityComparables.CallUnary(ctx, req)
}

// GetSalesComparables calls civil.public.parcels.v1.ParcelsService.GetSalesComparables.
func (c *parcelsServiceClient) GetSalesComparables(ctx context.Context, req *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error) {
	return c.getSalesComparables.CallUnary(ctx, req)
}

// GetParcelIdsByFeatureId calls civil.public.parcels.v1.ParcelsService.GetParcelIdsByFeatureId.
func (c *parcelsServiceClient) GetParcelIdsByFeatureId(ctx context.Context, req *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error) {
	return c.getParcelIdsByFeatureId.CallUnary(ctx, req)
}

// GetEstimatedParcelsExtentWGS84 calls
// civil.public.parcels.v1.ParcelsService.GetEstimatedParcelsExtentWGS84.
func (c *parcelsServiceClient) GetEstimatedParcelsExtentWGS84(ctx context.Context, req *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error) {
	return c.getEstimatedParcelsExtentWGS84.CallUnary(ctx, req)
}

// UpdateParcel calls civil.public.parcels.v1.ParcelsService.UpdateParcel.
func (c *parcelsServiceClient) UpdateParcel(ctx context.Context, req *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error) {
	return c.updateParcel.CallUnary(ctx, req)
}

// ParcelsServiceHandler is an implementation of the civil.public.parcels.v1.ParcelsService service.
type ParcelsServiceHandler interface {
	GetParcelsWithImprovementSummaryByParcelId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error)
	GetParcelsWithImprovementSummaryByFeatureId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetNumericalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error)
	// Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
	GetCategoricalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetCategoricalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelAttributeStatsByIdResponse], error)
	GetEquityComparables(context.Context, *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error)
	GetSalesComparables(context.Context, *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error)
	GetParcelIdsByFeatureId(context.Context, *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error)
	GetEstimatedParcelsExtentWGS84(context.Context, *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error)
	UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error)
}

// NewParcelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewParcelsServiceHandler(svc ParcelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	parcelsServiceMethods := v1.File_civil_public_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	parcelsServiceGetParcelsWithImprovementSummaryByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure,
		svc.GetParcelsWithImprovementSummaryByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetParcelsWithImprovementSummaryByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure,
		svc.GetParcelsWithImprovementSummaryByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetNumericalParcelAttributeStatsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure,
		svc.GetNumericalParcelAttributeStatsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetNumericalParcelAttributeStatsById")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetCategoricalParcelAttributeStatsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetCategoricalParcelAttributeStatsByIdProcedure,
		svc.GetCategoricalParcelAttributeStatsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetCategoricalParcelAttributeStatsById")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetEquityComparablesHandler := connect.NewUnaryHandler(
		ParcelsServiceGetEquityComparablesProcedure,
		svc.GetEquityComparables,
		connect.WithSchema(parcelsServiceMethods.ByName("GetEquityComparables")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetSalesComparablesHandler := connect.NewUnaryHandler(
		ParcelsServiceGetSalesComparablesProcedure,
		svc.GetSalesComparables,
		connect.WithSchema(parcelsServiceMethods.ByName("GetSalesComparables")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetParcelIdsByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelIdsByFeatureIdProcedure,
		svc.GetParcelIdsByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelIdsByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetEstimatedParcelsExtentWGS84Handler := connect.NewUnaryHandler(
		ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure,
		svc.GetEstimatedParcelsExtentWGS84,
		connect.WithSchema(parcelsServiceMethods.ByName("GetEstimatedParcelsExtentWGS84")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceUpdateParcelHandler := connect.NewUnaryHandler(
		ParcelsServiceUpdateParcelProcedure,
		svc.UpdateParcel,
		connect.WithSchema(parcelsServiceMethods.ByName("UpdateParcel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.parcels.v1.ParcelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure:
			parcelsServiceGetParcelsWithImprovementSummaryByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure:
			parcelsServiceGetParcelsWithImprovementSummaryByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure:
			parcelsServiceGetNumericalParcelAttributeStatsByIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetCategoricalParcelAttributeStatsByIdProcedure:
			parcelsServiceGetCategoricalParcelAttributeStatsByIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetEquityComparablesProcedure:
			parcelsServiceGetEquityComparablesHandler.ServeHTTP(w, r)
		case ParcelsServiceGetSalesComparablesProcedure:
			parcelsServiceGetSalesComparablesHandler.ServeHTTP(w, r)
		case ParcelsServiceGetParcelIdsByFeatureIdProcedure:
			parcelsServiceGetParcelIdsByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure:
			parcelsServiceGetEstimatedParcelsExtentWGS84Handler.ServeHTTP(w, r)
		case ParcelsServiceUpdateParcelProcedure:
			parcelsServiceUpdateParcelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedParcelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedParcelsServiceHandler struct{}

func (UnimplementedParcelsServiceHandler) GetParcelsWithImprovementSummaryByParcelId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetParcelsWithImprovementSummaryByFeatureId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetNumericalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetNumericalParcelAttributeStatsById is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetCategoricalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetCategoricalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelAttributeStatsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetCategoricalParcelAttributeStatsById is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetEquityComparables(context.Context, *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetEquityComparables is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetSalesComparables(context.Context, *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetSalesComparables is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetParcelIdsByFeatureId(context.Context, *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetParcelIdsByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetEstimatedParcelsExtentWGS84(context.Context, *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetEstimatedParcelsExtentWGS84 is not implemented"))
}

func (UnimplementedParcelsServiceHandler) UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.UpdateParcel is not implemented"))
}
