// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/parcels/v1/parcels.proto

package parcelsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/parcels/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ParcelsServiceName is the fully-qualified name of the ParcelsService service.
	ParcelsServiceName = "civil.public.parcels.v1.ParcelsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ParcelsServiceGetParcelsByIdProcedure is the fully-qualified name of the ParcelsService's
	// GetParcelsById RPC.
	ParcelsServiceGetParcelsByIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetParcelsById"
	// ParcelsServiceUpdateParcelProcedure is the fully-qualified name of the ParcelsService's
	// UpdateParcel RPC.
	ParcelsServiceUpdateParcelProcedure = "/civil.public.parcels.v1.ParcelsService/UpdateParcel"
	// ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure is the fully-qualified name of the
	// ParcelsService's GetNumericalParcelAttributeStatsById RPC.
	ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetNumericalParcelAttributeStatsById"
	// ParcelsServiceGetCategoricalAttributeParcelStatsByIdProcedure is the fully-qualified name of the
	// ParcelsService's GetCategoricalAttributeParcelStatsById RPC.
	ParcelsServiceGetCategoricalAttributeParcelStatsByIdProcedure = "/civil.public.parcels.v1.ParcelsService/GetCategoricalAttributeParcelStatsById"
)

// ParcelsServiceClient is a client for the civil.public.parcels.v1.ParcelsService service.
type ParcelsServiceClient interface {
	// Retrieves all of a specified parcel's attributes as an object.
	GetParcelsById(context.Context, *connect.Request[v1.GetParcelsByIdRequest]) (*connect.Response[v1.GetParcelsByIdResponse], error)
	UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetNumericalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error)
	// Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
	GetCategoricalAttributeParcelStatsById(context.Context, *connect.Request[v1.GetCategoricalAttributeParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalAttributeParcelStatsByIdResponse], error)
}

// NewParcelsServiceClient constructs a client for the civil.public.parcels.v1.ParcelsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewParcelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ParcelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	parcelsServiceMethods := v1.File_civil_public_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	return &parcelsServiceClient{
		getParcelsById: connect.NewClient[v1.GetParcelsByIdRequest, v1.GetParcelsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsById")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateParcel: connect.NewClient[v1.UpdateParcelRequest, v1.UpdateParcelResponse](
			httpClient,
			baseURL+ParcelsServiceUpdateParcelProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("UpdateParcel")),
			connect.WithClientOptions(opts...),
		),
		getNumericalParcelAttributeStatsById: connect.NewClient[v1.GetNumericalParcelAttributeStatsByIdRequest, v1.GetNumericalParcelAttributeStatsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetNumericalParcelAttributeStatsById")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getCategoricalAttributeParcelStatsById: connect.NewClient[v1.GetCategoricalAttributeParcelStatsByIdRequest, v1.GetCategoricalAttributeParcelStatsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetCategoricalAttributeParcelStatsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetCategoricalAttributeParcelStatsById")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// parcelsServiceClient implements ParcelsServiceClient.
type parcelsServiceClient struct {
	getParcelsById                         *connect.Client[v1.GetParcelsByIdRequest, v1.GetParcelsByIdResponse]
	updateParcel                           *connect.Client[v1.UpdateParcelRequest, v1.UpdateParcelResponse]
	getNumericalParcelAttributeStatsById   *connect.Client[v1.GetNumericalParcelAttributeStatsByIdRequest, v1.GetNumericalParcelAttributeStatsByIdResponse]
	getCategoricalAttributeParcelStatsById *connect.Client[v1.GetCategoricalAttributeParcelStatsByIdRequest, v1.GetCategoricalAttributeParcelStatsByIdResponse]
}

// GetParcelsById calls civil.public.parcels.v1.ParcelsService.GetParcelsById.
func (c *parcelsServiceClient) GetParcelsById(ctx context.Context, req *connect.Request[v1.GetParcelsByIdRequest]) (*connect.Response[v1.GetParcelsByIdResponse], error) {
	return c.getParcelsById.CallUnary(ctx, req)
}

// UpdateParcel calls civil.public.parcels.v1.ParcelsService.UpdateParcel.
func (c *parcelsServiceClient) UpdateParcel(ctx context.Context, req *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error) {
	return c.updateParcel.CallUnary(ctx, req)
}

// GetNumericalParcelAttributeStatsById calls
// civil.public.parcels.v1.ParcelsService.GetNumericalParcelAttributeStatsById.
func (c *parcelsServiceClient) GetNumericalParcelAttributeStatsById(ctx context.Context, req *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error) {
	return c.getNumericalParcelAttributeStatsById.CallUnary(ctx, req)
}

// GetCategoricalAttributeParcelStatsById calls
// civil.public.parcels.v1.ParcelsService.GetCategoricalAttributeParcelStatsById.
func (c *parcelsServiceClient) GetCategoricalAttributeParcelStatsById(ctx context.Context, req *connect.Request[v1.GetCategoricalAttributeParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalAttributeParcelStatsByIdResponse], error) {
	return c.getCategoricalAttributeParcelStatsById.CallUnary(ctx, req)
}

// ParcelsServiceHandler is an implementation of the civil.public.parcels.v1.ParcelsService service.
type ParcelsServiceHandler interface {
	// Retrieves all of a specified parcel's attributes as an object.
	GetParcelsById(context.Context, *connect.Request[v1.GetParcelsByIdRequest]) (*connect.Response[v1.GetParcelsByIdResponse], error)
	UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetNumericalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error)
	// Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
	GetCategoricalAttributeParcelStatsById(context.Context, *connect.Request[v1.GetCategoricalAttributeParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalAttributeParcelStatsByIdResponse], error)
}

// NewParcelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewParcelsServiceHandler(svc ParcelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	parcelsServiceMethods := v1.File_civil_public_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	parcelsServiceGetParcelsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelsByIdProcedure,
		svc.GetParcelsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsById")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceUpdateParcelHandler := connect.NewUnaryHandler(
		ParcelsServiceUpdateParcelProcedure,
		svc.UpdateParcel,
		connect.WithSchema(parcelsServiceMethods.ByName("UpdateParcel")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetNumericalParcelAttributeStatsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure,
		svc.GetNumericalParcelAttributeStatsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetNumericalParcelAttributeStatsById")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetCategoricalAttributeParcelStatsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetCategoricalAttributeParcelStatsByIdProcedure,
		svc.GetCategoricalAttributeParcelStatsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetCategoricalAttributeParcelStatsById")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.parcels.v1.ParcelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ParcelsServiceGetParcelsByIdProcedure:
			parcelsServiceGetParcelsByIdHandler.ServeHTTP(w, r)
		case ParcelsServiceUpdateParcelProcedure:
			parcelsServiceUpdateParcelHandler.ServeHTTP(w, r)
		case ParcelsServiceGetNumericalParcelAttributeStatsByIdProcedure:
			parcelsServiceGetNumericalParcelAttributeStatsByIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetCategoricalAttributeParcelStatsByIdProcedure:
			parcelsServiceGetCategoricalAttributeParcelStatsByIdHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedParcelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedParcelsServiceHandler struct{}

func (UnimplementedParcelsServiceHandler) GetParcelsById(context.Context, *connect.Request[v1.GetParcelsByIdRequest]) (*connect.Response[v1.GetParcelsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetParcelsById is not implemented"))
}

func (UnimplementedParcelsServiceHandler) UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.UpdateParcel is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetNumericalParcelAttributeStatsById(context.Context, *connect.Request[v1.GetNumericalParcelAttributeStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelAttributeStatsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetNumericalParcelAttributeStatsById is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetCategoricalAttributeParcelStatsById(context.Context, *connect.Request[v1.GetCategoricalAttributeParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalAttributeParcelStatsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.parcels.v1.ParcelsService.GetCategoricalAttributeParcelStatsById is not implemented"))
}
