// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: civil/public/tiles/v1/tiles.proto

package tilesv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetParcelTilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Z             int32                  `protobuf:"varint,1,opt,name=z,proto3" json:"z,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelTilesRequest) Reset() {
	*x = GetParcelTilesRequest{}
	mi := &file_civil_public_tiles_v1_tiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelTilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelTilesRequest) ProtoMessage() {}

func (x *GetParcelTilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_tiles_v1_tiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelTilesRequest.ProtoReflect.Descriptor instead.
func (*GetParcelTilesRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_tiles_v1_tiles_proto_rawDescGZIP(), []int{0}
}

func (x *GetParcelTilesRequest) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *GetParcelTilesRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GetParcelTilesRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetParcelTilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelTilesResponse) Reset() {
	*x = GetParcelTilesResponse{}
	mi := &file_civil_public_tiles_v1_tiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelTilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelTilesResponse) ProtoMessage() {}

func (x *GetParcelTilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_tiles_v1_tiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelTilesResponse.ProtoReflect.Descriptor instead.
func (*GetParcelTilesResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_tiles_v1_tiles_proto_rawDescGZIP(), []int{1}
}

func (x *GetParcelTilesResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetParcelTilesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_civil_public_tiles_v1_tiles_proto protoreflect.FileDescriptor

const file_civil_public_tiles_v1_tiles_proto_rawDesc = "" +
	"\n" +
	"!civil/public/tiles/v1/tiles.proto\x12\x15civil.public.tiles.v1\x1a\x1cgoogle/api/annotations.proto\"A\n" +
	"\x15GetParcelTilesRequest\x12\f\n" +
	"\x01z\x18\x01 \x01(\x05R\x01z\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"O\n" +
	"\x16GetParcelTilesResponse\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xaa\x01\n" +
	"\vTileService\x12\x9a\x01\n" +
	"\x0eGetParcelTiles\x12,.civil.public.tiles.v1.GetParcelTilesRequest\x1a-.civil.public.tiles.v1.GetParcelTilesResponse\"+\x82\xd3\xe4\x93\x02%\x12#/tiles/get_parcel_tiles/{z}/{x}/{y}B\xe2\x01\n" +
	"\x19com.civil.public.tiles.v1B\n" +
	"TilesProtoP\x01Z@github.com/civil-labs/civil-api-go/civil/public/tiles/v1;tilesv1\xa2\x02\x03CPT\xaa\x02\x15Civil.Public.Tiles.V1\xca\x02\x16Civil\\Public_\\Tiles\\V1\xe2\x02\"Civil\\Public_\\Tiles\\V1\\GPBMetadata\xea\x02\x18Civil::Public::Tiles::V1b\x06proto3"

var (
	file_civil_public_tiles_v1_tiles_proto_rawDescOnce sync.Once
	file_civil_public_tiles_v1_tiles_proto_rawDescData []byte
)

func file_civil_public_tiles_v1_tiles_proto_rawDescGZIP() []byte {
	file_civil_public_tiles_v1_tiles_proto_rawDescOnce.Do(func() {
		file_civil_public_tiles_v1_tiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_public_tiles_v1_tiles_proto_rawDesc), len(file_civil_public_tiles_v1_tiles_proto_rawDesc)))
	})
	return file_civil_public_tiles_v1_tiles_proto_rawDescData
}

var file_civil_public_tiles_v1_tiles_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_civil_public_tiles_v1_tiles_proto_goTypes = []any{
	(*GetParcelTilesRequest)(nil),  // 0: civil.public.tiles.v1.GetParcelTilesRequest
	(*GetParcelTilesResponse)(nil), // 1: civil.public.tiles.v1.GetParcelTilesResponse
}
var file_civil_public_tiles_v1_tiles_proto_depIdxs = []int32{
	0, // 0: civil.public.tiles.v1.TileService.GetParcelTiles:input_type -> civil.public.tiles.v1.GetParcelTilesRequest
	1, // 1: civil.public.tiles.v1.TileService.GetParcelTiles:output_type -> civil.public.tiles.v1.GetParcelTilesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_civil_public_tiles_v1_tiles_proto_init() }
func file_civil_public_tiles_v1_tiles_proto_init() {
	if File_civil_public_tiles_v1_tiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_public_tiles_v1_tiles_proto_rawDesc), len(file_civil_public_tiles_v1_tiles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_public_tiles_v1_tiles_proto_goTypes,
		DependencyIndexes: file_civil_public_tiles_v1_tiles_proto_depIdxs,
		MessageInfos:      file_civil_public_tiles_v1_tiles_proto_msgTypes,
	}.Build()
	File_civil_public_tiles_v1_tiles_proto = out.File
	file_civil_public_tiles_v1_tiles_proto_goTypes = nil
	file_civil_public_tiles_v1_tiles_proto_depIdxs = nil
}
