// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: civil/mesh/improvements/v1/improvements.proto

package improvementsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImprovementType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImprovementType) Reset() {
	*x = ImprovementType{}
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprovementType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprovementType) ProtoMessage() {}

func (x *ImprovementType) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprovementType.ProtoReflect.Descriptor instead.
func (*ImprovementType) Descriptor() ([]byte, []int) {
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP(), []int{0}
}

func (x *ImprovementType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImprovementType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImprovementType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImprovementType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetImprovementTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImprovementTypesRequest) Reset() {
	*x = GetImprovementTypesRequest{}
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementTypesRequest) ProtoMessage() {}

func (x *GetImprovementTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementTypesRequest.ProtoReflect.Descriptor instead.
func (*GetImprovementTypesRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP(), []int{1}
}

type GetImprovementTypesResponse struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ImprovementTypes map[string]*ImprovementType `protobuf:"bytes,1,rep,name=improvement_types,json=improvementTypes,proto3" json:"improvement_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetImprovementTypesResponse) Reset() {
	*x = GetImprovementTypesResponse{}
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementTypesResponse) ProtoMessage() {}

func (x *GetImprovementTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementTypesResponse.ProtoReflect.Descriptor instead.
func (*GetImprovementTypesResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP(), []int{2}
}

func (x *GetImprovementTypesResponse) GetImprovementTypes() map[string]*ImprovementType {
	if x != nil {
		return x.ImprovementTypes
	}
	return nil
}

type ImprovementCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Set to optional to allow it to properly pass zero values
	DepreciationModifier *float32 `protobuf:"fixed32,3,opt,name=depreciation_modifier,json=depreciationModifier,proto3,oneof" json:"depreciation_modifier,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImprovementCondition) Reset() {
	*x = ImprovementCondition{}
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprovementCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprovementCondition) ProtoMessage() {}

func (x *ImprovementCondition) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprovementCondition.ProtoReflect.Descriptor instead.
func (*ImprovementCondition) Descriptor() ([]byte, []int) {
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP(), []int{3}
}

func (x *ImprovementCondition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImprovementCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImprovementCondition) GetDepreciationModifier() float32 {
	if x != nil && x.DepreciationModifier != nil {
		return *x.DepreciationModifier
	}
	return 0
}

type GetImprovementConditionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImprovementConditionsRequest) Reset() {
	*x = GetImprovementConditionsRequest{}
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementConditionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementConditionsRequest) ProtoMessage() {}

func (x *GetImprovementConditionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementConditionsRequest.ProtoReflect.Descriptor instead.
func (*GetImprovementConditionsRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP(), []int{4}
}

type GetImprovementConditionsResponse struct {
	state                 protoimpl.MessageState           `protogen:"open.v1"`
	ImprovementConditions map[string]*ImprovementCondition `protobuf:"bytes,1,rep,name=improvement_conditions,json=improvementConditions,proto3" json:"improvement_conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetImprovementConditionsResponse) Reset() {
	*x = GetImprovementConditionsResponse{}
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementConditionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementConditionsResponse) ProtoMessage() {}

func (x *GetImprovementConditionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_improvements_v1_improvements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementConditionsResponse.ProtoReflect.Descriptor instead.
func (*GetImprovementConditionsResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP(), []int{5}
}

func (x *GetImprovementConditionsResponse) GetImprovementConditions() map[string]*ImprovementCondition {
	if x != nil {
		return x.ImprovementConditions
	}
	return nil
}

var File_civil_mesh_improvements_v1_improvements_proto protoreflect.FileDescriptor

const file_civil_mesh_improvements_v1_improvements_proto_rawDesc = "" +
	"\n" +
	"-civil/mesh/improvements/v1/improvements.proto\x12\x1acivil.mesh.improvements.v1\"k\n" +
	"\x0fImprovementType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x1c\n" +
	"\x1aGetImprovementTypesRequest\"\x8b\x02\n" +
	"\x1bGetImprovementTypesResponse\x12z\n" +
	"\x11improvement_types\x18\x01 \x03(\v2M.civil.mesh.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntryR\x10improvementTypes\x1ap\n" +
	"\x15ImprovementTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.civil.mesh.improvements.v1.ImprovementTypeR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x14ImprovementCondition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x15depreciation_modifier\x18\x03 \x01(\x02H\x00R\x14depreciationModifier\x88\x01\x01B\x18\n" +
	"\x16_depreciation_modifier\"!\n" +
	"\x1fGetImprovementConditionsRequest\"\xaf\x02\n" +
	" GetImprovementConditionsResponse\x12\x8e\x01\n" +
	"\x16improvement_conditions\x18\x01 \x03(\v2W.civil.mesh.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntryR\x15improvementConditions\x1az\n" +
	"\x1aImprovementConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.civil.mesh.improvements.v1.ImprovementConditionR\x05value:\x028\x012\xba\x02\n" +
	"\x13ImprovementsService\x12\x88\x01\n" +
	"\x13GetImprovementTypes\x126.civil.mesh.improvements.v1.GetImprovementTypesRequest\x1a7.civil.mesh.improvements.v1.GetImprovementTypesResponse\"\x00\x12\x97\x01\n" +
	"\x18GetImprovementConditions\x12;.civil.mesh.improvements.v1.GetImprovementConditionsRequest\x1a<.civil.mesh.improvements.v1.GetImprovementConditionsResponse\"\x00B\x8c\x02\n" +
	"\x1ecom.civil.mesh.improvements.v1B\x11ImprovementsProtoP\x01ZLgithub.com/civil-labs/civil-api-go/civil/mesh/improvements/v1;improvementsv1\xa2\x02\x03CMI\xaa\x02\x1aCivil.Mesh.Improvements.V1\xca\x02\x1aCivil\\Mesh\\Improvements\\V1\xe2\x02&Civil\\Mesh\\Improvements\\V1\\GPBMetadata\xea\x02\x1dCivil::Mesh::Improvements::V1b\x06proto3"

var (
	file_civil_mesh_improvements_v1_improvements_proto_rawDescOnce sync.Once
	file_civil_mesh_improvements_v1_improvements_proto_rawDescData []byte
)

func file_civil_mesh_improvements_v1_improvements_proto_rawDescGZIP() []byte {
	file_civil_mesh_improvements_v1_improvements_proto_rawDescOnce.Do(func() {
		file_civil_mesh_improvements_v1_improvements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_mesh_improvements_v1_improvements_proto_rawDesc), len(file_civil_mesh_improvements_v1_improvements_proto_rawDesc)))
	})
	return file_civil_mesh_improvements_v1_improvements_proto_rawDescData
}

var file_civil_mesh_improvements_v1_improvements_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_civil_mesh_improvements_v1_improvements_proto_goTypes = []any{
	(*ImprovementType)(nil),                  // 0: civil.mesh.improvements.v1.ImprovementType
	(*GetImprovementTypesRequest)(nil),       // 1: civil.mesh.improvements.v1.GetImprovementTypesRequest
	(*GetImprovementTypesResponse)(nil),      // 2: civil.mesh.improvements.v1.GetImprovementTypesResponse
	(*ImprovementCondition)(nil),             // 3: civil.mesh.improvements.v1.ImprovementCondition
	(*GetImprovementConditionsRequest)(nil),  // 4: civil.mesh.improvements.v1.GetImprovementConditionsRequest
	(*GetImprovementConditionsResponse)(nil), // 5: civil.mesh.improvements.v1.GetImprovementConditionsResponse
	nil,                                      // 6: civil.mesh.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntry
	nil,                                      // 7: civil.mesh.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntry
}
var file_civil_mesh_improvements_v1_improvements_proto_depIdxs = []int32{
	6, // 0: civil.mesh.improvements.v1.GetImprovementTypesResponse.improvement_types:type_name -> civil.mesh.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntry
	7, // 1: civil.mesh.improvements.v1.GetImprovementConditionsResponse.improvement_conditions:type_name -> civil.mesh.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntry
	0, // 2: civil.mesh.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntry.value:type_name -> civil.mesh.improvements.v1.ImprovementType
	3, // 3: civil.mesh.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntry.value:type_name -> civil.mesh.improvements.v1.ImprovementCondition
	1, // 4: civil.mesh.improvements.v1.ImprovementsService.GetImprovementTypes:input_type -> civil.mesh.improvements.v1.GetImprovementTypesRequest
	4, // 5: civil.mesh.improvements.v1.ImprovementsService.GetImprovementConditions:input_type -> civil.mesh.improvements.v1.GetImprovementConditionsRequest
	2, // 6: civil.mesh.improvements.v1.ImprovementsService.GetImprovementTypes:output_type -> civil.mesh.improvements.v1.GetImprovementTypesResponse
	5, // 7: civil.mesh.improvements.v1.ImprovementsService.GetImprovementConditions:output_type -> civil.mesh.improvements.v1.GetImprovementConditionsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_civil_mesh_improvements_v1_improvements_proto_init() }
func file_civil_mesh_improvements_v1_improvements_proto_init() {
	if File_civil_mesh_improvements_v1_improvements_proto != nil {
		return
	}
	file_civil_mesh_improvements_v1_improvements_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_mesh_improvements_v1_improvements_proto_rawDesc), len(file_civil_mesh_improvements_v1_improvements_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_mesh_improvements_v1_improvements_proto_goTypes,
		DependencyIndexes: file_civil_mesh_improvements_v1_improvements_proto_depIdxs,
		MessageInfos:      file_civil_mesh_improvements_v1_improvements_proto_msgTypes,
	}.Build()
	File_civil_mesh_improvements_v1_improvements_proto = out.File
	file_civil_mesh_improvements_v1_improvements_proto_goTypes = nil
	file_civil_mesh_improvements_v1_improvements_proto_depIdxs = nil
}
