// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: civil/mesh/parcels/v1/parcels.proto

package parcelsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetParcelAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	AttributeName string                 `protobuf:"bytes,2,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelAttributeRequest) Reset() {
	*x = GetParcelAttributeRequest{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelAttributeRequest) ProtoMessage() {}

func (x *GetParcelAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetParcelAttributeRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{0}
}

func (x *GetParcelAttributeRequest) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

func (x *GetParcelAttributeRequest) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

type GetParcelAttributeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttributeValue string                 `protobuf:"bytes,3,opt,name=attribute_value,json=attributeValue,proto3" json:"attribute_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetParcelAttributeResponse) Reset() {
	*x = GetParcelAttributeResponse{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelAttributeResponse) ProtoMessage() {}

func (x *GetParcelAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetParcelAttributeResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{1}
}

func (x *GetParcelAttributeResponse) GetAttributeValue() string {
	if x != nil {
		return x.AttributeValue
	}
	return ""
}

type GetParcelPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	PropertyName  string                 `protobuf:"bytes,2,opt,name=property_name,json=propertyName,proto3" json:"property_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelPropertyRequest) Reset() {
	*x = GetParcelPropertyRequest{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelPropertyRequest) ProtoMessage() {}

func (x *GetParcelPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetParcelPropertyRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{2}
}

func (x *GetParcelPropertyRequest) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

func (x *GetParcelPropertyRequest) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

type GetParcelPropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyValue string                 `protobuf:"bytes,3,opt,name=property_value,json=propertyValue,proto3" json:"property_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelPropertyResponse) Reset() {
	*x = GetParcelPropertyResponse{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelPropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelPropertyResponse) ProtoMessage() {}

func (x *GetParcelPropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelPropertyResponse.ProtoReflect.Descriptor instead.
func (*GetParcelPropertyResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{3}
}

func (x *GetParcelPropertyResponse) GetPropertyValue() string {
	if x != nil {
		return x.PropertyValue
	}
	return ""
}

var File_civil_mesh_parcels_v1_parcels_proto protoreflect.FileDescriptor

const file_civil_mesh_parcels_v1_parcels_proto_rawDesc = "" +
	"\n" +
	"#civil/mesh/parcels/v1/parcels.proto\x12\x15civil.mesh.parcels.v1\x1a\x1bbuf/validate/validate.proto\"v\n" +
	"\x19GetParcelAttributeRequest\x12'\n" +
	"\tparcel_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\bparcelId\x120\n" +
	"\x0eattribute_name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18?R\rattributeName\"Q\n" +
	"\x1aGetParcelAttributeResponse\x123\n" +
	"\x0fattribute_value\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x0eattributeValue\"s\n" +
	"\x18GetParcelPropertyRequest\x12'\n" +
	"\tparcel_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\bparcelId\x12.\n" +
	"\rproperty_name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18?R\fpropertyName\"N\n" +
	"\x19GetParcelPropertyResponse\x121\n" +
	"\x0eproperty_value\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\rpropertyValue2\x87\x02\n" +
	"\x0eParcelsService\x12{\n" +
	"\x12GetParcelAttribute\x120.civil.mesh.parcels.v1.GetParcelAttributeRequest\x1a1.civil.mesh.parcels.v1.GetParcelAttributeResponse\"\x00\x12x\n" +
	"\x11GetParcelProperty\x12/.civil.mesh.parcels.v1.GetParcelPropertyRequest\x1a0.civil.mesh.parcels.v1.GetParcelPropertyResponse\"\x00B\xe4\x01\n" +
	"\x19com.civil.mesh.parcels.v1B\fParcelsProtoP\x01ZBgithub.com/civil-labs/civil-api-go/civil/mesh/parcels/v1;parcelsv1\xa2\x02\x03CMP\xaa\x02\x15Civil.Mesh.Parcels.V1\xca\x02\x15Civil\\Mesh\\Parcels\\V1\xe2\x02!Civil\\Mesh\\Parcels\\V1\\GPBMetadata\xea\x02\x18Civil::Mesh::Parcels::V1b\x06proto3"

var (
	file_civil_mesh_parcels_v1_parcels_proto_rawDescOnce sync.Once
	file_civil_mesh_parcels_v1_parcels_proto_rawDescData []byte
)

func file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP() []byte {
	file_civil_mesh_parcels_v1_parcels_proto_rawDescOnce.Do(func() {
		file_civil_mesh_parcels_v1_parcels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_mesh_parcels_v1_parcels_proto_rawDesc), len(file_civil_mesh_parcels_v1_parcels_proto_rawDesc)))
	})
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescData
}

var file_civil_mesh_parcels_v1_parcels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_civil_mesh_parcels_v1_parcels_proto_goTypes = []any{
	(*GetParcelAttributeRequest)(nil),  // 0: civil.mesh.parcels.v1.GetParcelAttributeRequest
	(*GetParcelAttributeResponse)(nil), // 1: civil.mesh.parcels.v1.GetParcelAttributeResponse
	(*GetParcelPropertyRequest)(nil),   // 2: civil.mesh.parcels.v1.GetParcelPropertyRequest
	(*GetParcelPropertyResponse)(nil),  // 3: civil.mesh.parcels.v1.GetParcelPropertyResponse
}
var file_civil_mesh_parcels_v1_parcels_proto_depIdxs = []int32{
	0, // 0: civil.mesh.parcels.v1.ParcelsService.GetParcelAttribute:input_type -> civil.mesh.parcels.v1.GetParcelAttributeRequest
	2, // 1: civil.mesh.parcels.v1.ParcelsService.GetParcelProperty:input_type -> civil.mesh.parcels.v1.GetParcelPropertyRequest
	1, // 2: civil.mesh.parcels.v1.ParcelsService.GetParcelAttribute:output_type -> civil.mesh.parcels.v1.GetParcelAttributeResponse
	3, // 3: civil.mesh.parcels.v1.ParcelsService.GetParcelProperty:output_type -> civil.mesh.parcels.v1.GetParcelPropertyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_civil_mesh_parcels_v1_parcels_proto_init() }
func file_civil_mesh_parcels_v1_parcels_proto_init() {
	if File_civil_mesh_parcels_v1_parcels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_mesh_parcels_v1_parcels_proto_rawDesc), len(file_civil_mesh_parcels_v1_parcels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_mesh_parcels_v1_parcels_proto_goTypes,
		DependencyIndexes: file_civil_mesh_parcels_v1_parcels_proto_depIdxs,
		MessageInfos:      file_civil_mesh_parcels_v1_parcels_proto_msgTypes,
	}.Build()
	File_civil_mesh_parcels_v1_parcels_proto = out.File
	file_civil_mesh_parcels_v1_parcels_proto_goTypes = nil
	file_civil_mesh_parcels_v1_parcels_proto_depIdxs = nil
}
