// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: civil/mesh/parcels/v1/parcels.proto

package parcelsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParcelAffordances struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxFar         *float64               `protobuf:"fixed64,1,opt,name=max_far,json=maxFar,proto3,oneof" json:"max_far,omitempty"`
	MinLotSizeSqFt *float64               `protobuf:"fixed64,2,opt,name=min_lot_size_sq_ft,json=minLotSizeSqFt,proto3,oneof" json:"min_lot_size_sq_ft,omitempty"`
	MaxHeightFt    *float64               `protobuf:"fixed64,3,opt,name=max_height_ft,json=maxHeightFt,proto3,oneof" json:"max_height_ft,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParcelAffordances) Reset() {
	*x = ParcelAffordances{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParcelAffordances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParcelAffordances) ProtoMessage() {}

func (x *ParcelAffordances) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParcelAffordances.ProtoReflect.Descriptor instead.
func (*ParcelAffordances) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{0}
}

func (x *ParcelAffordances) GetMaxFar() float64 {
	if x != nil && x.MaxFar != nil {
		return *x.MaxFar
	}
	return 0
}

func (x *ParcelAffordances) GetMinLotSizeSqFt() float64 {
	if x != nil && x.MinLotSizeSqFt != nil {
		return *x.MinLotSizeSqFt
	}
	return 0
}

func (x *ParcelAffordances) GetMaxHeightFt() float64 {
	if x != nil && x.MaxHeightFt != nil {
		return *x.MaxHeightFt
	}
	return 0
}

type ParcelImprovementsSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ImprovementIds      []string               `protobuf:"bytes,1,rep,name=improvement_ids,json=improvementIds,proto3" json:"improvement_ids,omitempty"`
	TotalAreaSqFt       *float64               `protobuf:"fixed64,2,opt,name=total_area_sq_ft,json=totalAreaSqFt,proto3,oneof" json:"total_area_sq_ft,omitempty"`
	TotalBathrooms      *int32                 `protobuf:"varint,3,opt,name=total_bathrooms,json=totalBathrooms,proto3,oneof" json:"total_bathrooms,omitempty"`
	TotalBedrooms       *int32                 `protobuf:"varint,4,opt,name=total_bedrooms,json=totalBedrooms,proto3,oneof" json:"total_bedrooms,omitempty"`
	TotalUnits          *int32                 `protobuf:"varint,5,opt,name=total_units,json=totalUnits,proto3,oneof" json:"total_units,omitempty"`
	OldestYearBuilt     *int32                 `protobuf:"varint,6,opt,name=oldest_year_built,json=oldestYearBuilt,proto3,oneof" json:"oldest_year_built,omitempty"`
	NewestYearBuilt     *int32                 `protobuf:"varint,7,opt,name=newest_year_built,json=newestYearBuilt,proto3,oneof" json:"newest_year_built,omitempty"`
	LowestConditionNum  *int32                 `protobuf:"varint,8,opt,name=lowest_condition_num,json=lowestConditionNum,proto3,oneof" json:"lowest_condition_num,omitempty"`
	HighestConditionNum *int32                 `protobuf:"varint,9,opt,name=highest_condition_num,json=highestConditionNum,proto3,oneof" json:"highest_condition_num,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ParcelImprovementsSummary) Reset() {
	*x = ParcelImprovementsSummary{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParcelImprovementsSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParcelImprovementsSummary) ProtoMessage() {}

func (x *ParcelImprovementsSummary) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParcelImprovementsSummary.ProtoReflect.Descriptor instead.
func (*ParcelImprovementsSummary) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{1}
}

func (x *ParcelImprovementsSummary) GetImprovementIds() []string {
	if x != nil {
		return x.ImprovementIds
	}
	return nil
}

func (x *ParcelImprovementsSummary) GetTotalAreaSqFt() float64 {
	if x != nil && x.TotalAreaSqFt != nil {
		return *x.TotalAreaSqFt
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetTotalBathrooms() int32 {
	if x != nil && x.TotalBathrooms != nil {
		return *x.TotalBathrooms
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetTotalBedrooms() int32 {
	if x != nil && x.TotalBedrooms != nil {
		return *x.TotalBedrooms
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetTotalUnits() int32 {
	if x != nil && x.TotalUnits != nil {
		return *x.TotalUnits
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetOldestYearBuilt() int32 {
	if x != nil && x.OldestYearBuilt != nil {
		return *x.OldestYearBuilt
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetNewestYearBuilt() int32 {
	if x != nil && x.NewestYearBuilt != nil {
		return *x.NewestYearBuilt
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetLowestConditionNum() int32 {
	if x != nil && x.LowestConditionNum != nil {
		return *x.LowestConditionNum
	}
	return 0
}

func (x *ParcelImprovementsSummary) GetHighestConditionNum() int32 {
	if x != nil && x.HighestConditionNum != nil {
		return *x.HighestConditionNum
	}
	return 0
}

type Parcel struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	ParcelId                 string                     `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Address                  string                     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AddressId                string                     `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	OwnerName                string                     `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerAddress             string                     `protobuf:"bytes,5,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	OwnerId                  string                     `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	LandAreaSqFt             float64                    `protobuf:"fixed64,7,opt,name=land_area_sq_ft,json=landAreaSqFt,proto3" json:"land_area_sq_ft,omitempty"`
	LandUse                  string                     `protobuf:"bytes,8,opt,name=land_use,json=landUse,proto3" json:"land_use,omitempty"`
	LandUseCode              *string                    `protobuf:"bytes,9,opt,name=land_use_code,json=landUseCode,proto3,oneof" json:"land_use_code,omitempty"`
	Neighborhood             *string                    `protobuf:"bytes,10,opt,name=neighborhood,proto3,oneof" json:"neighborhood,omitempty"`
	MarketArea               *string                    `protobuf:"bytes,11,opt,name=market_area,json=marketArea,proto3,oneof" json:"market_area,omitempty"`
	Zoning                   []string                   `protobuf:"bytes,12,rep,name=zoning,proto3" json:"zoning,omitempty"`
	ZoningCodes              []string                   `protobuf:"bytes,13,rep,name=zoning_codes,json=zoningCodes,proto3" json:"zoning_codes,omitempty"`
	MarketLandValue          string                     `protobuf:"bytes,14,opt,name=market_land_value,json=marketLandValue,proto3" json:"market_land_value,omitempty"`
	AssessedLandValue        string                     `protobuf:"bytes,15,opt,name=assessed_land_value,json=assessedLandValue,proto3" json:"assessed_land_value,omitempty"`
	MarketImprovementValue   string                     `protobuf:"bytes,16,opt,name=market_improvement_value,json=marketImprovementValue,proto3" json:"market_improvement_value,omitempty"`
	AssessedImprovementValue string                     `protobuf:"bytes,17,opt,name=assessed_improvement_value,json=assessedImprovementValue,proto3" json:"assessed_improvement_value,omitempty"`
	Affordances              *ParcelAffordances         `protobuf:"bytes,18,opt,name=affordances,proto3" json:"affordances,omitempty"`
	ImprovementSummary       *ParcelImprovementsSummary `protobuf:"bytes,19,opt,name=improvement_summary,json=improvementSummary,proto3" json:"improvement_summary,omitempty"`
	Properties               string                     `protobuf:"bytes,20,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Parcel) Reset() {
	*x = Parcel{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parcel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parcel) ProtoMessage() {}

func (x *Parcel) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parcel.ProtoReflect.Descriptor instead.
func (*Parcel) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{2}
}

func (x *Parcel) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

func (x *Parcel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Parcel) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Parcel) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Parcel) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *Parcel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Parcel) GetLandAreaSqFt() float64 {
	if x != nil {
		return x.LandAreaSqFt
	}
	return 0
}

func (x *Parcel) GetLandUse() string {
	if x != nil {
		return x.LandUse
	}
	return ""
}

func (x *Parcel) GetLandUseCode() string {
	if x != nil && x.LandUseCode != nil {
		return *x.LandUseCode
	}
	return ""
}

func (x *Parcel) GetNeighborhood() string {
	if x != nil && x.Neighborhood != nil {
		return *x.Neighborhood
	}
	return ""
}

func (x *Parcel) GetMarketArea() string {
	if x != nil && x.MarketArea != nil {
		return *x.MarketArea
	}
	return ""
}

func (x *Parcel) GetZoning() []string {
	if x != nil {
		return x.Zoning
	}
	return nil
}

func (x *Parcel) GetZoningCodes() []string {
	if x != nil {
		return x.ZoningCodes
	}
	return nil
}

func (x *Parcel) GetMarketLandValue() string {
	if x != nil {
		return x.MarketLandValue
	}
	return ""
}

func (x *Parcel) GetAssessedLandValue() string {
	if x != nil {
		return x.AssessedLandValue
	}
	return ""
}

func (x *Parcel) GetMarketImprovementValue() string {
	if x != nil {
		return x.MarketImprovementValue
	}
	return ""
}

func (x *Parcel) GetAssessedImprovementValue() string {
	if x != nil {
		return x.AssessedImprovementValue
	}
	return ""
}

func (x *Parcel) GetAffordances() *ParcelAffordances {
	if x != nil {
		return x.Affordances
	}
	return nil
}

func (x *Parcel) GetImprovementSummary() *ParcelImprovementsSummary {
	if x != nil {
		return x.ImprovementSummary
	}
	return nil
}

func (x *Parcel) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

type GetParcelsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelIds     []string               `protobuf:"bytes,1,rep,name=parcel_ids,json=parcelIds,proto3" json:"parcel_ids,omitempty"`
	LegalAsOf     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=legal_as_of,json=legalAsOf,proto3,oneof" json:"legal_as_of,omitempty"`
	SystemAsOf    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=system_as_of,json=systemAsOf,proto3,oneof" json:"system_as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelsByIdRequest) Reset() {
	*x = GetParcelsByIdRequest{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelsByIdRequest) ProtoMessage() {}

func (x *GetParcelsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetParcelsByIdRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{3}
}

func (x *GetParcelsByIdRequest) GetParcelIds() []string {
	if x != nil {
		return x.ParcelIds
	}
	return nil
}

func (x *GetParcelsByIdRequest) GetLegalAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.LegalAsOf
	}
	return nil
}

func (x *GetParcelsByIdRequest) GetSystemAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.SystemAsOf
	}
	return nil
}

type GetParcelsByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parcels       map[string]*Parcel     `protobuf:"bytes,1,rep,name=parcels,proto3" json:"parcels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParcelsByIdResponse) Reset() {
	*x = GetParcelsByIdResponse{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParcelsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelsByIdResponse) ProtoMessage() {}

func (x *GetParcelsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelsByIdResponse.ProtoReflect.Descriptor instead.
func (*GetParcelsByIdResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{4}
}

func (x *GetParcelsByIdResponse) GetParcels() map[string]*Parcel {
	if x != nil {
		return x.Parcels
	}
	return nil
}

type UpdateParcelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParcelRequest) Reset() {
	*x = UpdateParcelRequest{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelRequest) ProtoMessage() {}

func (x *UpdateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelRequest.ProtoReflect.Descriptor instead.
func (*UpdateParcelRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{5}
}

type UpdateParcelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParcelResponse) Reset() {
	*x = UpdateParcelResponse{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelResponse) ProtoMessage() {}

func (x *UpdateParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelResponse.ProtoReflect.Descriptor instead.
func (*UpdateParcelResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{6}
}

type GetNumericalParcelStatsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNumericalParcelStatsByIdRequest) Reset() {
	*x = GetNumericalParcelStatsByIdRequest{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNumericalParcelStatsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumericalParcelStatsByIdRequest) ProtoMessage() {}

func (x *GetNumericalParcelStatsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumericalParcelStatsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetNumericalParcelStatsByIdRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{7}
}

type GetNumericalParcelStatsByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNumericalParcelStatsByIdResponse) Reset() {
	*x = GetNumericalParcelStatsByIdResponse{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNumericalParcelStatsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumericalParcelStatsByIdResponse) ProtoMessage() {}

func (x *GetNumericalParcelStatsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumericalParcelStatsByIdResponse.ProtoReflect.Descriptor instead.
func (*GetNumericalParcelStatsByIdResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{8}
}

type GetCategoricalParcelStatsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoricalParcelStatsByIdRequest) Reset() {
	*x = GetCategoricalParcelStatsByIdRequest{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoricalParcelStatsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoricalParcelStatsByIdRequest) ProtoMessage() {}

func (x *GetCategoricalParcelStatsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoricalParcelStatsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCategoricalParcelStatsByIdRequest) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{9}
}

type GetCategoricalParcelStatsByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoricalParcelStatsByIdResponse) Reset() {
	*x = GetCategoricalParcelStatsByIdResponse{}
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoricalParcelStatsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoricalParcelStatsByIdResponse) ProtoMessage() {}

func (x *GetCategoricalParcelStatsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_mesh_parcels_v1_parcels_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoricalParcelStatsByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCategoricalParcelStatsByIdResponse) Descriptor() ([]byte, []int) {
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP(), []int{10}
}

var File_civil_mesh_parcels_v1_parcels_proto protoreflect.FileDescriptor

const file_civil_mesh_parcels_v1_parcels_proto_rawDesc = "" +
	"\n" +
	"#civil/mesh/parcels/v1/parcels.proto\x12\x15civil.mesh.parcels.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x11ParcelAffordances\x12\x1c\n" +
	"\amax_far\x18\x01 \x01(\x01H\x00R\x06maxFar\x88\x01\x01\x12/\n" +
	"\x12min_lot_size_sq_ft\x18\x02 \x01(\x01H\x01R\x0eminLotSizeSqFt\x88\x01\x01\x12'\n" +
	"\rmax_height_ft\x18\x03 \x01(\x01H\x02R\vmaxHeightFt\x88\x01\x01B\n" +
	"\n" +
	"\b_max_farB\x15\n" +
	"\x13_min_lot_size_sq_ftB\x10\n" +
	"\x0e_max_height_ft\"\xef\x04\n" +
	"\x19ParcelImprovementsSummary\x12'\n" +
	"\x0fimprovement_ids\x18\x01 \x03(\tR\x0eimprovementIds\x12,\n" +
	"\x10total_area_sq_ft\x18\x02 \x01(\x01H\x00R\rtotalAreaSqFt\x88\x01\x01\x12,\n" +
	"\x0ftotal_bathrooms\x18\x03 \x01(\x05H\x01R\x0etotalBathrooms\x88\x01\x01\x12*\n" +
	"\x0etotal_bedrooms\x18\x04 \x01(\x05H\x02R\rtotalBedrooms\x88\x01\x01\x12$\n" +
	"\vtotal_units\x18\x05 \x01(\x05H\x03R\n" +
	"totalUnits\x88\x01\x01\x12/\n" +
	"\x11oldest_year_built\x18\x06 \x01(\x05H\x04R\x0foldestYearBuilt\x88\x01\x01\x12/\n" +
	"\x11newest_year_built\x18\a \x01(\x05H\x05R\x0fnewestYearBuilt\x88\x01\x01\x125\n" +
	"\x14lowest_condition_num\x18\b \x01(\x05H\x06R\x12lowestConditionNum\x88\x01\x01\x127\n" +
	"\x15highest_condition_num\x18\t \x01(\x05H\aR\x13highestConditionNum\x88\x01\x01B\x13\n" +
	"\x11_total_area_sq_ftB\x12\n" +
	"\x10_total_bathroomsB\x11\n" +
	"\x0f_total_bedroomsB\x0e\n" +
	"\f_total_unitsB\x14\n" +
	"\x12_oldest_year_builtB\x14\n" +
	"\x12_newest_year_builtB\x17\n" +
	"\x15_lowest_condition_numB\x18\n" +
	"\x16_highest_condition_num\"\x88\a\n" +
	"\x06Parcel\x12\x1b\n" +
	"\tparcel_id\x18\x01 \x01(\tR\bparcelId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\x12#\n" +
	"\rowner_address\x18\x05 \x01(\tR\fownerAddress\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12%\n" +
	"\x0fland_area_sq_ft\x18\a \x01(\x01R\flandAreaSqFt\x12\x19\n" +
	"\bland_use\x18\b \x01(\tR\alandUse\x12'\n" +
	"\rland_use_code\x18\t \x01(\tH\x00R\vlandUseCode\x88\x01\x01\x12'\n" +
	"\fneighborhood\x18\n" +
	" \x01(\tH\x01R\fneighborhood\x88\x01\x01\x12$\n" +
	"\vmarket_area\x18\v \x01(\tH\x02R\n" +
	"marketArea\x88\x01\x01\x12\x16\n" +
	"\x06zoning\x18\f \x03(\tR\x06zoning\x12!\n" +
	"\fzoning_codes\x18\r \x03(\tR\vzoningCodes\x12*\n" +
	"\x11market_land_value\x18\x0e \x01(\tR\x0fmarketLandValue\x12.\n" +
	"\x13assessed_land_value\x18\x0f \x01(\tR\x11assessedLandValue\x128\n" +
	"\x18market_improvement_value\x18\x10 \x01(\tR\x16marketImprovementValue\x12<\n" +
	"\x1aassessed_improvement_value\x18\x11 \x01(\tR\x18assessedImprovementValue\x12J\n" +
	"\vaffordances\x18\x12 \x01(\v2(.civil.mesh.parcels.v1.ParcelAffordancesR\vaffordances\x12a\n" +
	"\x13improvement_summary\x18\x13 \x01(\v20.civil.mesh.parcels.v1.ParcelImprovementsSummaryR\x12improvementSummary\x12\x1e\n" +
	"\n" +
	"properties\x18\x14 \x01(\tR\n" +
	"propertiesB\x10\n" +
	"\x0e_land_use_codeB\x0f\n" +
	"\r_neighborhoodB\x0e\n" +
	"\f_market_area\"\xdb\x01\n" +
	"\x15GetParcelsByIdRequest\x12\x1d\n" +
	"\n" +
	"parcel_ids\x18\x01 \x03(\tR\tparcelIds\x12?\n" +
	"\vlegal_as_of\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tlegalAsOf\x88\x01\x01\x12A\n" +
	"\fsystem_as_of\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"systemAsOf\x88\x01\x01B\x0e\n" +
	"\f_legal_as_ofB\x0f\n" +
	"\r_system_as_of\"\xc9\x01\n" +
	"\x16GetParcelsByIdResponse\x12T\n" +
	"\aparcels\x18\x01 \x03(\v2:.civil.mesh.parcels.v1.GetParcelsByIdResponse.ParcelsEntryR\aparcels\x1aY\n" +
	"\fParcelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.civil.mesh.parcels.v1.ParcelR\x05value:\x028\x01\"\x15\n" +
	"\x13UpdateParcelRequest\"\x16\n" +
	"\x14UpdateParcelResponse\"$\n" +
	"\"GetNumericalParcelStatsByIdRequest\"%\n" +
	"#GetNumericalParcelStatsByIdResponse\"&\n" +
	"$GetCategoricalParcelStatsByIdRequest\"'\n" +
	"%GetCategoricalParcelStatsByIdResponse2\xa4\x04\n" +
	"\x0eParcelsService\x12o\n" +
	"\x0eGetParcelsById\x12,.civil.mesh.parcels.v1.GetParcelsByIdRequest\x1a-.civil.mesh.parcels.v1.GetParcelsByIdResponse\"\x00\x12i\n" +
	"\fUpdateParcel\x12*.civil.mesh.parcels.v1.UpdateParcelRequest\x1a+.civil.mesh.parcels.v1.UpdateParcelResponse\"\x00\x12\x96\x01\n" +
	"\x1bGetNumericalParcelStatsById\x129.civil.mesh.parcels.v1.GetNumericalParcelStatsByIdRequest\x1a:.civil.mesh.parcels.v1.GetNumericalParcelStatsByIdResponse\"\x00\x12\x9c\x01\n" +
	"\x1dGetCategoricalParcelStatsById\x12;.civil.mesh.parcels.v1.GetCategoricalParcelStatsByIdRequest\x1a<.civil.mesh.parcels.v1.GetCategoricalParcelStatsByIdResponse\"\x00B\xe4\x01\n" +
	"\x19com.civil.mesh.parcels.v1B\fParcelsProtoP\x01ZBgithub.com/civil-labs/civil-api-go/civil/mesh/parcels/v1;parcelsv1\xa2\x02\x03CMP\xaa\x02\x15Civil.Mesh.Parcels.V1\xca\x02\x15Civil\\Mesh\\Parcels\\V1\xe2\x02!Civil\\Mesh\\Parcels\\V1\\GPBMetadata\xea\x02\x18Civil::Mesh::Parcels::V1b\x06proto3"

var (
	file_civil_mesh_parcels_v1_parcels_proto_rawDescOnce sync.Once
	file_civil_mesh_parcels_v1_parcels_proto_rawDescData []byte
)

func file_civil_mesh_parcels_v1_parcels_proto_rawDescGZIP() []byte {
	file_civil_mesh_parcels_v1_parcels_proto_rawDescOnce.Do(func() {
		file_civil_mesh_parcels_v1_parcels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_mesh_parcels_v1_parcels_proto_rawDesc), len(file_civil_mesh_parcels_v1_parcels_proto_rawDesc)))
	})
	return file_civil_mesh_parcels_v1_parcels_proto_rawDescData
}

var file_civil_mesh_parcels_v1_parcels_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_civil_mesh_parcels_v1_parcels_proto_goTypes = []any{
	(*ParcelAffordances)(nil),                     // 0: civil.mesh.parcels.v1.ParcelAffordances
	(*ParcelImprovementsSummary)(nil),             // 1: civil.mesh.parcels.v1.ParcelImprovementsSummary
	(*Parcel)(nil),                                // 2: civil.mesh.parcels.v1.Parcel
	(*GetParcelsByIdRequest)(nil),                 // 3: civil.mesh.parcels.v1.GetParcelsByIdRequest
	(*GetParcelsByIdResponse)(nil),                // 4: civil.mesh.parcels.v1.GetParcelsByIdResponse
	(*UpdateParcelRequest)(nil),                   // 5: civil.mesh.parcels.v1.UpdateParcelRequest
	(*UpdateParcelResponse)(nil),                  // 6: civil.mesh.parcels.v1.UpdateParcelResponse
	(*GetNumericalParcelStatsByIdRequest)(nil),    // 7: civil.mesh.parcels.v1.GetNumericalParcelStatsByIdRequest
	(*GetNumericalParcelStatsByIdResponse)(nil),   // 8: civil.mesh.parcels.v1.GetNumericalParcelStatsByIdResponse
	(*GetCategoricalParcelStatsByIdRequest)(nil),  // 9: civil.mesh.parcels.v1.GetCategoricalParcelStatsByIdRequest
	(*GetCategoricalParcelStatsByIdResponse)(nil), // 10: civil.mesh.parcels.v1.GetCategoricalParcelStatsByIdResponse
	nil,                           // 11: civil.mesh.parcels.v1.GetParcelsByIdResponse.ParcelsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_civil_mesh_parcels_v1_parcels_proto_depIdxs = []int32{
	0,  // 0: civil.mesh.parcels.v1.Parcel.affordances:type_name -> civil.mesh.parcels.v1.ParcelAffordances
	1,  // 1: civil.mesh.parcels.v1.Parcel.improvement_summary:type_name -> civil.mesh.parcels.v1.ParcelImprovementsSummary
	12, // 2: civil.mesh.parcels.v1.GetParcelsByIdRequest.legal_as_of:type_name -> google.protobuf.Timestamp
	12, // 3: civil.mesh.parcels.v1.GetParcelsByIdRequest.system_as_of:type_name -> google.protobuf.Timestamp
	11, // 4: civil.mesh.parcels.v1.GetParcelsByIdResponse.parcels:type_name -> civil.mesh.parcels.v1.GetParcelsByIdResponse.ParcelsEntry
	2,  // 5: civil.mesh.parcels.v1.GetParcelsByIdResponse.ParcelsEntry.value:type_name -> civil.mesh.parcels.v1.Parcel
	3,  // 6: civil.mesh.parcels.v1.ParcelsService.GetParcelsById:input_type -> civil.mesh.parcels.v1.GetParcelsByIdRequest
	5,  // 7: civil.mesh.parcels.v1.ParcelsService.UpdateParcel:input_type -> civil.mesh.parcels.v1.UpdateParcelRequest
	7,  // 8: civil.mesh.parcels.v1.ParcelsService.GetNumericalParcelStatsById:input_type -> civil.mesh.parcels.v1.GetNumericalParcelStatsByIdRequest
	9,  // 9: civil.mesh.parcels.v1.ParcelsService.GetCategoricalParcelStatsById:input_type -> civil.mesh.parcels.v1.GetCategoricalParcelStatsByIdRequest
	4,  // 10: civil.mesh.parcels.v1.ParcelsService.GetParcelsById:output_type -> civil.mesh.parcels.v1.GetParcelsByIdResponse
	6,  // 11: civil.mesh.parcels.v1.ParcelsService.UpdateParcel:output_type -> civil.mesh.parcels.v1.UpdateParcelResponse
	8,  // 12: civil.mesh.parcels.v1.ParcelsService.GetNumericalParcelStatsById:output_type -> civil.mesh.parcels.v1.GetNumericalParcelStatsByIdResponse
	10, // 13: civil.mesh.parcels.v1.ParcelsService.GetCategoricalParcelStatsById:output_type -> civil.mesh.parcels.v1.GetCategoricalParcelStatsByIdResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_civil_mesh_parcels_v1_parcels_proto_init() }
func file_civil_mesh_parcels_v1_parcels_proto_init() {
	if File_civil_mesh_parcels_v1_parcels_proto != nil {
		return
	}
	file_civil_mesh_parcels_v1_parcels_proto_msgTypes[0].OneofWrappers = []any{}
	file_civil_mesh_parcels_v1_parcels_proto_msgTypes[1].OneofWrappers = []any{}
	file_civil_mesh_parcels_v1_parcels_proto_msgTypes[2].OneofWrappers = []any{}
	file_civil_mesh_parcels_v1_parcels_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_mesh_parcels_v1_parcels_proto_rawDesc), len(file_civil_mesh_parcels_v1_parcels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_mesh_parcels_v1_parcels_proto_goTypes,
		DependencyIndexes: file_civil_mesh_parcels_v1_parcels_proto_depIdxs,
		MessageInfos:      file_civil_mesh_parcels_v1_parcels_proto_msgTypes,
	}.Build()
	File_civil_mesh_parcels_v1_parcels_proto = out.File
	file_civil_mesh_parcels_v1_parcels_proto_goTypes = nil
	file_civil_mesh_parcels_v1_parcels_proto_depIdxs = nil
}
