// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/tiles/v1/tiles.proto

package tilesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/tiles/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TileServiceName is the fully-qualified name of the TileService service.
	TileServiceName = "civil.public.tiles.v1.TileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TileServiceGetTileJsonProcedure is the fully-qualified name of the TileService's GetTileJson RPC.
	TileServiceGetTileJsonProcedure = "/civil.public.tiles.v1.TileService/GetTileJson"
	// TileServiceGetTileProcedure is the fully-qualified name of the TileService's GetTile RPC.
	TileServiceGetTileProcedure = "/civil.public.tiles.v1.TileService/GetTile"
)

// TileServiceClient is a client for the civil.public.tiles.v1.TileService service.
type TileServiceClient interface {
	// GetTileJson retrieves the discovery metadata for a tile source.
	// Clients use this to configure map layers.
	GetTileJson(context.Context, *connect.Request[v1.GetTileJsonRequest]) (*connect.Response[v1.GetTileJsonResponse], error)
	// GetTile retrieves a vector tile (MVT/PBF) for a given coordinate.
	GetTile(context.Context, *connect.Request[v1.GetTileRequest]) (*connect.Response[v1.GetTileResponse], error)
}

// NewTileServiceClient constructs a client for the civil.public.tiles.v1.TileService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tileServiceMethods := v1.File_civil_public_tiles_v1_tiles_proto.Services().ByName("TileService").Methods()
	return &tileServiceClient{
		getTileJson: connect.NewClient[v1.GetTileJsonRequest, v1.GetTileJsonResponse](
			httpClient,
			baseURL+TileServiceGetTileJsonProcedure,
			connect.WithSchema(tileServiceMethods.ByName("GetTileJson")),
			connect.WithClientOptions(opts...),
		),
		getTile: connect.NewClient[v1.GetTileRequest, v1.GetTileResponse](
			httpClient,
			baseURL+TileServiceGetTileProcedure,
			connect.WithSchema(tileServiceMethods.ByName("GetTile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tileServiceClient implements TileServiceClient.
type tileServiceClient struct {
	getTileJson *connect.Client[v1.GetTileJsonRequest, v1.GetTileJsonResponse]
	getTile     *connect.Client[v1.GetTileRequest, v1.GetTileResponse]
}

// GetTileJson calls civil.public.tiles.v1.TileService.GetTileJson.
func (c *tileServiceClient) GetTileJson(ctx context.Context, req *connect.Request[v1.GetTileJsonRequest]) (*connect.Response[v1.GetTileJsonResponse], error) {
	return c.getTileJson.CallUnary(ctx, req)
}

// GetTile calls civil.public.tiles.v1.TileService.GetTile.
func (c *tileServiceClient) GetTile(ctx context.Context, req *connect.Request[v1.GetTileRequest]) (*connect.Response[v1.GetTileResponse], error) {
	return c.getTile.CallUnary(ctx, req)
}

// TileServiceHandler is an implementation of the civil.public.tiles.v1.TileService service.
type TileServiceHandler interface {
	// GetTileJson retrieves the discovery metadata for a tile source.
	// Clients use this to configure map layers.
	GetTileJson(context.Context, *connect.Request[v1.GetTileJsonRequest]) (*connect.Response[v1.GetTileJsonResponse], error)
	// GetTile retrieves a vector tile (MVT/PBF) for a given coordinate.
	GetTile(context.Context, *connect.Request[v1.GetTileRequest]) (*connect.Response[v1.GetTileResponse], error)
}

// NewTileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTileServiceHandler(svc TileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tileServiceMethods := v1.File_civil_public_tiles_v1_tiles_proto.Services().ByName("TileService").Methods()
	tileServiceGetTileJsonHandler := connect.NewUnaryHandler(
		TileServiceGetTileJsonProcedure,
		svc.GetTileJson,
		connect.WithSchema(tileServiceMethods.ByName("GetTileJson")),
		connect.WithHandlerOptions(opts...),
	)
	tileServiceGetTileHandler := connect.NewUnaryHandler(
		TileServiceGetTileProcedure,
		svc.GetTile,
		connect.WithSchema(tileServiceMethods.ByName("GetTile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.tiles.v1.TileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TileServiceGetTileJsonProcedure:
			tileServiceGetTileJsonHandler.ServeHTTP(w, r)
		case TileServiceGetTileProcedure:
			tileServiceGetTileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTileServiceHandler struct{}

func (UnimplementedTileServiceHandler) GetTileJson(context.Context, *connect.Request[v1.GetTileJsonRequest]) (*connect.Response[v1.GetTileJsonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.tiles.v1.TileService.GetTileJson is not implemented"))
}

func (UnimplementedTileServiceHandler) GetTile(context.Context, *connect.Request[v1.GetTileRequest]) (*connect.Response[v1.GetTileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.tiles.v1.TileService.GetTile is not implemented"))
}
