// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/tiles/v1/tiles.proto

package tilesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/tiles/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TileServiceName is the fully-qualified name of the TileService service.
	TileServiceName = "civil.public.tiles.v1.TileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TileServiceGetParcelTilesProcedure is the fully-qualified name of the TileService's
	// GetParcelTiles RPC.
	TileServiceGetParcelTilesProcedure = "/civil.public.tiles.v1.TileService/GetParcelTiles"
)

// TileServiceClient is a client for the civil.public.tiles.v1.TileService service.
type TileServiceClient interface {
	GetParcelTiles(context.Context, *connect.Request[v1.GetParcelTilesRequest]) (*connect.Response[v1.GetParcelTilesResponse], error)
}

// NewTileServiceClient constructs a client for the civil.public.tiles.v1.TileService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tileServiceMethods := v1.File_civil_public_tiles_v1_tiles_proto.Services().ByName("TileService").Methods()
	return &tileServiceClient{
		getParcelTiles: connect.NewClient[v1.GetParcelTilesRequest, v1.GetParcelTilesResponse](
			httpClient,
			baseURL+TileServiceGetParcelTilesProcedure,
			connect.WithSchema(tileServiceMethods.ByName("GetParcelTiles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tileServiceClient implements TileServiceClient.
type tileServiceClient struct {
	getParcelTiles *connect.Client[v1.GetParcelTilesRequest, v1.GetParcelTilesResponse]
}

// GetParcelTiles calls civil.public.tiles.v1.TileService.GetParcelTiles.
func (c *tileServiceClient) GetParcelTiles(ctx context.Context, req *connect.Request[v1.GetParcelTilesRequest]) (*connect.Response[v1.GetParcelTilesResponse], error) {
	return c.getParcelTiles.CallUnary(ctx, req)
}

// TileServiceHandler is an implementation of the civil.public.tiles.v1.TileService service.
type TileServiceHandler interface {
	GetParcelTiles(context.Context, *connect.Request[v1.GetParcelTilesRequest]) (*connect.Response[v1.GetParcelTilesResponse], error)
}

// NewTileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTileServiceHandler(svc TileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tileServiceMethods := v1.File_civil_public_tiles_v1_tiles_proto.Services().ByName("TileService").Methods()
	tileServiceGetParcelTilesHandler := connect.NewUnaryHandler(
		TileServiceGetParcelTilesProcedure,
		svc.GetParcelTiles,
		connect.WithSchema(tileServiceMethods.ByName("GetParcelTiles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.tiles.v1.TileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TileServiceGetParcelTilesProcedure:
			tileServiceGetParcelTilesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTileServiceHandler struct{}

func (UnimplementedTileServiceHandler) GetParcelTiles(context.Context, *connect.Request[v1.GetParcelTilesRequest]) (*connect.Response[v1.GetParcelTilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.tiles.v1.TileService.GetParcelTiles is not implemented"))
}
