// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/mesh/improvements/v1/improvements.proto

package improvementsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/mesh/improvements/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ImprovementsServiceName is the fully-qualified name of the ImprovementsService service.
	ImprovementsServiceName = "civil.mesh.improvements.v1.ImprovementsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ImprovementsServiceGetImprovementTypesProcedure is the fully-qualified name of the
	// ImprovementsService's GetImprovementTypes RPC.
	ImprovementsServiceGetImprovementTypesProcedure = "/civil.mesh.improvements.v1.ImprovementsService/GetImprovementTypes"
	// ImprovementsServiceGetImprovementConditionsProcedure is the fully-qualified name of the
	// ImprovementsService's GetImprovementConditions RPC.
	ImprovementsServiceGetImprovementConditionsProcedure = "/civil.mesh.improvements.v1.ImprovementsService/GetImprovementConditions"
)

// ImprovementsServiceClient is a client for the civil.mesh.improvements.v1.ImprovementsService
// service.
type ImprovementsServiceClient interface {
	GetImprovementTypes(context.Context, *connect.Request[v1.GetImprovementTypesRequest]) (*connect.Response[v1.GetImprovementTypesResponse], error)
	GetImprovementConditions(context.Context, *connect.Request[v1.GetImprovementConditionsRequest]) (*connect.Response[v1.GetImprovementConditionsResponse], error)
}

// NewImprovementsServiceClient constructs a client for the
// civil.mesh.improvements.v1.ImprovementsService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImprovementsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImprovementsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	improvementsServiceMethods := v1.File_civil_mesh_improvements_v1_improvements_proto.Services().ByName("ImprovementsService").Methods()
	return &improvementsServiceClient{
		getImprovementTypes: connect.NewClient[v1.GetImprovementTypesRequest, v1.GetImprovementTypesResponse](
			httpClient,
			baseURL+ImprovementsServiceGetImprovementTypesProcedure,
			connect.WithSchema(improvementsServiceMethods.ByName("GetImprovementTypes")),
			connect.WithClientOptions(opts...),
		),
		getImprovementConditions: connect.NewClient[v1.GetImprovementConditionsRequest, v1.GetImprovementConditionsResponse](
			httpClient,
			baseURL+ImprovementsServiceGetImprovementConditionsProcedure,
			connect.WithSchema(improvementsServiceMethods.ByName("GetImprovementConditions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// improvementsServiceClient implements ImprovementsServiceClient.
type improvementsServiceClient struct {
	getImprovementTypes      *connect.Client[v1.GetImprovementTypesRequest, v1.GetImprovementTypesResponse]
	getImprovementConditions *connect.Client[v1.GetImprovementConditionsRequest, v1.GetImprovementConditionsResponse]
}

// GetImprovementTypes calls civil.mesh.improvements.v1.ImprovementsService.GetImprovementTypes.
func (c *improvementsServiceClient) GetImprovementTypes(ctx context.Context, req *connect.Request[v1.GetImprovementTypesRequest]) (*connect.Response[v1.GetImprovementTypesResponse], error) {
	return c.getImprovementTypes.CallUnary(ctx, req)
}

// GetImprovementConditions calls
// civil.mesh.improvements.v1.ImprovementsService.GetImprovementConditions.
func (c *improvementsServiceClient) GetImprovementConditions(ctx context.Context, req *connect.Request[v1.GetImprovementConditionsRequest]) (*connect.Response[v1.GetImprovementConditionsResponse], error) {
	return c.getImprovementConditions.CallUnary(ctx, req)
}

// ImprovementsServiceHandler is an implementation of the
// civil.mesh.improvements.v1.ImprovementsService service.
type ImprovementsServiceHandler interface {
	GetImprovementTypes(context.Context, *connect.Request[v1.GetImprovementTypesRequest]) (*connect.Response[v1.GetImprovementTypesResponse], error)
	GetImprovementConditions(context.Context, *connect.Request[v1.GetImprovementConditionsRequest]) (*connect.Response[v1.GetImprovementConditionsResponse], error)
}

// NewImprovementsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImprovementsServiceHandler(svc ImprovementsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	improvementsServiceMethods := v1.File_civil_mesh_improvements_v1_improvements_proto.Services().ByName("ImprovementsService").Methods()
	improvementsServiceGetImprovementTypesHandler := connect.NewUnaryHandler(
		ImprovementsServiceGetImprovementTypesProcedure,
		svc.GetImprovementTypes,
		connect.WithSchema(improvementsServiceMethods.ByName("GetImprovementTypes")),
		connect.WithHandlerOptions(opts...),
	)
	improvementsServiceGetImprovementConditionsHandler := connect.NewUnaryHandler(
		ImprovementsServiceGetImprovementConditionsProcedure,
		svc.GetImprovementConditions,
		connect.WithSchema(improvementsServiceMethods.ByName("GetImprovementConditions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.mesh.improvements.v1.ImprovementsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImprovementsServiceGetImprovementTypesProcedure:
			improvementsServiceGetImprovementTypesHandler.ServeHTTP(w, r)
		case ImprovementsServiceGetImprovementConditionsProcedure:
			improvementsServiceGetImprovementConditionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImprovementsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImprovementsServiceHandler struct{}

func (UnimplementedImprovementsServiceHandler) GetImprovementTypes(context.Context, *connect.Request[v1.GetImprovementTypesRequest]) (*connect.Response[v1.GetImprovementTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.improvements.v1.ImprovementsService.GetImprovementTypes is not implemented"))
}

func (UnimplementedImprovementsServiceHandler) GetImprovementConditions(context.Context, *connect.Request[v1.GetImprovementConditionsRequest]) (*connect.Response[v1.GetImprovementConditionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.improvements.v1.ImprovementsService.GetImprovementConditions is not implemented"))
}
