// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: civil/public/dex/v1/dex.proto

package dexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret            string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	RedirectUris      []string               `protobuf:"bytes,3,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TrustedPeers      []string               `protobuf:"bytes,4,rep,name=trusted_peers,json=trustedPeers,proto3" json:"trusted_peers,omitempty"`
	Public            bool                   `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	Name              string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl           string                 `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	AllowedConnectors []string               `protobuf:"bytes,8,rep,name=allowed_connectors,json=allowedConnectors,proto3" json:"allowed_connectors,omitempty"`
	SsoSharedWith     []string               `protobuf:"bytes,9,rep,name=sso_shared_with,json=ssoSharedWith,proto3" json:"sso_shared_with,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Client) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *Client) GetTrustedPeers() []string {
	if x != nil {
		return x.TrustedPeers
	}
	return nil
}

func (x *Client) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Client) GetAllowedConnectors() []string {
	if x != nil {
		return x.AllowedConnectors
	}
	return nil
}

func (x *Client) GetSsoSharedWith() []string {
	if x != nil {
		return x.SsoSharedWith
	}
	return nil
}

// ClientInfo represents an OAuth2 client without sensitive information.
type ClientInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RedirectUris      []string               `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TrustedPeers      []string               `protobuf:"bytes,3,rep,name=trusted_peers,json=trustedPeers,proto3" json:"trusted_peers,omitempty"`
	Public            bool                   `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	Name              string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl           string                 `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	AllowedConnectors []string               `protobuf:"bytes,7,rep,name=allowed_connectors,json=allowedConnectors,proto3" json:"allowed_connectors,omitempty"`
	SsoSharedWith     []string               `protobuf:"bytes,8,rep,name=sso_shared_with,json=ssoSharedWith,proto3" json:"sso_shared_with,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{1}
}

func (x *ClientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientInfo) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *ClientInfo) GetTrustedPeers() []string {
	if x != nil {
		return x.TrustedPeers
	}
	return nil
}

func (x *ClientInfo) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *ClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientInfo) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ClientInfo) GetAllowedConnectors() []string {
	if x != nil {
		return x.AllowedConnectors
	}
	return nil
}

func (x *ClientInfo) GetSsoSharedWith() []string {
	if x != nil {
		return x.SsoSharedWith
	}
	return nil
}

// GetClientReq is a request to retrieve client details.
type GetClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the client.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetClientResp returns the client details.
type GetClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientResponse.ProtoReflect.Descriptor instead.
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// CreateClientReq is a request to make a client.
type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{4}
}

func (x *CreateClientRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// CreateClientResp returns the response from creating a client.
type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyExists bool                   `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClientResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

func (x *CreateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// DeleteClientReq is a request to delete a client.
type DeleteClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the client.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteClientResp determines if the client is deleted successfully.
type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotFound      bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClientResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

// UpdateClientReq is a request to update an existing client.
type UpdateClientRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RedirectUris      []string               `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	TrustedPeers      []string               `protobuf:"bytes,3,rep,name=trusted_peers,json=trustedPeers,proto3" json:"trusted_peers,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl           string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	AllowedConnectors []string               `protobuf:"bytes,6,rep,name=allowed_connectors,json=allowedConnectors,proto3" json:"allowed_connectors,omitempty"`
	SsoSharedWith     []string               `protobuf:"bytes,7,rep,name=sso_shared_with,json=ssoSharedWith,proto3" json:"sso_shared_with,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateClientRequest) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *UpdateClientRequest) GetTrustedPeers() []string {
	if x != nil {
		return x.TrustedPeers
	}
	return nil
}

func (x *UpdateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClientRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UpdateClientRequest) GetAllowedConnectors() []string {
	if x != nil {
		return x.AllowedConnectors
	}
	return nil
}

func (x *UpdateClientRequest) GetSsoSharedWith() []string {
	if x != nil {
		return x.SsoSharedWith
	}
	return nil
}

// UpdateClientResp returns the response from updating a client.
type UpdateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotFound      bool                   `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientResponse) Reset() {
	*x = UpdateClientResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientResponse) ProtoMessage() {}

func (x *UpdateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateClientResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

// ListClientReq is a request to enumerate clients.
type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{10}
}

// ListClientResp returns a list of clients.
type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientInfo          `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{11}
}

func (x *ListClientsResponse) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

// VersionReq is a request to fetch version info.
type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{12}
}

// VersionResp holds the version info of components.
type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semantic version of the server.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Numeric version of the API. It increases every time a new call is added to the API.
	// Clients should use this info to determine if the server supports specific features.
	Api           int32 `protobuf:"varint,2,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{13}
}

func (x *GetVersionResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GetVersionResponse) GetApi() int32 {
	if x != nil {
		return x.Api
	}
	return 0
}

// RefreshTokenRef contains the metadata for a refresh token that is managed by the storage.
type RefreshTokenRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the refresh token.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CreatedAt     int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsed      int64  `protobuf:"varint,6,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRef) Reset() {
	*x = RefreshTokenRef{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRef) ProtoMessage() {}

func (x *RefreshTokenRef) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRef.ProtoReflect.Descriptor instead.
func (*RefreshTokenRef) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefreshTokenRef) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshTokenRef) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RefreshTokenRef) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

// ListRefreshReq is a request to enumerate the refresh tokens of a user.
type ListRefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The "sub" claim returned in the ID Token.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefreshRequest) Reset() {
	*x = ListRefreshRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefreshRequest) ProtoMessage() {}

func (x *ListRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefreshRequest.ProtoReflect.Descriptor instead.
func (*ListRefreshRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{15}
}

func (x *ListRefreshRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListRefreshResp returns a list of refresh tokens for a user.
type ListRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshTokens []*RefreshTokenRef     `protobuf:"bytes,1,rep,name=refresh_tokens,json=refreshTokens,proto3" json:"refresh_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefreshResponse) Reset() {
	*x = ListRefreshResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefreshResponse) ProtoMessage() {}

func (x *ListRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefreshResponse.ProtoReflect.Descriptor instead.
func (*ListRefreshResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{16}
}

func (x *ListRefreshResponse) GetRefreshTokens() []*RefreshTokenRef {
	if x != nil {
		return x.RefreshTokens
	}
	return nil
}

// RevokeRefreshReq is a request to revoke the refresh token of the user-client pair.
type RevokeRefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The "sub" claim returned in the ID Token.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshRequest) Reset() {
	*x = RevokeRefreshRequest{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshRequest) ProtoMessage() {}

func (x *RevokeRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeRefreshRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRefreshRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// RevokeRefreshResp determines if the refresh token is revoked successfully.
type RevokeRefreshResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set to true is refresh token was not found and token could not be revoked.
	NotFound      bool `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshResponse) Reset() {
	*x = RevokeRefreshResponse{}
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshResponse) ProtoMessage() {}

func (x *RevokeRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_dex_v1_dex_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshResponse.ProtoReflect.Descriptor instead.
func (*RevokeRefreshResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_dex_v1_dex_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeRefreshResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

var File_civil_public_dex_v1_dex_proto protoreflect.FileDescriptor

const file_civil_public_dex_v1_dex_proto_rawDesc = "" +
	"\n" +
	"\x1dcivil/public/dex/v1/dex.proto\x12\x13civil.public.dex.v1\"\x98\x02\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12#\n" +
	"\rredirect_uris\x18\x03 \x03(\tR\fredirectUris\x12#\n" +
	"\rtrusted_peers\x18\x04 \x03(\tR\ftrustedPeers\x12\x16\n" +
	"\x06public\x18\x05 \x01(\bR\x06public\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\a \x01(\tR\alogoUrl\x12-\n" +
	"\x12allowed_connectors\x18\b \x03(\tR\x11allowedConnectors\x12&\n" +
	"\x0fsso_shared_with\x18\t \x03(\tR\rssoSharedWith\"\x84\x02\n" +
	"\n" +
	"ClientInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rredirect_uris\x18\x02 \x03(\tR\fredirectUris\x12#\n" +
	"\rtrusted_peers\x18\x03 \x03(\tR\ftrustedPeers\x12\x16\n" +
	"\x06public\x18\x04 \x01(\bR\x06public\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x06 \x01(\tR\alogoUrl\x12-\n" +
	"\x12allowed_connectors\x18\a \x03(\tR\x11allowedConnectors\x12&\n" +
	"\x0fsso_shared_with\x18\b \x03(\tR\rssoSharedWith\"\"\n" +
	"\x10GetClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x11GetClientResponse\x123\n" +
	"\x06client\x18\x01 \x01(\v2\x1b.civil.public.dex.v1.ClientR\x06client\"J\n" +
	"\x13CreateClientRequest\x123\n" +
	"\x06client\x18\x01 \x01(\v2\x1b.civil.public.dex.v1.ClientR\x06client\"r\n" +
	"\x14CreateClientResponse\x12%\n" +
	"\x0ealready_exists\x18\x01 \x01(\bR\ralreadyExists\x123\n" +
	"\x06client\x18\x02 \x01(\v2\x1b.civil.public.dex.v1.ClientR\x06client\"%\n" +
	"\x13DeleteClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x14DeleteClientResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\"\xf5\x01\n" +
	"\x13UpdateClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rredirect_uris\x18\x02 \x03(\tR\fredirectUris\x12#\n" +
	"\rtrusted_peers\x18\x03 \x03(\tR\ftrustedPeers\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12-\n" +
	"\x12allowed_connectors\x18\x06 \x03(\tR\x11allowedConnectors\x12&\n" +
	"\x0fsso_shared_with\x18\a \x03(\tR\rssoSharedWith\"3\n" +
	"\x14UpdateClientResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound\"\x14\n" +
	"\x12ListClientsRequest\"P\n" +
	"\x13ListClientsResponse\x129\n" +
	"\aclients\x18\x01 \x03(\v2\x1f.civil.public.dex.v1.ClientInfoR\aclients\"\x13\n" +
	"\x11GetVersionRequest\">\n" +
	"\x12GetVersionResponse\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x10\n" +
	"\x03api\x18\x02 \x01(\x05R\x03api\"z\n" +
	"\x0fRefreshTokenRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tlast_used\x18\x06 \x01(\x03R\blastUsed\"-\n" +
	"\x12ListRefreshRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"b\n" +
	"\x13ListRefreshResponse\x12K\n" +
	"\x0erefresh_tokens\x18\x01 \x03(\v2$.civil.public.dex.v1.RefreshTokenRefR\rrefreshTokens\"L\n" +
	"\x14RevokeRefreshRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"4\n" +
	"\x15RevokeRefreshResponse\x12\x1b\n" +
	"\tnot_found\x18\x01 \x01(\bR\bnotFound2\xb2\x06\n" +
	"\n" +
	"DexService\x12\\\n" +
	"\tGetClient\x12%.civil.public.dex.v1.GetClientRequest\x1a&.civil.public.dex.v1.GetClientResponse\"\x00\x12e\n" +
	"\fCreateClient\x12(.civil.public.dex.v1.CreateClientRequest\x1a).civil.public.dex.v1.CreateClientResponse\"\x00\x12e\n" +
	"\fUpdateClient\x12(.civil.public.dex.v1.UpdateClientRequest\x1a).civil.public.dex.v1.UpdateClientResponse\"\x00\x12e\n" +
	"\fDeleteClient\x12(.civil.public.dex.v1.DeleteClientRequest\x1a).civil.public.dex.v1.DeleteClientResponse\"\x00\x12b\n" +
	"\vListClients\x12'.civil.public.dex.v1.ListClientsRequest\x1a(.civil.public.dex.v1.ListClientsResponse\"\x00\x12_\n" +
	"\n" +
	"GetVersion\x12&.civil.public.dex.v1.GetVersionRequest\x1a'.civil.public.dex.v1.GetVersionResponse\"\x00\x12b\n" +
	"\vListRefresh\x12'.civil.public.dex.v1.ListRefreshRequest\x1a(.civil.public.dex.v1.ListRefreshResponse\"\x00\x12h\n" +
	"\rRevokeRefresh\x12).civil.public.dex.v1.RevokeRefreshRequest\x1a*.civil.public.dex.v1.RevokeRefreshResponse\"\x00B\xd2\x01\n" +
	"\x17com.civil.public.dex.v1B\bDexProtoP\x01Z<github.com/civil-labs/civil-api-go/civil/public/dex/v1;dexv1\xa2\x02\x03CPD\xaa\x02\x13Civil.Public.Dex.V1\xca\x02\x14Civil\\Public_\\Dex\\V1\xe2\x02 Civil\\Public_\\Dex\\V1\\GPBMetadata\xea\x02\x16Civil::Public::Dex::V1b\x06proto3"

var (
	file_civil_public_dex_v1_dex_proto_rawDescOnce sync.Once
	file_civil_public_dex_v1_dex_proto_rawDescData []byte
)

func file_civil_public_dex_v1_dex_proto_rawDescGZIP() []byte {
	file_civil_public_dex_v1_dex_proto_rawDescOnce.Do(func() {
		file_civil_public_dex_v1_dex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_public_dex_v1_dex_proto_rawDesc), len(file_civil_public_dex_v1_dex_proto_rawDesc)))
	})
	return file_civil_public_dex_v1_dex_proto_rawDescData
}

var file_civil_public_dex_v1_dex_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_civil_public_dex_v1_dex_proto_goTypes = []any{
	(*Client)(nil),                // 0: civil.public.dex.v1.Client
	(*ClientInfo)(nil),            // 1: civil.public.dex.v1.ClientInfo
	(*GetClientRequest)(nil),      // 2: civil.public.dex.v1.GetClientRequest
	(*GetClientResponse)(nil),     // 3: civil.public.dex.v1.GetClientResponse
	(*CreateClientRequest)(nil),   // 4: civil.public.dex.v1.CreateClientRequest
	(*CreateClientResponse)(nil),  // 5: civil.public.dex.v1.CreateClientResponse
	(*DeleteClientRequest)(nil),   // 6: civil.public.dex.v1.DeleteClientRequest
	(*DeleteClientResponse)(nil),  // 7: civil.public.dex.v1.DeleteClientResponse
	(*UpdateClientRequest)(nil),   // 8: civil.public.dex.v1.UpdateClientRequest
	(*UpdateClientResponse)(nil),  // 9: civil.public.dex.v1.UpdateClientResponse
	(*ListClientsRequest)(nil),    // 10: civil.public.dex.v1.ListClientsRequest
	(*ListClientsResponse)(nil),   // 11: civil.public.dex.v1.ListClientsResponse
	(*GetVersionRequest)(nil),     // 12: civil.public.dex.v1.GetVersionRequest
	(*GetVersionResponse)(nil),    // 13: civil.public.dex.v1.GetVersionResponse
	(*RefreshTokenRef)(nil),       // 14: civil.public.dex.v1.RefreshTokenRef
	(*ListRefreshRequest)(nil),    // 15: civil.public.dex.v1.ListRefreshRequest
	(*ListRefreshResponse)(nil),   // 16: civil.public.dex.v1.ListRefreshResponse
	(*RevokeRefreshRequest)(nil),  // 17: civil.public.dex.v1.RevokeRefreshRequest
	(*RevokeRefreshResponse)(nil), // 18: civil.public.dex.v1.RevokeRefreshResponse
}
var file_civil_public_dex_v1_dex_proto_depIdxs = []int32{
	0,  // 0: civil.public.dex.v1.GetClientResponse.client:type_name -> civil.public.dex.v1.Client
	0,  // 1: civil.public.dex.v1.CreateClientRequest.client:type_name -> civil.public.dex.v1.Client
	0,  // 2: civil.public.dex.v1.CreateClientResponse.client:type_name -> civil.public.dex.v1.Client
	1,  // 3: civil.public.dex.v1.ListClientsResponse.clients:type_name -> civil.public.dex.v1.ClientInfo
	14, // 4: civil.public.dex.v1.ListRefreshResponse.refresh_tokens:type_name -> civil.public.dex.v1.RefreshTokenRef
	2,  // 5: civil.public.dex.v1.DexService.GetClient:input_type -> civil.public.dex.v1.GetClientRequest
	4,  // 6: civil.public.dex.v1.DexService.CreateClient:input_type -> civil.public.dex.v1.CreateClientRequest
	8,  // 7: civil.public.dex.v1.DexService.UpdateClient:input_type -> civil.public.dex.v1.UpdateClientRequest
	6,  // 8: civil.public.dex.v1.DexService.DeleteClient:input_type -> civil.public.dex.v1.DeleteClientRequest
	10, // 9: civil.public.dex.v1.DexService.ListClients:input_type -> civil.public.dex.v1.ListClientsRequest
	12, // 10: civil.public.dex.v1.DexService.GetVersion:input_type -> civil.public.dex.v1.GetVersionRequest
	15, // 11: civil.public.dex.v1.DexService.ListRefresh:input_type -> civil.public.dex.v1.ListRefreshRequest
	17, // 12: civil.public.dex.v1.DexService.RevokeRefresh:input_type -> civil.public.dex.v1.RevokeRefreshRequest
	3,  // 13: civil.public.dex.v1.DexService.GetClient:output_type -> civil.public.dex.v1.GetClientResponse
	5,  // 14: civil.public.dex.v1.DexService.CreateClient:output_type -> civil.public.dex.v1.CreateClientResponse
	9,  // 15: civil.public.dex.v1.DexService.UpdateClient:output_type -> civil.public.dex.v1.UpdateClientResponse
	7,  // 16: civil.public.dex.v1.DexService.DeleteClient:output_type -> civil.public.dex.v1.DeleteClientResponse
	11, // 17: civil.public.dex.v1.DexService.ListClients:output_type -> civil.public.dex.v1.ListClientsResponse
	13, // 18: civil.public.dex.v1.DexService.GetVersion:output_type -> civil.public.dex.v1.GetVersionResponse
	16, // 19: civil.public.dex.v1.DexService.ListRefresh:output_type -> civil.public.dex.v1.ListRefreshResponse
	18, // 20: civil.public.dex.v1.DexService.RevokeRefresh:output_type -> civil.public.dex.v1.RevokeRefreshResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_civil_public_dex_v1_dex_proto_init() }
func file_civil_public_dex_v1_dex_proto_init() {
	if File_civil_public_dex_v1_dex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_public_dex_v1_dex_proto_rawDesc), len(file_civil_public_dex_v1_dex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_public_dex_v1_dex_proto_goTypes,
		DependencyIndexes: file_civil_public_dex_v1_dex_proto_depIdxs,
		MessageInfos:      file_civil_public_dex_v1_dex_proto_msgTypes,
	}.Build()
	File_civil_public_dex_v1_dex_proto = out.File
	file_civil_public_dex_v1_dex_proto_goTypes = nil
	file_civil_public_dex_v1_dex_proto_depIdxs = nil
}
