// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/config/v1/config.proto

package configv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/config/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "civil.public.config.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceGetInstanceMetadataProcedure is the fully-qualified name of the ConfigService's
	// GetInstanceMetadata RPC.
	ConfigServiceGetInstanceMetadataProcedure = "/civil.public.config.v1.ConfigService/GetInstanceMetadata"
)

// ConfigServiceClient is a client for the civil.public.config.v1.ConfigService service.
type ConfigServiceClient interface {
	GetInstanceMetadata(context.Context, *connect.Request[v1.GetInstanceMetadataRequest]) (*connect.Response[v1.GetInstanceMetadataResponse], error)
}

// NewConfigServiceClient constructs a client for the civil.public.config.v1.ConfigService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1.File_civil_public_config_v1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		getInstanceMetadata: connect.NewClient[v1.GetInstanceMetadataRequest, v1.GetInstanceMetadataResponse](
			httpClient,
			baseURL+ConfigServiceGetInstanceMetadataProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetInstanceMetadata")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	getInstanceMetadata *connect.Client[v1.GetInstanceMetadataRequest, v1.GetInstanceMetadataResponse]
}

// GetInstanceMetadata calls civil.public.config.v1.ConfigService.GetInstanceMetadata.
func (c *configServiceClient) GetInstanceMetadata(ctx context.Context, req *connect.Request[v1.GetInstanceMetadataRequest]) (*connect.Response[v1.GetInstanceMetadataResponse], error) {
	return c.getInstanceMetadata.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the civil.public.config.v1.ConfigService service.
type ConfigServiceHandler interface {
	GetInstanceMetadata(context.Context, *connect.Request[v1.GetInstanceMetadataRequest]) (*connect.Response[v1.GetInstanceMetadataResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1.File_civil_public_config_v1_config_proto.Services().ByName("ConfigService").Methods()
	configServiceGetInstanceMetadataHandler := connect.NewUnaryHandler(
		ConfigServiceGetInstanceMetadataProcedure,
		svc.GetInstanceMetadata,
		connect.WithSchema(configServiceMethods.ByName("GetInstanceMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.config.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceGetInstanceMetadataProcedure:
			configServiceGetInstanceMetadataHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) GetInstanceMetadata(context.Context, *connect.Request[v1.GetInstanceMetadataRequest]) (*connect.Response[v1.GetInstanceMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.config.v1.ConfigService.GetInstanceMetadata is not implemented"))
}
