// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/sales/v1/sales.proto

package salesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/sales/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SalesServiceName is the fully-qualified name of the SalesService service.
	SalesServiceName = "civil.public.sales.v1.SalesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SalesServiceGetSalesByParcelIdProcedure is the fully-qualified name of the SalesService's
	// GetSalesByParcelId RPC.
	SalesServiceGetSalesByParcelIdProcedure = "/civil.public.sales.v1.SalesService/GetSalesByParcelId"
	// SalesServiceGetSalesByPolygonProcedure is the fully-qualified name of the SalesService's
	// GetSalesByPolygon RPC.
	SalesServiceGetSalesByPolygonProcedure = "/civil.public.sales.v1.SalesService/GetSalesByPolygon"
)

// SalesServiceClient is a client for the civil.public.sales.v1.SalesService service.
type SalesServiceClient interface {
	// Retrieves all of a specified parcel's attributes as an object.
	GetSalesByParcelId(context.Context, *connect.Request[v1.GetSalesByParcelIdRequest]) (*connect.Response[v1.GetSalesByParcelIdResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetSalesByPolygon(context.Context, *connect.Request[v1.GetSalesByPolygonRequest]) (*connect.Response[v1.GetSalesByPolygonResponse], error)
}

// NewSalesServiceClient constructs a client for the civil.public.sales.v1.SalesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSalesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SalesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	salesServiceMethods := v1.File_civil_public_sales_v1_sales_proto.Services().ByName("SalesService").Methods()
	return &salesServiceClient{
		getSalesByParcelId: connect.NewClient[v1.GetSalesByParcelIdRequest, v1.GetSalesByParcelIdResponse](
			httpClient,
			baseURL+SalesServiceGetSalesByParcelIdProcedure,
			connect.WithSchema(salesServiceMethods.ByName("GetSalesByParcelId")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSalesByPolygon: connect.NewClient[v1.GetSalesByPolygonRequest, v1.GetSalesByPolygonResponse](
			httpClient,
			baseURL+SalesServiceGetSalesByPolygonProcedure,
			connect.WithSchema(salesServiceMethods.ByName("GetSalesByPolygon")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// salesServiceClient implements SalesServiceClient.
type salesServiceClient struct {
	getSalesByParcelId *connect.Client[v1.GetSalesByParcelIdRequest, v1.GetSalesByParcelIdResponse]
	getSalesByPolygon  *connect.Client[v1.GetSalesByPolygonRequest, v1.GetSalesByPolygonResponse]
}

// GetSalesByParcelId calls civil.public.sales.v1.SalesService.GetSalesByParcelId.
func (c *salesServiceClient) GetSalesByParcelId(ctx context.Context, req *connect.Request[v1.GetSalesByParcelIdRequest]) (*connect.Response[v1.GetSalesByParcelIdResponse], error) {
	return c.getSalesByParcelId.CallUnary(ctx, req)
}

// GetSalesByPolygon calls civil.public.sales.v1.SalesService.GetSalesByPolygon.
func (c *salesServiceClient) GetSalesByPolygon(ctx context.Context, req *connect.Request[v1.GetSalesByPolygonRequest]) (*connect.Response[v1.GetSalesByPolygonResponse], error) {
	return c.getSalesByPolygon.CallUnary(ctx, req)
}

// SalesServiceHandler is an implementation of the civil.public.sales.v1.SalesService service.
type SalesServiceHandler interface {
	// Retrieves all of a specified parcel's attributes as an object.
	GetSalesByParcelId(context.Context, *connect.Request[v1.GetSalesByParcelIdRequest]) (*connect.Response[v1.GetSalesByParcelIdResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetSalesByPolygon(context.Context, *connect.Request[v1.GetSalesByPolygonRequest]) (*connect.Response[v1.GetSalesByPolygonResponse], error)
}

// NewSalesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSalesServiceHandler(svc SalesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	salesServiceMethods := v1.File_civil_public_sales_v1_sales_proto.Services().ByName("SalesService").Methods()
	salesServiceGetSalesByParcelIdHandler := connect.NewUnaryHandler(
		SalesServiceGetSalesByParcelIdProcedure,
		svc.GetSalesByParcelId,
		connect.WithSchema(salesServiceMethods.ByName("GetSalesByParcelId")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	salesServiceGetSalesByPolygonHandler := connect.NewUnaryHandler(
		SalesServiceGetSalesByPolygonProcedure,
		svc.GetSalesByPolygon,
		connect.WithSchema(salesServiceMethods.ByName("GetSalesByPolygon")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.sales.v1.SalesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SalesServiceGetSalesByParcelIdProcedure:
			salesServiceGetSalesByParcelIdHandler.ServeHTTP(w, r)
		case SalesServiceGetSalesByPolygonProcedure:
			salesServiceGetSalesByPolygonHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSalesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSalesServiceHandler struct{}

func (UnimplementedSalesServiceHandler) GetSalesByParcelId(context.Context, *connect.Request[v1.GetSalesByParcelIdRequest]) (*connect.Response[v1.GetSalesByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.sales.v1.SalesService.GetSalesByParcelId is not implemented"))
}

func (UnimplementedSalesServiceHandler) GetSalesByPolygon(context.Context, *connect.Request[v1.GetSalesByPolygonRequest]) (*connect.Response[v1.GetSalesByPolygonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.sales.v1.SalesService.GetSalesByPolygon is not implemented"))
}
