// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: civil/public/zoning/v1/zoning.proto

package zoningv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zoning struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                    string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	MaxFar                  float32                `protobuf:"fixed32,4,opt,name=max_far,json=maxFar,proto3" json:"max_far,omitempty"`
	MinLotSizeSqFt          float32                `protobuf:"fixed32,5,opt,name=min_lot_size_sq_ft,json=minLotSizeSqFt,proto3" json:"min_lot_size_sq_ft,omitempty"`
	MaxHeightFt             float32                `protobuf:"fixed32,6,opt,name=max_height_ft,json=maxHeightFt,proto3" json:"max_height_ft,omitempty"`
	MaxDwellingUnitsPerAcre float32                `protobuf:"fixed32,7,opt,name=max_dwelling_units_per_acre,json=maxDwellingUnitsPerAcre,proto3" json:"max_dwelling_units_per_acre,omitempty"`
	MaxLotCoveragePct       float32                `protobuf:"fixed32,8,opt,name=max_lot_coverage_pct,json=maxLotCoveragePct,proto3" json:"max_lot_coverage_pct,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Zoning) Reset() {
	*x = Zoning{}
	mi := &file_civil_public_zoning_v1_zoning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zoning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zoning) ProtoMessage() {}

func (x *Zoning) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_zoning_v1_zoning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zoning.ProtoReflect.Descriptor instead.
func (*Zoning) Descriptor() ([]byte, []int) {
	return file_civil_public_zoning_v1_zoning_proto_rawDescGZIP(), []int{0}
}

func (x *Zoning) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zoning) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zoning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Zoning) GetMaxFar() float32 {
	if x != nil {
		return x.MaxFar
	}
	return 0
}

func (x *Zoning) GetMinLotSizeSqFt() float32 {
	if x != nil {
		return x.MinLotSizeSqFt
	}
	return 0
}

func (x *Zoning) GetMaxHeightFt() float32 {
	if x != nil {
		return x.MaxHeightFt
	}
	return 0
}

func (x *Zoning) GetMaxDwellingUnitsPerAcre() float32 {
	if x != nil {
		return x.MaxDwellingUnitsPerAcre
	}
	return 0
}

func (x *Zoning) GetMaxLotCoveragePct() float32 {
	if x != nil {
		return x.MaxLotCoveragePct
	}
	return 0
}

type GetZoningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoningRequest) Reset() {
	*x = GetZoningRequest{}
	mi := &file_civil_public_zoning_v1_zoning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoningRequest) ProtoMessage() {}

func (x *GetZoningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_zoning_v1_zoning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoningRequest.ProtoReflect.Descriptor instead.
func (*GetZoningRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_zoning_v1_zoning_proto_rawDescGZIP(), []int{1}
}

type GetZoningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zoning        map[string]*Zoning     `protobuf:"bytes,1,rep,name=zoning,proto3" json:"zoning,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoningResponse) Reset() {
	*x = GetZoningResponse{}
	mi := &file_civil_public_zoning_v1_zoning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoningResponse) ProtoMessage() {}

func (x *GetZoningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_zoning_v1_zoning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoningResponse.ProtoReflect.Descriptor instead.
func (*GetZoningResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_zoning_v1_zoning_proto_rawDescGZIP(), []int{2}
}

func (x *GetZoningResponse) GetZoning() map[string]*Zoning {
	if x != nil {
		return x.Zoning
	}
	return nil
}

var File_civil_public_zoning_v1_zoning_proto protoreflect.FileDescriptor

const file_civil_public_zoning_v1_zoning_proto_rawDesc = "" +
	"\n" +
	"#civil/public/zoning/v1/zoning.proto\x12\x16civil.public.zoning.v1\"\x98\x02\n" +
	"\x06Zoning\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x17\n" +
	"\amax_far\x18\x04 \x01(\x02R\x06maxFar\x12*\n" +
	"\x12min_lot_size_sq_ft\x18\x05 \x01(\x02R\x0eminLotSizeSqFt\x12\"\n" +
	"\rmax_height_ft\x18\x06 \x01(\x02R\vmaxHeightFt\x12<\n" +
	"\x1bmax_dwelling_units_per_acre\x18\a \x01(\x02R\x17maxDwellingUnitsPerAcre\x12/\n" +
	"\x14max_lot_coverage_pct\x18\b \x01(\x02R\x11maxLotCoveragePct\"\x12\n" +
	"\x10GetZoningRequest\"\xbd\x01\n" +
	"\x11GetZoningResponse\x12M\n" +
	"\x06zoning\x18\x01 \x03(\v25.civil.public.zoning.v1.GetZoningResponse.ZoningEntryR\x06zoning\x1aY\n" +
	"\vZoningEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.civil.public.zoning.v1.ZoningR\x05value:\x028\x012v\n" +
	"\rZoningService\x12e\n" +
	"\tGetZoning\x12(.civil.public.zoning.v1.GetZoningRequest\x1a).civil.public.zoning.v1.GetZoningResponse\"\x03\x90\x02\x01B\xea\x01\n" +
	"\x1acom.civil.public.zoning.v1B\vZoningProtoP\x01ZBgithub.com/civil-labs/civil-api-go/civil/public/zoning/v1;zoningv1\xa2\x02\x03CPZ\xaa\x02\x16Civil.Public.Zoning.V1\xca\x02\x17Civil\\Public_\\Zoning\\V1\xe2\x02#Civil\\Public_\\Zoning\\V1\\GPBMetadata\xea\x02\x19Civil::Public::Zoning::V1b\x06proto3"

var (
	file_civil_public_zoning_v1_zoning_proto_rawDescOnce sync.Once
	file_civil_public_zoning_v1_zoning_proto_rawDescData []byte
)

func file_civil_public_zoning_v1_zoning_proto_rawDescGZIP() []byte {
	file_civil_public_zoning_v1_zoning_proto_rawDescOnce.Do(func() {
		file_civil_public_zoning_v1_zoning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_public_zoning_v1_zoning_proto_rawDesc), len(file_civil_public_zoning_v1_zoning_proto_rawDesc)))
	})
	return file_civil_public_zoning_v1_zoning_proto_rawDescData
}

var file_civil_public_zoning_v1_zoning_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_civil_public_zoning_v1_zoning_proto_goTypes = []any{
	(*Zoning)(nil),            // 0: civil.public.zoning.v1.Zoning
	(*GetZoningRequest)(nil),  // 1: civil.public.zoning.v1.GetZoningRequest
	(*GetZoningResponse)(nil), // 2: civil.public.zoning.v1.GetZoningResponse
	nil,                       // 3: civil.public.zoning.v1.GetZoningResponse.ZoningEntry
}
var file_civil_public_zoning_v1_zoning_proto_depIdxs = []int32{
	3, // 0: civil.public.zoning.v1.GetZoningResponse.zoning:type_name -> civil.public.zoning.v1.GetZoningResponse.ZoningEntry
	0, // 1: civil.public.zoning.v1.GetZoningResponse.ZoningEntry.value:type_name -> civil.public.zoning.v1.Zoning
	1, // 2: civil.public.zoning.v1.ZoningService.GetZoning:input_type -> civil.public.zoning.v1.GetZoningRequest
	2, // 3: civil.public.zoning.v1.ZoningService.GetZoning:output_type -> civil.public.zoning.v1.GetZoningResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_civil_public_zoning_v1_zoning_proto_init() }
func file_civil_public_zoning_v1_zoning_proto_init() {
	if File_civil_public_zoning_v1_zoning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_public_zoning_v1_zoning_proto_rawDesc), len(file_civil_public_zoning_v1_zoning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_public_zoning_v1_zoning_proto_goTypes,
		DependencyIndexes: file_civil_public_zoning_v1_zoning_proto_depIdxs,
		MessageInfos:      file_civil_public_zoning_v1_zoning_proto_msgTypes,
	}.Build()
	File_civil_public_zoning_v1_zoning_proto = out.File
	file_civil_public_zoning_v1_zoning_proto_goTypes = nil
	file_civil_public_zoning_v1_zoning_proto_depIdxs = nil
}
