// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: civil/public/sales/v1/sales.proto

package salesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleId        string                 `protobuf:"bytes,1,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	SaleTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sale_timestamp,json=saleTimestamp,proto3" json:"sale_timestamp,omitempty"`
	SalePrice     string                 `protobuf:"bytes,3,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	SaleDeedBook  string                 `protobuf:"bytes,4,opt,name=sale_deed_book,json=saleDeedBook,proto3" json:"sale_deed_book,omitempty"`
	SaleDeedPage  string                 `protobuf:"bytes,5,opt,name=sale_deed_page,json=saleDeedPage,proto3" json:"sale_deed_page,omitempty"`
	SaleDeedUri   string                 `protobuf:"bytes,6,opt,name=sale_deed_uri,json=saleDeedUri,proto3" json:"sale_deed_uri,omitempty"`
	SellerName    string                 `protobuf:"bytes,7,opt,name=seller_name,json=sellerName,proto3" json:"seller_name,omitempty"`
	SellerAddress string                 `protobuf:"bytes,8,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	SellerId      string                 `protobuf:"bytes,9,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	BuyerName     string                 `protobuf:"bytes,10,opt,name=buyer_name,json=buyerName,proto3" json:"buyer_name,omitempty"`
	BuyerAddress  string                 `protobuf:"bytes,11,opt,name=buyer_address,json=buyerAddress,proto3" json:"buyer_address,omitempty"`
	BuyerId       string                 `protobuf:"bytes,12,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sale) Reset() {
	*x = Sale{}
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sale) ProtoMessage() {}

func (x *Sale) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sale.ProtoReflect.Descriptor instead.
func (*Sale) Descriptor() ([]byte, []int) {
	return file_civil_public_sales_v1_sales_proto_rawDescGZIP(), []int{0}
}

func (x *Sale) GetSaleId() string {
	if x != nil {
		return x.SaleId
	}
	return ""
}

func (x *Sale) GetSaleTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleTimestamp
	}
	return nil
}

func (x *Sale) GetSalePrice() string {
	if x != nil {
		return x.SalePrice
	}
	return ""
}

func (x *Sale) GetSaleDeedBook() string {
	if x != nil {
		return x.SaleDeedBook
	}
	return ""
}

func (x *Sale) GetSaleDeedPage() string {
	if x != nil {
		return x.SaleDeedPage
	}
	return ""
}

func (x *Sale) GetSaleDeedUri() string {
	if x != nil {
		return x.SaleDeedUri
	}
	return ""
}

func (x *Sale) GetSellerName() string {
	if x != nil {
		return x.SellerName
	}
	return ""
}

func (x *Sale) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *Sale) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Sale) GetBuyerName() string {
	if x != nil {
		return x.BuyerName
	}
	return ""
}

func (x *Sale) GetBuyerAddress() string {
	if x != nil {
		return x.BuyerAddress
	}
	return ""
}

func (x *Sale) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

type GetSalesByParcelIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemAsOf    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=system_as_of,json=systemAsOf,proto3,oneof" json:"system_as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesByParcelIdRequest) Reset() {
	*x = GetSalesByParcelIdRequest{}
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesByParcelIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesByParcelIdRequest) ProtoMessage() {}

func (x *GetSalesByParcelIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesByParcelIdRequest.ProtoReflect.Descriptor instead.
func (*GetSalesByParcelIdRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_sales_v1_sales_proto_rawDescGZIP(), []int{1}
}

func (x *GetSalesByParcelIdRequest) GetSystemAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.SystemAsOf
	}
	return nil
}

type GetSalesByParcelIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesByParcelIdResponse) Reset() {
	*x = GetSalesByParcelIdResponse{}
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesByParcelIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesByParcelIdResponse) ProtoMessage() {}

func (x *GetSalesByParcelIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesByParcelIdResponse.ProtoReflect.Descriptor instead.
func (*GetSalesByParcelIdResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_sales_v1_sales_proto_rawDescGZIP(), []int{2}
}

type GetSalesByPolygonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesByPolygonRequest) Reset() {
	*x = GetSalesByPolygonRequest{}
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesByPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesByPolygonRequest) ProtoMessage() {}

func (x *GetSalesByPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesByPolygonRequest.ProtoReflect.Descriptor instead.
func (*GetSalesByPolygonRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_sales_v1_sales_proto_rawDescGZIP(), []int{3}
}

type GetSalesByPolygonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesByPolygonResponse) Reset() {
	*x = GetSalesByPolygonResponse{}
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesByPolygonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesByPolygonResponse) ProtoMessage() {}

func (x *GetSalesByPolygonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_sales_v1_sales_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesByPolygonResponse.ProtoReflect.Descriptor instead.
func (*GetSalesByPolygonResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_sales_v1_sales_proto_rawDescGZIP(), []int{4}
}

var File_civil_public_sales_v1_sales_proto protoreflect.FileDescriptor

const file_civil_public_sales_v1_sales_proto_rawDesc = "" +
	"\n" +
	"!civil/public/sales/v1/sales.proto\x12\x15civil.public.sales.v1\x1a\x1bbuf/validate/validate.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x04\n" +
	"\x04Sale\x12q\n" +
	"\asale_id\x18\x01 \x01(\tBX\xbaGM:(\x12&'d25f625b-4e82-4761-82ca-10dafc5dcf77'\x92\x02 The unique identifier of a sale.\xbaH\x05r\x03\xb0\x01\x01R\x06saleId\x12y\n" +
	"\x0esale_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB6\xbaG \x92\x02\x1dThe time the sale occured at.\xbaH\x10\xb2\x01\r*\v\b\x80\x92\xb8Ø\xfe\xff\xff\xff\x01R\rsaleTimestamp\x12?\n" +
	"\n" +
	"sale_price\x18\x03 \x01(\tB \xbaH\x1dr\x1b2\x19^-?[0-9]+(\\.[0-9]{1,4})?$R\tsalePrice\x12$\n" +
	"\x0esale_deed_book\x18\x04 \x01(\tR\fsaleDeedBook\x12$\n" +
	"\x0esale_deed_page\x18\x05 \x01(\tR\fsaleDeedPage\x12\"\n" +
	"\rsale_deed_uri\x18\x06 \x01(\tR\vsaleDeedUri\x12\x1f\n" +
	"\vseller_name\x18\a \x01(\tR\n" +
	"sellerName\x12%\n" +
	"\x0eseller_address\x18\b \x01(\tR\rsellerAddress\x12\x1b\n" +
	"\tseller_id\x18\t \x01(\tR\bsellerId\x12\x1d\n" +
	"\n" +
	"buyer_name\x18\n" +
	" \x01(\tR\tbuyerName\x12#\n" +
	"\rbuyer_address\x18\v \x01(\tR\fbuyerAddress\x12\x19\n" +
	"\bbuyer_id\x18\f \x01(\tR\abuyerId\"\xda\x01\n" +
	"\x19GetSalesByParcelIdRequest\x12\xab\x01\n" +
	"\fsystem_as_of\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampBh\xbaGP\x92\x02MThe transaction time to evaluate the database state against. Defaults to now.\xbaH\x12\xb2\x01\x0f8\x01*\v\b\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01H\x00R\n" +
	"systemAsOf\x88\x01\x01B\x0f\n" +
	"\r_system_as_of\"\x1c\n" +
	"\x1aGetSalesByParcelIdResponse\"\x1a\n" +
	"\x18GetSalesByPolygonRequest\"\x1b\n" +
	"\x19GetSalesByPolygonResponse2\x8b\x02\n" +
	"\fSalesService\x12~\n" +
	"\x12GetSalesByParcelId\x120.civil.public.sales.v1.GetSalesByParcelIdRequest\x1a1.civil.public.sales.v1.GetSalesByParcelIdResponse\"\x03\x90\x02\x01\x12{\n" +
	"\x11GetSalesByPolygon\x12/.civil.public.sales.v1.GetSalesByPolygonRequest\x1a0.civil.public.sales.v1.GetSalesByPolygonResponse\"\x03\x90\x02\x01B\xe2\x01\n" +
	"\x19com.civil.public.sales.v1B\n" +
	"SalesProtoP\x01Z@github.com/civil-labs/civil-api-go/civil/public/sales/v1;salesv1\xa2\x02\x03CPS\xaa\x02\x15Civil.Public.Sales.V1\xca\x02\x16Civil\\Public_\\Sales\\V1\xe2\x02\"Civil\\Public_\\Sales\\V1\\GPBMetadata\xea\x02\x18Civil::Public::Sales::V1b\x06proto3"

var (
	file_civil_public_sales_v1_sales_proto_rawDescOnce sync.Once
	file_civil_public_sales_v1_sales_proto_rawDescData []byte
)

func file_civil_public_sales_v1_sales_proto_rawDescGZIP() []byte {
	file_civil_public_sales_v1_sales_proto_rawDescOnce.Do(func() {
		file_civil_public_sales_v1_sales_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_public_sales_v1_sales_proto_rawDesc), len(file_civil_public_sales_v1_sales_proto_rawDesc)))
	})
	return file_civil_public_sales_v1_sales_proto_rawDescData
}

var file_civil_public_sales_v1_sales_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_civil_public_sales_v1_sales_proto_goTypes = []any{
	(*Sale)(nil),                       // 0: civil.public.sales.v1.Sale
	(*GetSalesByParcelIdRequest)(nil),  // 1: civil.public.sales.v1.GetSalesByParcelIdRequest
	(*GetSalesByParcelIdResponse)(nil), // 2: civil.public.sales.v1.GetSalesByParcelIdResponse
	(*GetSalesByPolygonRequest)(nil),   // 3: civil.public.sales.v1.GetSalesByPolygonRequest
	(*GetSalesByPolygonResponse)(nil),  // 4: civil.public.sales.v1.GetSalesByPolygonResponse
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_civil_public_sales_v1_sales_proto_depIdxs = []int32{
	5, // 0: civil.public.sales.v1.Sale.sale_timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: civil.public.sales.v1.GetSalesByParcelIdRequest.system_as_of:type_name -> google.protobuf.Timestamp
	1, // 2: civil.public.sales.v1.SalesService.GetSalesByParcelId:input_type -> civil.public.sales.v1.GetSalesByParcelIdRequest
	3, // 3: civil.public.sales.v1.SalesService.GetSalesByPolygon:input_type -> civil.public.sales.v1.GetSalesByPolygonRequest
	2, // 4: civil.public.sales.v1.SalesService.GetSalesByParcelId:output_type -> civil.public.sales.v1.GetSalesByParcelIdResponse
	4, // 5: civil.public.sales.v1.SalesService.GetSalesByPolygon:output_type -> civil.public.sales.v1.GetSalesByPolygonResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_civil_public_sales_v1_sales_proto_init() }
func file_civil_public_sales_v1_sales_proto_init() {
	if File_civil_public_sales_v1_sales_proto != nil {
		return
	}
	file_civil_public_sales_v1_sales_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_public_sales_v1_sales_proto_rawDesc), len(file_civil_public_sales_v1_sales_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_public_sales_v1_sales_proto_goTypes,
		DependencyIndexes: file_civil_public_sales_v1_sales_proto_depIdxs,
		MessageInfos:      file_civil_public_sales_v1_sales_proto_msgTypes,
	}.Build()
	File_civil_public_sales_v1_sales_proto = out.File
	file_civil_public_sales_v1_sales_proto_goTypes = nil
	file_civil_public_sales_v1_sales_proto_depIdxs = nil
}
