// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/mesh/parcels/v1/parcels.proto

package parcelsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/mesh/parcels/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ParcelsServiceName is the fully-qualified name of the ParcelsService service.
	ParcelsServiceName = "civil.mesh.parcels.v1.ParcelsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure is the fully-qualified name of
	// the ParcelsService's GetParcelsWithImprovementSummaryByParcelId RPC.
	ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetParcelsWithImprovementSummaryByParcelId"
	// ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure is the fully-qualified name of
	// the ParcelsService's GetParcelsWithImprovementSummaryByFeatureId RPC.
	ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetParcelsWithImprovementSummaryByFeatureId"
	// ParcelsServiceGetNumericalParcelStatsByIdProcedure is the fully-qualified name of the
	// ParcelsService's GetNumericalParcelStatsById RPC.
	ParcelsServiceGetNumericalParcelStatsByIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetNumericalParcelStatsById"
	// ParcelsServiceGetCategoricalParcelStatsByIdProcedure is the fully-qualified name of the
	// ParcelsService's GetCategoricalParcelStatsById RPC.
	ParcelsServiceGetCategoricalParcelStatsByIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetCategoricalParcelStatsById"
	// ParcelsServiceGetEquityComparablesProcedure is the fully-qualified name of the ParcelsService's
	// GetEquityComparables RPC.
	ParcelsServiceGetEquityComparablesProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetEquityComparables"
	// ParcelsServiceGetSalesComparablesProcedure is the fully-qualified name of the ParcelsService's
	// GetSalesComparables RPC.
	ParcelsServiceGetSalesComparablesProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetSalesComparables"
	// ParcelsServiceGetParcelIdsByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetParcelIdsByFeatureId RPC.
	ParcelsServiceGetParcelIdsByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetParcelIdsByFeatureId"
	// ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure is the fully-qualified name of the
	// ParcelsService's GetEstimatedParcelsExtentWGS84 RPC.
	ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure = "/civil.mesh.parcels.v1.ParcelsService/GetEstimatedParcelsExtentWGS84"
	// ParcelsServiceGetLandAreaSqftByParcelIdProcedure is the fully-qualified name of the
	// ParcelsService's GetLandAreaSqftByParcelId RPC.
	ParcelsServiceGetLandAreaSqftByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetLandAreaSqftByParcelId"
	// ParcelsServiceGetFrontageFtByParcelIdProcedure is the fully-qualified name of the
	// ParcelsService's GetFrontageFtByParcelId RPC.
	ParcelsServiceGetFrontageFtByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetFrontageFtByParcelId"
	// ParcelsServiceGetDepthFtByParcelIdProcedure is the fully-qualified name of the ParcelsService's
	// GetDepthFtByParcelId RPC.
	ParcelsServiceGetDepthFtByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetDepthFtByParcelId"
	// ParcelsServiceGetLandUseIdByParcelIdProcedure is the fully-qualified name of the ParcelsService's
	// GetLandUseIdByParcelId RPC.
	ParcelsServiceGetLandUseIdByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetLandUseIdByParcelId"
	// ParcelsServiceGetZoningIdByParcelIdProcedure is the fully-qualified name of the ParcelsService's
	// GetZoningIdByParcelId RPC.
	ParcelsServiceGetZoningIdByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetZoningIdByParcelId"
	// ParcelsServiceGetImprovementAreaSqftByParcelIdProcedure is the fully-qualified name of the
	// ParcelsService's GetImprovementAreaSqftByParcelId RPC.
	ParcelsServiceGetImprovementAreaSqftByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetImprovementAreaSqftByParcelId"
	// ParcelsServiceGetBedroomsByParcelIdProcedure is the fully-qualified name of the ParcelsService's
	// GetBedroomsByParcelId RPC.
	ParcelsServiceGetBedroomsByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetBedroomsByParcelId"
	// ParcelsServiceGetBathroomsByParcelIdProcedure is the fully-qualified name of the ParcelsService's
	// GetBathroomsByParcelId RPC.
	ParcelsServiceGetBathroomsByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetBathroomsByParcelId"
	// ParcelsServiceGetUnitsByParcelIdProcedure is the fully-qualified name of the ParcelsService's
	// GetUnitsByParcelId RPC.
	ParcelsServiceGetUnitsByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetUnitsByParcelId"
	// ParcelsServiceGetPrimaryImprovementYearBuiltByParcelIdProcedure is the fully-qualified name of
	// the ParcelsService's GetPrimaryImprovementYearBuiltByParcelId RPC.
	ParcelsServiceGetPrimaryImprovementYearBuiltByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementYearBuiltByParcelId"
	// ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdProcedure is the fully-qualified
	// name of the ParcelsService's GetPrimaryImprovementEffectiveYearBuiltByParcelId RPC.
	ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementEffectiveYearBuiltByParcelId"
	// ParcelsServiceGetPrimaryImprovementConditionIdByParcelIdProcedure is the fully-qualified name of
	// the ParcelsService's GetPrimaryImprovementConditionIdByParcelId RPC.
	ParcelsServiceGetPrimaryImprovementConditionIdByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementConditionIdByParcelId"
	// ParcelsServiceGetPrimaryImprovementTypeIdByParcelIdProcedure is the fully-qualified name of the
	// ParcelsService's GetPrimaryImprovementTypeIdByParcelId RPC.
	ParcelsServiceGetPrimaryImprovementTypeIdByParcelIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementTypeIdByParcelId"
	// ParcelsServiceGetLandAreaSqftByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetLandAreaSqftByFeatureId RPC.
	ParcelsServiceGetLandAreaSqftByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetLandAreaSqftByFeatureId"
	// ParcelsServiceGetFrontageFtByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetFrontageFtByFeatureId RPC.
	ParcelsServiceGetFrontageFtByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetFrontageFtByFeatureId"
	// ParcelsServiceGetDepthFtByFeatureIdProcedure is the fully-qualified name of the ParcelsService's
	// GetDepthFtByFeatureId RPC.
	ParcelsServiceGetDepthFtByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetDepthFtByFeatureId"
	// ParcelsServiceGetLandUseIdByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetLandUseIdByFeatureId RPC.
	ParcelsServiceGetLandUseIdByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetLandUseIdByFeatureId"
	// ParcelsServiceGetZoningIdByFeatureIdProcedure is the fully-qualified name of the ParcelsService's
	// GetZoningIdByFeatureId RPC.
	ParcelsServiceGetZoningIdByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetZoningIdByFeatureId"
	// ParcelsServiceGetImprovementAreaSqftByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetImprovementAreaSqftByFeatureId RPC.
	ParcelsServiceGetImprovementAreaSqftByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetImprovementAreaSqftByFeatureId"
	// ParcelsServiceGetBedroomsByFeatureIdProcedure is the fully-qualified name of the ParcelsService's
	// GetBedroomsByFeatureId RPC.
	ParcelsServiceGetBedroomsByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetBedroomsByFeatureId"
	// ParcelsServiceGetBathroomsByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetBathroomsByFeatureId RPC.
	ParcelsServiceGetBathroomsByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetBathroomsByFeatureId"
	// ParcelsServiceGetUnitsByFeatureIdProcedure is the fully-qualified name of the ParcelsService's
	// GetUnitsByFeatureId RPC.
	ParcelsServiceGetUnitsByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetUnitsByFeatureId"
	// ParcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdProcedure is the fully-qualified name of
	// the ParcelsService's GetPrimaryImprovementYearBuiltByFeatureId RPC.
	ParcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementYearBuiltByFeatureId"
	// ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdProcedure is the fully-qualified
	// name of the ParcelsService's GetPrimaryImprovementEffectiveYearBuiltByFeatureId RPC.
	ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementEffectiveYearBuiltByFeatureId"
	// ParcelsServiceGetPrimaryImprovementConditionIdByFeatureIdProcedure is the fully-qualified name of
	// the ParcelsService's GetPrimaryImprovementConditionIdByFeatureId RPC.
	ParcelsServiceGetPrimaryImprovementConditionIdByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementConditionIdByFeatureId"
	// ParcelsServiceGetPrimaryImprovementTypeIdByFeatureIdProcedure is the fully-qualified name of the
	// ParcelsService's GetPrimaryImprovementTypeIdByFeatureId RPC.
	ParcelsServiceGetPrimaryImprovementTypeIdByFeatureIdProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetPrimaryImprovementTypeIdByFeatureId"
	// ParcelsServiceUpdateParcelProcedure is the fully-qualified name of the ParcelsService's
	// UpdateParcel RPC.
	ParcelsServiceUpdateParcelProcedure = "/civil.mesh.parcels.v1.ParcelsService/UpdateParcel"
)

// ParcelsServiceClient is a client for the civil.mesh.parcels.v1.ParcelsService service.
type ParcelsServiceClient interface {
	// Retrieves the value for a specified attribute for a given parcel
	GetParcelsWithImprovementSummaryByParcelId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error)
	GetParcelsWithImprovementSummaryByFeatureId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetNumericalParcelStatsById(context.Context, *connect.Request[v1.GetNumericalParcelStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelStatsByIdResponse], error)
	// Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
	GetCategoricalParcelStatsById(context.Context, *connect.Request[v1.GetCategoricalParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelStatsByIdResponse], error)
	GetEquityComparables(context.Context, *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error)
	GetSalesComparables(context.Context, *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error)
	GetParcelIdsByFeatureId(context.Context, *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error)
	GetEstimatedParcelsExtentWGS84(context.Context, *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error)
	GetLandAreaSqftByParcelId(context.Context, *connect.Request[v1.GetLandAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetLandAreaSqftByParcelIdResponse], error)
	GetFrontageFtByParcelId(context.Context, *connect.Request[v1.GetFrontageFtByParcelIdRequest]) (*connect.Response[v1.GetFrontageFtByParcelIdResponse], error)
	GetDepthFtByParcelId(context.Context, *connect.Request[v1.GetDepthFtByParcelIdRequest]) (*connect.Response[v1.GetDepthFtByParcelIdResponse], error)
	GetLandUseIdByParcelId(context.Context, *connect.Request[v1.GetLandUseIdByParcelIdRequest]) (*connect.Response[v1.GetLandUseIdByParcelIdResponse], error)
	GetZoningIdByParcelId(context.Context, *connect.Request[v1.GetZoningIdByParcelIdRequest]) (*connect.Response[v1.GetZoningIdByParcelIdResponse], error)
	GetImprovementAreaSqftByParcelId(context.Context, *connect.Request[v1.GetImprovementAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByParcelIdResponse], error)
	GetBedroomsByParcelId(context.Context, *connect.Request[v1.GetBedroomsByParcelIdRequest]) (*connect.Response[v1.GetBedroomsByParcelIdResponse], error)
	GetBathroomsByParcelId(context.Context, *connect.Request[v1.GetBathroomsByParcelIdRequest]) (*connect.Response[v1.GetBathroomsByParcelIdResponse], error)
	GetUnitsByParcelId(context.Context, *connect.Request[v1.GetUnitsByParcelIdRequest]) (*connect.Response[v1.GetUnitsByParcelIdResponse], error)
	GetPrimaryImprovementYearBuiltByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByParcelIdResponse], error)
	GetPrimaryImprovementEffectiveYearBuiltByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdResponse], error)
	GetPrimaryImprovementConditionIdByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementConditionIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByParcelIdResponse], error)
	GetPrimaryImprovementTypeIdByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementTypeIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByParcelIdResponse], error)
	GetLandAreaSqftByFeatureId(context.Context, *connect.Request[v1.GetLandAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetLandAreaSqftByFeatureIdResponse], error)
	GetFrontageFtByFeatureId(context.Context, *connect.Request[v1.GetFrontageFtByFeatureIdRequest]) (*connect.Response[v1.GetFrontageFtByFeatureIdResponse], error)
	GetDepthFtByFeatureId(context.Context, *connect.Request[v1.GetDepthFtByFeatureIdRequest]) (*connect.Response[v1.GetDepthFtByFeatureIdResponse], error)
	GetLandUseIdByFeatureId(context.Context, *connect.Request[v1.GetLandUseIdByFeatureIdRequest]) (*connect.Response[v1.GetLandUseIdByFeatureIdResponse], error)
	GetZoningIdByFeatureId(context.Context, *connect.Request[v1.GetZoningIdByFeatureIdRequest]) (*connect.Response[v1.GetZoningIdByFeatureIdResponse], error)
	GetImprovementAreaSqftByFeatureId(context.Context, *connect.Request[v1.GetImprovementAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByFeatureIdResponse], error)
	GetBedroomsByFeatureId(context.Context, *connect.Request[v1.GetBedroomsByFeatureIdRequest]) (*connect.Response[v1.GetBedroomsByFeatureIdResponse], error)
	GetBathroomsByFeatureId(context.Context, *connect.Request[v1.GetBathroomsByFeatureIdRequest]) (*connect.Response[v1.GetBathroomsByFeatureIdResponse], error)
	GetUnitsByFeatureId(context.Context, *connect.Request[v1.GetUnitsByFeatureIdRequest]) (*connect.Response[v1.GetUnitsByFeatureIdResponse], error)
	GetPrimaryImprovementYearBuiltByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByFeatureIdResponse], error)
	GetPrimaryImprovementEffectiveYearBuiltByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdResponse], error)
	GetPrimaryImprovementConditionIdByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementConditionIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByFeatureIdResponse], error)
	GetPrimaryImprovementTypeIdByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementTypeIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByFeatureIdResponse], error)
	UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error)
}

// NewParcelsServiceClient constructs a client for the civil.mesh.parcels.v1.ParcelsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewParcelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ParcelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	parcelsServiceMethods := v1.File_civil_mesh_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	return &parcelsServiceClient{
		getParcelsWithImprovementSummaryByParcelId: connect.NewClient[v1.GetParcelsWithImprovementSummaryByParcelIdRequest, v1.GetParcelsWithImprovementSummaryByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getParcelsWithImprovementSummaryByFeatureId: connect.NewClient[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest, v1.GetParcelsWithImprovementSummaryByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getNumericalParcelStatsById: connect.NewClient[v1.GetNumericalParcelStatsByIdRequest, v1.GetNumericalParcelStatsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetNumericalParcelStatsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetNumericalParcelStatsById")),
			connect.WithClientOptions(opts...),
		),
		getCategoricalParcelStatsById: connect.NewClient[v1.GetCategoricalParcelStatsByIdRequest, v1.GetCategoricalParcelStatsByIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetCategoricalParcelStatsByIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetCategoricalParcelStatsById")),
			connect.WithClientOptions(opts...),
		),
		getEquityComparables: connect.NewClient[v1.GetEquityComparablesRequest, v1.GetEquityComparablesResponse](
			httpClient,
			baseURL+ParcelsServiceGetEquityComparablesProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetEquityComparables")),
			connect.WithClientOptions(opts...),
		),
		getSalesComparables: connect.NewClient[v1.GetSalesComparablesRequest, v1.GetSalesComparablesResponse](
			httpClient,
			baseURL+ParcelsServiceGetSalesComparablesProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetSalesComparables")),
			connect.WithClientOptions(opts...),
		),
		getParcelIdsByFeatureId: connect.NewClient[v1.GetParcelIdsByFeatureIdRequest, v1.GetParcelIdsByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelIdsByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelIdsByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getEstimatedParcelsExtentWGS84: connect.NewClient[v1.GetEstimatedParcelsExtentWGS84Request, v1.GetEstimatedParcelsExtentWGS84Response](
			httpClient,
			baseURL+ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetEstimatedParcelsExtentWGS84")),
			connect.WithClientOptions(opts...),
		),
		getLandAreaSqftByParcelId: connect.NewClient[v1.GetLandAreaSqftByParcelIdRequest, v1.GetLandAreaSqftByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetLandAreaSqftByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetLandAreaSqftByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getFrontageFtByParcelId: connect.NewClient[v1.GetFrontageFtByParcelIdRequest, v1.GetFrontageFtByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetFrontageFtByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetFrontageFtByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getDepthFtByParcelId: connect.NewClient[v1.GetDepthFtByParcelIdRequest, v1.GetDepthFtByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetDepthFtByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetDepthFtByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getLandUseIdByParcelId: connect.NewClient[v1.GetLandUseIdByParcelIdRequest, v1.GetLandUseIdByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetLandUseIdByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetLandUseIdByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getZoningIdByParcelId: connect.NewClient[v1.GetZoningIdByParcelIdRequest, v1.GetZoningIdByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetZoningIdByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetZoningIdByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getImprovementAreaSqftByParcelId: connect.NewClient[v1.GetImprovementAreaSqftByParcelIdRequest, v1.GetImprovementAreaSqftByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetImprovementAreaSqftByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetImprovementAreaSqftByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getBedroomsByParcelId: connect.NewClient[v1.GetBedroomsByParcelIdRequest, v1.GetBedroomsByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetBedroomsByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetBedroomsByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getBathroomsByParcelId: connect.NewClient[v1.GetBathroomsByParcelIdRequest, v1.GetBathroomsByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetBathroomsByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetBathroomsByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getUnitsByParcelId: connect.NewClient[v1.GetUnitsByParcelIdRequest, v1.GetUnitsByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetUnitsByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetUnitsByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementYearBuiltByParcelId: connect.NewClient[v1.GetPrimaryImprovementYearBuiltByParcelIdRequest, v1.GetPrimaryImprovementYearBuiltByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementYearBuiltByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementYearBuiltByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementEffectiveYearBuiltByParcelId: connect.NewClient[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdRequest, v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementEffectiveYearBuiltByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementConditionIdByParcelId: connect.NewClient[v1.GetPrimaryImprovementConditionIdByParcelIdRequest, v1.GetPrimaryImprovementConditionIdByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementConditionIdByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementConditionIdByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementTypeIdByParcelId: connect.NewClient[v1.GetPrimaryImprovementTypeIdByParcelIdRequest, v1.GetPrimaryImprovementTypeIdByParcelIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementTypeIdByParcelIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementTypeIdByParcelId")),
			connect.WithClientOptions(opts...),
		),
		getLandAreaSqftByFeatureId: connect.NewClient[v1.GetLandAreaSqftByFeatureIdRequest, v1.GetLandAreaSqftByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetLandAreaSqftByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetLandAreaSqftByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getFrontageFtByFeatureId: connect.NewClient[v1.GetFrontageFtByFeatureIdRequest, v1.GetFrontageFtByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetFrontageFtByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetFrontageFtByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getDepthFtByFeatureId: connect.NewClient[v1.GetDepthFtByFeatureIdRequest, v1.GetDepthFtByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetDepthFtByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetDepthFtByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getLandUseIdByFeatureId: connect.NewClient[v1.GetLandUseIdByFeatureIdRequest, v1.GetLandUseIdByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetLandUseIdByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetLandUseIdByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getZoningIdByFeatureId: connect.NewClient[v1.GetZoningIdByFeatureIdRequest, v1.GetZoningIdByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetZoningIdByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetZoningIdByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getImprovementAreaSqftByFeatureId: connect.NewClient[v1.GetImprovementAreaSqftByFeatureIdRequest, v1.GetImprovementAreaSqftByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetImprovementAreaSqftByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetImprovementAreaSqftByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getBedroomsByFeatureId: connect.NewClient[v1.GetBedroomsByFeatureIdRequest, v1.GetBedroomsByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetBedroomsByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetBedroomsByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getBathroomsByFeatureId: connect.NewClient[v1.GetBathroomsByFeatureIdRequest, v1.GetBathroomsByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetBathroomsByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetBathroomsByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getUnitsByFeatureId: connect.NewClient[v1.GetUnitsByFeatureIdRequest, v1.GetUnitsByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetUnitsByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetUnitsByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementYearBuiltByFeatureId: connect.NewClient[v1.GetPrimaryImprovementYearBuiltByFeatureIdRequest, v1.GetPrimaryImprovementYearBuiltByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementYearBuiltByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementEffectiveYearBuiltByFeatureId: connect.NewClient[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdRequest, v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementEffectiveYearBuiltByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementConditionIdByFeatureId: connect.NewClient[v1.GetPrimaryImprovementConditionIdByFeatureIdRequest, v1.GetPrimaryImprovementConditionIdByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementConditionIdByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementConditionIdByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		getPrimaryImprovementTypeIdByFeatureId: connect.NewClient[v1.GetPrimaryImprovementTypeIdByFeatureIdRequest, v1.GetPrimaryImprovementTypeIdByFeatureIdResponse](
			httpClient,
			baseURL+ParcelsServiceGetPrimaryImprovementTypeIdByFeatureIdProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementTypeIdByFeatureId")),
			connect.WithClientOptions(opts...),
		),
		updateParcel: connect.NewClient[v1.UpdateParcelRequest, v1.UpdateParcelResponse](
			httpClient,
			baseURL+ParcelsServiceUpdateParcelProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("UpdateParcel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// parcelsServiceClient implements ParcelsServiceClient.
type parcelsServiceClient struct {
	getParcelsWithImprovementSummaryByParcelId         *connect.Client[v1.GetParcelsWithImprovementSummaryByParcelIdRequest, v1.GetParcelsWithImprovementSummaryByParcelIdResponse]
	getParcelsWithImprovementSummaryByFeatureId        *connect.Client[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest, v1.GetParcelsWithImprovementSummaryByFeatureIdResponse]
	getNumericalParcelStatsById                        *connect.Client[v1.GetNumericalParcelStatsByIdRequest, v1.GetNumericalParcelStatsByIdResponse]
	getCategoricalParcelStatsById                      *connect.Client[v1.GetCategoricalParcelStatsByIdRequest, v1.GetCategoricalParcelStatsByIdResponse]
	getEquityComparables                               *connect.Client[v1.GetEquityComparablesRequest, v1.GetEquityComparablesResponse]
	getSalesComparables                                *connect.Client[v1.GetSalesComparablesRequest, v1.GetSalesComparablesResponse]
	getParcelIdsByFeatureId                            *connect.Client[v1.GetParcelIdsByFeatureIdRequest, v1.GetParcelIdsByFeatureIdResponse]
	getEstimatedParcelsExtentWGS84                     *connect.Client[v1.GetEstimatedParcelsExtentWGS84Request, v1.GetEstimatedParcelsExtentWGS84Response]
	getLandAreaSqftByParcelId                          *connect.Client[v1.GetLandAreaSqftByParcelIdRequest, v1.GetLandAreaSqftByParcelIdResponse]
	getFrontageFtByParcelId                            *connect.Client[v1.GetFrontageFtByParcelIdRequest, v1.GetFrontageFtByParcelIdResponse]
	getDepthFtByParcelId                               *connect.Client[v1.GetDepthFtByParcelIdRequest, v1.GetDepthFtByParcelIdResponse]
	getLandUseIdByParcelId                             *connect.Client[v1.GetLandUseIdByParcelIdRequest, v1.GetLandUseIdByParcelIdResponse]
	getZoningIdByParcelId                              *connect.Client[v1.GetZoningIdByParcelIdRequest, v1.GetZoningIdByParcelIdResponse]
	getImprovementAreaSqftByParcelId                   *connect.Client[v1.GetImprovementAreaSqftByParcelIdRequest, v1.GetImprovementAreaSqftByParcelIdResponse]
	getBedroomsByParcelId                              *connect.Client[v1.GetBedroomsByParcelIdRequest, v1.GetBedroomsByParcelIdResponse]
	getBathroomsByParcelId                             *connect.Client[v1.GetBathroomsByParcelIdRequest, v1.GetBathroomsByParcelIdResponse]
	getUnitsByParcelId                                 *connect.Client[v1.GetUnitsByParcelIdRequest, v1.GetUnitsByParcelIdResponse]
	getPrimaryImprovementYearBuiltByParcelId           *connect.Client[v1.GetPrimaryImprovementYearBuiltByParcelIdRequest, v1.GetPrimaryImprovementYearBuiltByParcelIdResponse]
	getPrimaryImprovementEffectiveYearBuiltByParcelId  *connect.Client[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdRequest, v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdResponse]
	getPrimaryImprovementConditionIdByParcelId         *connect.Client[v1.GetPrimaryImprovementConditionIdByParcelIdRequest, v1.GetPrimaryImprovementConditionIdByParcelIdResponse]
	getPrimaryImprovementTypeIdByParcelId              *connect.Client[v1.GetPrimaryImprovementTypeIdByParcelIdRequest, v1.GetPrimaryImprovementTypeIdByParcelIdResponse]
	getLandAreaSqftByFeatureId                         *connect.Client[v1.GetLandAreaSqftByFeatureIdRequest, v1.GetLandAreaSqftByFeatureIdResponse]
	getFrontageFtByFeatureId                           *connect.Client[v1.GetFrontageFtByFeatureIdRequest, v1.GetFrontageFtByFeatureIdResponse]
	getDepthFtByFeatureId                              *connect.Client[v1.GetDepthFtByFeatureIdRequest, v1.GetDepthFtByFeatureIdResponse]
	getLandUseIdByFeatureId                            *connect.Client[v1.GetLandUseIdByFeatureIdRequest, v1.GetLandUseIdByFeatureIdResponse]
	getZoningIdByFeatureId                             *connect.Client[v1.GetZoningIdByFeatureIdRequest, v1.GetZoningIdByFeatureIdResponse]
	getImprovementAreaSqftByFeatureId                  *connect.Client[v1.GetImprovementAreaSqftByFeatureIdRequest, v1.GetImprovementAreaSqftByFeatureIdResponse]
	getBedroomsByFeatureId                             *connect.Client[v1.GetBedroomsByFeatureIdRequest, v1.GetBedroomsByFeatureIdResponse]
	getBathroomsByFeatureId                            *connect.Client[v1.GetBathroomsByFeatureIdRequest, v1.GetBathroomsByFeatureIdResponse]
	getUnitsByFeatureId                                *connect.Client[v1.GetUnitsByFeatureIdRequest, v1.GetUnitsByFeatureIdResponse]
	getPrimaryImprovementYearBuiltByFeatureId          *connect.Client[v1.GetPrimaryImprovementYearBuiltByFeatureIdRequest, v1.GetPrimaryImprovementYearBuiltByFeatureIdResponse]
	getPrimaryImprovementEffectiveYearBuiltByFeatureId *connect.Client[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdRequest, v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdResponse]
	getPrimaryImprovementConditionIdByFeatureId        *connect.Client[v1.GetPrimaryImprovementConditionIdByFeatureIdRequest, v1.GetPrimaryImprovementConditionIdByFeatureIdResponse]
	getPrimaryImprovementTypeIdByFeatureId             *connect.Client[v1.GetPrimaryImprovementTypeIdByFeatureIdRequest, v1.GetPrimaryImprovementTypeIdByFeatureIdResponse]
	updateParcel                                       *connect.Client[v1.UpdateParcelRequest, v1.UpdateParcelResponse]
}

// GetParcelsWithImprovementSummaryByParcelId calls
// civil.mesh.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByParcelId.
func (c *parcelsServiceClient) GetParcelsWithImprovementSummaryByParcelId(ctx context.Context, req *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error) {
	return c.getParcelsWithImprovementSummaryByParcelId.CallUnary(ctx, req)
}

// GetParcelsWithImprovementSummaryByFeatureId calls
// civil.mesh.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByFeatureId.
func (c *parcelsServiceClient) GetParcelsWithImprovementSummaryByFeatureId(ctx context.Context, req *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error) {
	return c.getParcelsWithImprovementSummaryByFeatureId.CallUnary(ctx, req)
}

// GetNumericalParcelStatsById calls
// civil.mesh.parcels.v1.ParcelsService.GetNumericalParcelStatsById.
func (c *parcelsServiceClient) GetNumericalParcelStatsById(ctx context.Context, req *connect.Request[v1.GetNumericalParcelStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelStatsByIdResponse], error) {
	return c.getNumericalParcelStatsById.CallUnary(ctx, req)
}

// GetCategoricalParcelStatsById calls
// civil.mesh.parcels.v1.ParcelsService.GetCategoricalParcelStatsById.
func (c *parcelsServiceClient) GetCategoricalParcelStatsById(ctx context.Context, req *connect.Request[v1.GetCategoricalParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelStatsByIdResponse], error) {
	return c.getCategoricalParcelStatsById.CallUnary(ctx, req)
}

// GetEquityComparables calls civil.mesh.parcels.v1.ParcelsService.GetEquityComparables.
func (c *parcelsServiceClient) GetEquityComparables(ctx context.Context, req *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error) {
	return c.getEquityComparables.CallUnary(ctx, req)
}

// GetSalesComparables calls civil.mesh.parcels.v1.ParcelsService.GetSalesComparables.
func (c *parcelsServiceClient) GetSalesComparables(ctx context.Context, req *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error) {
	return c.getSalesComparables.CallUnary(ctx, req)
}

// GetParcelIdsByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetParcelIdsByFeatureId.
func (c *parcelsServiceClient) GetParcelIdsByFeatureId(ctx context.Context, req *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error) {
	return c.getParcelIdsByFeatureId.CallUnary(ctx, req)
}

// GetEstimatedParcelsExtentWGS84 calls
// civil.mesh.parcels.v1.ParcelsService.GetEstimatedParcelsExtentWGS84.
func (c *parcelsServiceClient) GetEstimatedParcelsExtentWGS84(ctx context.Context, req *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error) {
	return c.getEstimatedParcelsExtentWGS84.CallUnary(ctx, req)
}

// GetLandAreaSqftByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetLandAreaSqftByParcelId.
func (c *parcelsServiceClient) GetLandAreaSqftByParcelId(ctx context.Context, req *connect.Request[v1.GetLandAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetLandAreaSqftByParcelIdResponse], error) {
	return c.getLandAreaSqftByParcelId.CallUnary(ctx, req)
}

// GetFrontageFtByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetFrontageFtByParcelId.
func (c *parcelsServiceClient) GetFrontageFtByParcelId(ctx context.Context, req *connect.Request[v1.GetFrontageFtByParcelIdRequest]) (*connect.Response[v1.GetFrontageFtByParcelIdResponse], error) {
	return c.getFrontageFtByParcelId.CallUnary(ctx, req)
}

// GetDepthFtByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetDepthFtByParcelId.
func (c *parcelsServiceClient) GetDepthFtByParcelId(ctx context.Context, req *connect.Request[v1.GetDepthFtByParcelIdRequest]) (*connect.Response[v1.GetDepthFtByParcelIdResponse], error) {
	return c.getDepthFtByParcelId.CallUnary(ctx, req)
}

// GetLandUseIdByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetLandUseIdByParcelId.
func (c *parcelsServiceClient) GetLandUseIdByParcelId(ctx context.Context, req *connect.Request[v1.GetLandUseIdByParcelIdRequest]) (*connect.Response[v1.GetLandUseIdByParcelIdResponse], error) {
	return c.getLandUseIdByParcelId.CallUnary(ctx, req)
}

// GetZoningIdByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetZoningIdByParcelId.
func (c *parcelsServiceClient) GetZoningIdByParcelId(ctx context.Context, req *connect.Request[v1.GetZoningIdByParcelIdRequest]) (*connect.Response[v1.GetZoningIdByParcelIdResponse], error) {
	return c.getZoningIdByParcelId.CallUnary(ctx, req)
}

// GetImprovementAreaSqftByParcelId calls
// civil.mesh.parcels.v1.ParcelsService.GetImprovementAreaSqftByParcelId.
func (c *parcelsServiceClient) GetImprovementAreaSqftByParcelId(ctx context.Context, req *connect.Request[v1.GetImprovementAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByParcelIdResponse], error) {
	return c.getImprovementAreaSqftByParcelId.CallUnary(ctx, req)
}

// GetBedroomsByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetBedroomsByParcelId.
func (c *parcelsServiceClient) GetBedroomsByParcelId(ctx context.Context, req *connect.Request[v1.GetBedroomsByParcelIdRequest]) (*connect.Response[v1.GetBedroomsByParcelIdResponse], error) {
	return c.getBedroomsByParcelId.CallUnary(ctx, req)
}

// GetBathroomsByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetBathroomsByParcelId.
func (c *parcelsServiceClient) GetBathroomsByParcelId(ctx context.Context, req *connect.Request[v1.GetBathroomsByParcelIdRequest]) (*connect.Response[v1.GetBathroomsByParcelIdResponse], error) {
	return c.getBathroomsByParcelId.CallUnary(ctx, req)
}

// GetUnitsByParcelId calls civil.mesh.parcels.v1.ParcelsService.GetUnitsByParcelId.
func (c *parcelsServiceClient) GetUnitsByParcelId(ctx context.Context, req *connect.Request[v1.GetUnitsByParcelIdRequest]) (*connect.Response[v1.GetUnitsByParcelIdResponse], error) {
	return c.getUnitsByParcelId.CallUnary(ctx, req)
}

// GetPrimaryImprovementYearBuiltByParcelId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementYearBuiltByParcelId.
func (c *parcelsServiceClient) GetPrimaryImprovementYearBuiltByParcelId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByParcelIdResponse], error) {
	return c.getPrimaryImprovementYearBuiltByParcelId.CallUnary(ctx, req)
}

// GetPrimaryImprovementEffectiveYearBuiltByParcelId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementEffectiveYearBuiltByParcelId.
func (c *parcelsServiceClient) GetPrimaryImprovementEffectiveYearBuiltByParcelId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdResponse], error) {
	return c.getPrimaryImprovementEffectiveYearBuiltByParcelId.CallUnary(ctx, req)
}

// GetPrimaryImprovementConditionIdByParcelId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementConditionIdByParcelId.
func (c *parcelsServiceClient) GetPrimaryImprovementConditionIdByParcelId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementConditionIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByParcelIdResponse], error) {
	return c.getPrimaryImprovementConditionIdByParcelId.CallUnary(ctx, req)
}

// GetPrimaryImprovementTypeIdByParcelId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementTypeIdByParcelId.
func (c *parcelsServiceClient) GetPrimaryImprovementTypeIdByParcelId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementTypeIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByParcelIdResponse], error) {
	return c.getPrimaryImprovementTypeIdByParcelId.CallUnary(ctx, req)
}

// GetLandAreaSqftByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetLandAreaSqftByFeatureId.
func (c *parcelsServiceClient) GetLandAreaSqftByFeatureId(ctx context.Context, req *connect.Request[v1.GetLandAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetLandAreaSqftByFeatureIdResponse], error) {
	return c.getLandAreaSqftByFeatureId.CallUnary(ctx, req)
}

// GetFrontageFtByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetFrontageFtByFeatureId.
func (c *parcelsServiceClient) GetFrontageFtByFeatureId(ctx context.Context, req *connect.Request[v1.GetFrontageFtByFeatureIdRequest]) (*connect.Response[v1.GetFrontageFtByFeatureIdResponse], error) {
	return c.getFrontageFtByFeatureId.CallUnary(ctx, req)
}

// GetDepthFtByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetDepthFtByFeatureId.
func (c *parcelsServiceClient) GetDepthFtByFeatureId(ctx context.Context, req *connect.Request[v1.GetDepthFtByFeatureIdRequest]) (*connect.Response[v1.GetDepthFtByFeatureIdResponse], error) {
	return c.getDepthFtByFeatureId.CallUnary(ctx, req)
}

// GetLandUseIdByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetLandUseIdByFeatureId.
func (c *parcelsServiceClient) GetLandUseIdByFeatureId(ctx context.Context, req *connect.Request[v1.GetLandUseIdByFeatureIdRequest]) (*connect.Response[v1.GetLandUseIdByFeatureIdResponse], error) {
	return c.getLandUseIdByFeatureId.CallUnary(ctx, req)
}

// GetZoningIdByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetZoningIdByFeatureId.
func (c *parcelsServiceClient) GetZoningIdByFeatureId(ctx context.Context, req *connect.Request[v1.GetZoningIdByFeatureIdRequest]) (*connect.Response[v1.GetZoningIdByFeatureIdResponse], error) {
	return c.getZoningIdByFeatureId.CallUnary(ctx, req)
}

// GetImprovementAreaSqftByFeatureId calls
// civil.mesh.parcels.v1.ParcelsService.GetImprovementAreaSqftByFeatureId.
func (c *parcelsServiceClient) GetImprovementAreaSqftByFeatureId(ctx context.Context, req *connect.Request[v1.GetImprovementAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByFeatureIdResponse], error) {
	return c.getImprovementAreaSqftByFeatureId.CallUnary(ctx, req)
}

// GetBedroomsByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetBedroomsByFeatureId.
func (c *parcelsServiceClient) GetBedroomsByFeatureId(ctx context.Context, req *connect.Request[v1.GetBedroomsByFeatureIdRequest]) (*connect.Response[v1.GetBedroomsByFeatureIdResponse], error) {
	return c.getBedroomsByFeatureId.CallUnary(ctx, req)
}

// GetBathroomsByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetBathroomsByFeatureId.
func (c *parcelsServiceClient) GetBathroomsByFeatureId(ctx context.Context, req *connect.Request[v1.GetBathroomsByFeatureIdRequest]) (*connect.Response[v1.GetBathroomsByFeatureIdResponse], error) {
	return c.getBathroomsByFeatureId.CallUnary(ctx, req)
}

// GetUnitsByFeatureId calls civil.mesh.parcels.v1.ParcelsService.GetUnitsByFeatureId.
func (c *parcelsServiceClient) GetUnitsByFeatureId(ctx context.Context, req *connect.Request[v1.GetUnitsByFeatureIdRequest]) (*connect.Response[v1.GetUnitsByFeatureIdResponse], error) {
	return c.getUnitsByFeatureId.CallUnary(ctx, req)
}

// GetPrimaryImprovementYearBuiltByFeatureId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementYearBuiltByFeatureId.
func (c *parcelsServiceClient) GetPrimaryImprovementYearBuiltByFeatureId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByFeatureIdResponse], error) {
	return c.getPrimaryImprovementYearBuiltByFeatureId.CallUnary(ctx, req)
}

// GetPrimaryImprovementEffectiveYearBuiltByFeatureId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementEffectiveYearBuiltByFeatureId.
func (c *parcelsServiceClient) GetPrimaryImprovementEffectiveYearBuiltByFeatureId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdResponse], error) {
	return c.getPrimaryImprovementEffectiveYearBuiltByFeatureId.CallUnary(ctx, req)
}

// GetPrimaryImprovementConditionIdByFeatureId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementConditionIdByFeatureId.
func (c *parcelsServiceClient) GetPrimaryImprovementConditionIdByFeatureId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementConditionIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByFeatureIdResponse], error) {
	return c.getPrimaryImprovementConditionIdByFeatureId.CallUnary(ctx, req)
}

// GetPrimaryImprovementTypeIdByFeatureId calls
// civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementTypeIdByFeatureId.
func (c *parcelsServiceClient) GetPrimaryImprovementTypeIdByFeatureId(ctx context.Context, req *connect.Request[v1.GetPrimaryImprovementTypeIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByFeatureIdResponse], error) {
	return c.getPrimaryImprovementTypeIdByFeatureId.CallUnary(ctx, req)
}

// UpdateParcel calls civil.mesh.parcels.v1.ParcelsService.UpdateParcel.
func (c *parcelsServiceClient) UpdateParcel(ctx context.Context, req *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error) {
	return c.updateParcel.CallUnary(ctx, req)
}

// ParcelsServiceHandler is an implementation of the civil.mesh.parcels.v1.ParcelsService service.
type ParcelsServiceHandler interface {
	// Retrieves the value for a specified attribute for a given parcel
	GetParcelsWithImprovementSummaryByParcelId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error)
	GetParcelsWithImprovementSummaryByFeatureId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error)
	// Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
	GetNumericalParcelStatsById(context.Context, *connect.Request[v1.GetNumericalParcelStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelStatsByIdResponse], error)
	// Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
	GetCategoricalParcelStatsById(context.Context, *connect.Request[v1.GetCategoricalParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelStatsByIdResponse], error)
	GetEquityComparables(context.Context, *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error)
	GetSalesComparables(context.Context, *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error)
	GetParcelIdsByFeatureId(context.Context, *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error)
	GetEstimatedParcelsExtentWGS84(context.Context, *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error)
	GetLandAreaSqftByParcelId(context.Context, *connect.Request[v1.GetLandAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetLandAreaSqftByParcelIdResponse], error)
	GetFrontageFtByParcelId(context.Context, *connect.Request[v1.GetFrontageFtByParcelIdRequest]) (*connect.Response[v1.GetFrontageFtByParcelIdResponse], error)
	GetDepthFtByParcelId(context.Context, *connect.Request[v1.GetDepthFtByParcelIdRequest]) (*connect.Response[v1.GetDepthFtByParcelIdResponse], error)
	GetLandUseIdByParcelId(context.Context, *connect.Request[v1.GetLandUseIdByParcelIdRequest]) (*connect.Response[v1.GetLandUseIdByParcelIdResponse], error)
	GetZoningIdByParcelId(context.Context, *connect.Request[v1.GetZoningIdByParcelIdRequest]) (*connect.Response[v1.GetZoningIdByParcelIdResponse], error)
	GetImprovementAreaSqftByParcelId(context.Context, *connect.Request[v1.GetImprovementAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByParcelIdResponse], error)
	GetBedroomsByParcelId(context.Context, *connect.Request[v1.GetBedroomsByParcelIdRequest]) (*connect.Response[v1.GetBedroomsByParcelIdResponse], error)
	GetBathroomsByParcelId(context.Context, *connect.Request[v1.GetBathroomsByParcelIdRequest]) (*connect.Response[v1.GetBathroomsByParcelIdResponse], error)
	GetUnitsByParcelId(context.Context, *connect.Request[v1.GetUnitsByParcelIdRequest]) (*connect.Response[v1.GetUnitsByParcelIdResponse], error)
	GetPrimaryImprovementYearBuiltByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByParcelIdResponse], error)
	GetPrimaryImprovementEffectiveYearBuiltByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdResponse], error)
	GetPrimaryImprovementConditionIdByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementConditionIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByParcelIdResponse], error)
	GetPrimaryImprovementTypeIdByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementTypeIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByParcelIdResponse], error)
	GetLandAreaSqftByFeatureId(context.Context, *connect.Request[v1.GetLandAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetLandAreaSqftByFeatureIdResponse], error)
	GetFrontageFtByFeatureId(context.Context, *connect.Request[v1.GetFrontageFtByFeatureIdRequest]) (*connect.Response[v1.GetFrontageFtByFeatureIdResponse], error)
	GetDepthFtByFeatureId(context.Context, *connect.Request[v1.GetDepthFtByFeatureIdRequest]) (*connect.Response[v1.GetDepthFtByFeatureIdResponse], error)
	GetLandUseIdByFeatureId(context.Context, *connect.Request[v1.GetLandUseIdByFeatureIdRequest]) (*connect.Response[v1.GetLandUseIdByFeatureIdResponse], error)
	GetZoningIdByFeatureId(context.Context, *connect.Request[v1.GetZoningIdByFeatureIdRequest]) (*connect.Response[v1.GetZoningIdByFeatureIdResponse], error)
	GetImprovementAreaSqftByFeatureId(context.Context, *connect.Request[v1.GetImprovementAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByFeatureIdResponse], error)
	GetBedroomsByFeatureId(context.Context, *connect.Request[v1.GetBedroomsByFeatureIdRequest]) (*connect.Response[v1.GetBedroomsByFeatureIdResponse], error)
	GetBathroomsByFeatureId(context.Context, *connect.Request[v1.GetBathroomsByFeatureIdRequest]) (*connect.Response[v1.GetBathroomsByFeatureIdResponse], error)
	GetUnitsByFeatureId(context.Context, *connect.Request[v1.GetUnitsByFeatureIdRequest]) (*connect.Response[v1.GetUnitsByFeatureIdResponse], error)
	GetPrimaryImprovementYearBuiltByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByFeatureIdResponse], error)
	GetPrimaryImprovementEffectiveYearBuiltByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdResponse], error)
	GetPrimaryImprovementConditionIdByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementConditionIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByFeatureIdResponse], error)
	GetPrimaryImprovementTypeIdByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementTypeIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByFeatureIdResponse], error)
	UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error)
}

// NewParcelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewParcelsServiceHandler(svc ParcelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	parcelsServiceMethods := v1.File_civil_mesh_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	parcelsServiceGetParcelsWithImprovementSummaryByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure,
		svc.GetParcelsWithImprovementSummaryByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetParcelsWithImprovementSummaryByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure,
		svc.GetParcelsWithImprovementSummaryByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelsWithImprovementSummaryByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetNumericalParcelStatsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetNumericalParcelStatsByIdProcedure,
		svc.GetNumericalParcelStatsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetNumericalParcelStatsById")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetCategoricalParcelStatsByIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetCategoricalParcelStatsByIdProcedure,
		svc.GetCategoricalParcelStatsById,
		connect.WithSchema(parcelsServiceMethods.ByName("GetCategoricalParcelStatsById")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetEquityComparablesHandler := connect.NewUnaryHandler(
		ParcelsServiceGetEquityComparablesProcedure,
		svc.GetEquityComparables,
		connect.WithSchema(parcelsServiceMethods.ByName("GetEquityComparables")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetSalesComparablesHandler := connect.NewUnaryHandler(
		ParcelsServiceGetSalesComparablesProcedure,
		svc.GetSalesComparables,
		connect.WithSchema(parcelsServiceMethods.ByName("GetSalesComparables")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetParcelIdsByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelIdsByFeatureIdProcedure,
		svc.GetParcelIdsByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelIdsByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetEstimatedParcelsExtentWGS84Handler := connect.NewUnaryHandler(
		ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure,
		svc.GetEstimatedParcelsExtentWGS84,
		connect.WithSchema(parcelsServiceMethods.ByName("GetEstimatedParcelsExtentWGS84")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetLandAreaSqftByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetLandAreaSqftByParcelIdProcedure,
		svc.GetLandAreaSqftByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetLandAreaSqftByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetFrontageFtByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetFrontageFtByParcelIdProcedure,
		svc.GetFrontageFtByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetFrontageFtByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetDepthFtByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetDepthFtByParcelIdProcedure,
		svc.GetDepthFtByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetDepthFtByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetLandUseIdByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetLandUseIdByParcelIdProcedure,
		svc.GetLandUseIdByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetLandUseIdByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetZoningIdByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetZoningIdByParcelIdProcedure,
		svc.GetZoningIdByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetZoningIdByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetImprovementAreaSqftByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetImprovementAreaSqftByParcelIdProcedure,
		svc.GetImprovementAreaSqftByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetImprovementAreaSqftByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetBedroomsByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetBedroomsByParcelIdProcedure,
		svc.GetBedroomsByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetBedroomsByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetBathroomsByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetBathroomsByParcelIdProcedure,
		svc.GetBathroomsByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetBathroomsByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetUnitsByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetUnitsByParcelIdProcedure,
		svc.GetUnitsByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetUnitsByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementYearBuiltByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementYearBuiltByParcelIdProcedure,
		svc.GetPrimaryImprovementYearBuiltByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementYearBuiltByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdProcedure,
		svc.GetPrimaryImprovementEffectiveYearBuiltByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementEffectiveYearBuiltByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementConditionIdByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementConditionIdByParcelIdProcedure,
		svc.GetPrimaryImprovementConditionIdByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementConditionIdByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementTypeIdByParcelIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementTypeIdByParcelIdProcedure,
		svc.GetPrimaryImprovementTypeIdByParcelId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementTypeIdByParcelId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetLandAreaSqftByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetLandAreaSqftByFeatureIdProcedure,
		svc.GetLandAreaSqftByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetLandAreaSqftByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetFrontageFtByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetFrontageFtByFeatureIdProcedure,
		svc.GetFrontageFtByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetFrontageFtByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetDepthFtByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetDepthFtByFeatureIdProcedure,
		svc.GetDepthFtByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetDepthFtByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetLandUseIdByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetLandUseIdByFeatureIdProcedure,
		svc.GetLandUseIdByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetLandUseIdByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetZoningIdByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetZoningIdByFeatureIdProcedure,
		svc.GetZoningIdByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetZoningIdByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetImprovementAreaSqftByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetImprovementAreaSqftByFeatureIdProcedure,
		svc.GetImprovementAreaSqftByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetImprovementAreaSqftByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetBedroomsByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetBedroomsByFeatureIdProcedure,
		svc.GetBedroomsByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetBedroomsByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetBathroomsByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetBathroomsByFeatureIdProcedure,
		svc.GetBathroomsByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetBathroomsByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetUnitsByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetUnitsByFeatureIdProcedure,
		svc.GetUnitsByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetUnitsByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdProcedure,
		svc.GetPrimaryImprovementYearBuiltByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementYearBuiltByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdProcedure,
		svc.GetPrimaryImprovementEffectiveYearBuiltByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementEffectiveYearBuiltByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementConditionIdByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementConditionIdByFeatureIdProcedure,
		svc.GetPrimaryImprovementConditionIdByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementConditionIdByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceGetPrimaryImprovementTypeIdByFeatureIdHandler := connect.NewUnaryHandler(
		ParcelsServiceGetPrimaryImprovementTypeIdByFeatureIdProcedure,
		svc.GetPrimaryImprovementTypeIdByFeatureId,
		connect.WithSchema(parcelsServiceMethods.ByName("GetPrimaryImprovementTypeIdByFeatureId")),
		connect.WithHandlerOptions(opts...),
	)
	parcelsServiceUpdateParcelHandler := connect.NewUnaryHandler(
		ParcelsServiceUpdateParcelProcedure,
		svc.UpdateParcel,
		connect.WithSchema(parcelsServiceMethods.ByName("UpdateParcel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.mesh.parcels.v1.ParcelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ParcelsServiceGetParcelsWithImprovementSummaryByParcelIdProcedure:
			parcelsServiceGetParcelsWithImprovementSummaryByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetParcelsWithImprovementSummaryByFeatureIdProcedure:
			parcelsServiceGetParcelsWithImprovementSummaryByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetNumericalParcelStatsByIdProcedure:
			parcelsServiceGetNumericalParcelStatsByIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetCategoricalParcelStatsByIdProcedure:
			parcelsServiceGetCategoricalParcelStatsByIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetEquityComparablesProcedure:
			parcelsServiceGetEquityComparablesHandler.ServeHTTP(w, r)
		case ParcelsServiceGetSalesComparablesProcedure:
			parcelsServiceGetSalesComparablesHandler.ServeHTTP(w, r)
		case ParcelsServiceGetParcelIdsByFeatureIdProcedure:
			parcelsServiceGetParcelIdsByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetEstimatedParcelsExtentWGS84Procedure:
			parcelsServiceGetEstimatedParcelsExtentWGS84Handler.ServeHTTP(w, r)
		case ParcelsServiceGetLandAreaSqftByParcelIdProcedure:
			parcelsServiceGetLandAreaSqftByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetFrontageFtByParcelIdProcedure:
			parcelsServiceGetFrontageFtByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetDepthFtByParcelIdProcedure:
			parcelsServiceGetDepthFtByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetLandUseIdByParcelIdProcedure:
			parcelsServiceGetLandUseIdByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetZoningIdByParcelIdProcedure:
			parcelsServiceGetZoningIdByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetImprovementAreaSqftByParcelIdProcedure:
			parcelsServiceGetImprovementAreaSqftByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetBedroomsByParcelIdProcedure:
			parcelsServiceGetBedroomsByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetBathroomsByParcelIdProcedure:
			parcelsServiceGetBathroomsByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetUnitsByParcelIdProcedure:
			parcelsServiceGetUnitsByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementYearBuiltByParcelIdProcedure:
			parcelsServiceGetPrimaryImprovementYearBuiltByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdProcedure:
			parcelsServiceGetPrimaryImprovementEffectiveYearBuiltByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementConditionIdByParcelIdProcedure:
			parcelsServiceGetPrimaryImprovementConditionIdByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementTypeIdByParcelIdProcedure:
			parcelsServiceGetPrimaryImprovementTypeIdByParcelIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetLandAreaSqftByFeatureIdProcedure:
			parcelsServiceGetLandAreaSqftByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetFrontageFtByFeatureIdProcedure:
			parcelsServiceGetFrontageFtByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetDepthFtByFeatureIdProcedure:
			parcelsServiceGetDepthFtByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetLandUseIdByFeatureIdProcedure:
			parcelsServiceGetLandUseIdByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetZoningIdByFeatureIdProcedure:
			parcelsServiceGetZoningIdByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetImprovementAreaSqftByFeatureIdProcedure:
			parcelsServiceGetImprovementAreaSqftByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetBedroomsByFeatureIdProcedure:
			parcelsServiceGetBedroomsByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetBathroomsByFeatureIdProcedure:
			parcelsServiceGetBathroomsByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetUnitsByFeatureIdProcedure:
			parcelsServiceGetUnitsByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdProcedure:
			parcelsServiceGetPrimaryImprovementYearBuiltByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdProcedure:
			parcelsServiceGetPrimaryImprovementEffectiveYearBuiltByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementConditionIdByFeatureIdProcedure:
			parcelsServiceGetPrimaryImprovementConditionIdByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceGetPrimaryImprovementTypeIdByFeatureIdProcedure:
			parcelsServiceGetPrimaryImprovementTypeIdByFeatureIdHandler.ServeHTTP(w, r)
		case ParcelsServiceUpdateParcelProcedure:
			parcelsServiceUpdateParcelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedParcelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedParcelsServiceHandler struct{}

func (UnimplementedParcelsServiceHandler) GetParcelsWithImprovementSummaryByParcelId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByParcelIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetParcelsWithImprovementSummaryByFeatureId(context.Context, *connect.Request[v1.GetParcelsWithImprovementSummaryByFeatureIdRequest]) (*connect.Response[v1.GetParcelsWithImprovementSummaryByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetNumericalParcelStatsById(context.Context, *connect.Request[v1.GetNumericalParcelStatsByIdRequest]) (*connect.Response[v1.GetNumericalParcelStatsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetNumericalParcelStatsById is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetCategoricalParcelStatsById(context.Context, *connect.Request[v1.GetCategoricalParcelStatsByIdRequest]) (*connect.Response[v1.GetCategoricalParcelStatsByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetCategoricalParcelStatsById is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetEquityComparables(context.Context, *connect.Request[v1.GetEquityComparablesRequest]) (*connect.Response[v1.GetEquityComparablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetEquityComparables is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetSalesComparables(context.Context, *connect.Request[v1.GetSalesComparablesRequest]) (*connect.Response[v1.GetSalesComparablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetSalesComparables is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetParcelIdsByFeatureId(context.Context, *connect.Request[v1.GetParcelIdsByFeatureIdRequest]) (*connect.Response[v1.GetParcelIdsByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetParcelIdsByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetEstimatedParcelsExtentWGS84(context.Context, *connect.Request[v1.GetEstimatedParcelsExtentWGS84Request]) (*connect.Response[v1.GetEstimatedParcelsExtentWGS84Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetEstimatedParcelsExtentWGS84 is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetLandAreaSqftByParcelId(context.Context, *connect.Request[v1.GetLandAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetLandAreaSqftByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetLandAreaSqftByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetFrontageFtByParcelId(context.Context, *connect.Request[v1.GetFrontageFtByParcelIdRequest]) (*connect.Response[v1.GetFrontageFtByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetFrontageFtByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetDepthFtByParcelId(context.Context, *connect.Request[v1.GetDepthFtByParcelIdRequest]) (*connect.Response[v1.GetDepthFtByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetDepthFtByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetLandUseIdByParcelId(context.Context, *connect.Request[v1.GetLandUseIdByParcelIdRequest]) (*connect.Response[v1.GetLandUseIdByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetLandUseIdByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetZoningIdByParcelId(context.Context, *connect.Request[v1.GetZoningIdByParcelIdRequest]) (*connect.Response[v1.GetZoningIdByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetZoningIdByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetImprovementAreaSqftByParcelId(context.Context, *connect.Request[v1.GetImprovementAreaSqftByParcelIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetImprovementAreaSqftByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetBedroomsByParcelId(context.Context, *connect.Request[v1.GetBedroomsByParcelIdRequest]) (*connect.Response[v1.GetBedroomsByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetBedroomsByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetBathroomsByParcelId(context.Context, *connect.Request[v1.GetBathroomsByParcelIdRequest]) (*connect.Response[v1.GetBathroomsByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetBathroomsByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetUnitsByParcelId(context.Context, *connect.Request[v1.GetUnitsByParcelIdRequest]) (*connect.Response[v1.GetUnitsByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetUnitsByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementYearBuiltByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementYearBuiltByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementEffectiveYearBuiltByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementEffectiveYearBuiltByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementConditionIdByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementConditionIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementConditionIdByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementTypeIdByParcelId(context.Context, *connect.Request[v1.GetPrimaryImprovementTypeIdByParcelIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByParcelIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementTypeIdByParcelId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetLandAreaSqftByFeatureId(context.Context, *connect.Request[v1.GetLandAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetLandAreaSqftByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetLandAreaSqftByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetFrontageFtByFeatureId(context.Context, *connect.Request[v1.GetFrontageFtByFeatureIdRequest]) (*connect.Response[v1.GetFrontageFtByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetFrontageFtByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetDepthFtByFeatureId(context.Context, *connect.Request[v1.GetDepthFtByFeatureIdRequest]) (*connect.Response[v1.GetDepthFtByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetDepthFtByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetLandUseIdByFeatureId(context.Context, *connect.Request[v1.GetLandUseIdByFeatureIdRequest]) (*connect.Response[v1.GetLandUseIdByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetLandUseIdByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetZoningIdByFeatureId(context.Context, *connect.Request[v1.GetZoningIdByFeatureIdRequest]) (*connect.Response[v1.GetZoningIdByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetZoningIdByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetImprovementAreaSqftByFeatureId(context.Context, *connect.Request[v1.GetImprovementAreaSqftByFeatureIdRequest]) (*connect.Response[v1.GetImprovementAreaSqftByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetImprovementAreaSqftByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetBedroomsByFeatureId(context.Context, *connect.Request[v1.GetBedroomsByFeatureIdRequest]) (*connect.Response[v1.GetBedroomsByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetBedroomsByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetBathroomsByFeatureId(context.Context, *connect.Request[v1.GetBathroomsByFeatureIdRequest]) (*connect.Response[v1.GetBathroomsByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetBathroomsByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetUnitsByFeatureId(context.Context, *connect.Request[v1.GetUnitsByFeatureIdRequest]) (*connect.Response[v1.GetUnitsByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetUnitsByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementYearBuiltByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementYearBuiltByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementYearBuiltByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementEffectiveYearBuiltByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementEffectiveYearBuiltByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementEffectiveYearBuiltByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementConditionIdByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementConditionIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementConditionIdByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementConditionIdByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) GetPrimaryImprovementTypeIdByFeatureId(context.Context, *connect.Request[v1.GetPrimaryImprovementTypeIdByFeatureIdRequest]) (*connect.Response[v1.GetPrimaryImprovementTypeIdByFeatureIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetPrimaryImprovementTypeIdByFeatureId is not implemented"))
}

func (UnimplementedParcelsServiceHandler) UpdateParcel(context.Context, *connect.Request[v1.UpdateParcelRequest]) (*connect.Response[v1.UpdateParcelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.UpdateParcel is not implemented"))
}
