// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/mesh/parcels/v1/parcels.proto

package parcelsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/mesh/parcels/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ParcelsServiceName is the fully-qualified name of the ParcelsService service.
	ParcelsServiceName = "civil.mesh.parcels.v1.ParcelsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ParcelsServiceGetParcelAttributeProcedure is the fully-qualified name of the ParcelsService's
	// GetParcelAttribute RPC.
	ParcelsServiceGetParcelAttributeProcedure = "/civil.mesh.parcels.v1.ParcelsService/GetParcelAttribute"
)

// ParcelsServiceClient is a client for the civil.mesh.parcels.v1.ParcelsService service.
type ParcelsServiceClient interface {
	// Retrieves a specified attribute value for a given parcel.
	GetParcelAttribute(context.Context, *connect.Request[v1.GetParcelAttributeRequest]) (*connect.Response[v1.GetParcelAttributeResponse], error)
}

// NewParcelsServiceClient constructs a client for the civil.mesh.parcels.v1.ParcelsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewParcelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ParcelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	parcelsServiceMethods := v1.File_civil_mesh_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	return &parcelsServiceClient{
		getParcelAttribute: connect.NewClient[v1.GetParcelAttributeRequest, v1.GetParcelAttributeResponse](
			httpClient,
			baseURL+ParcelsServiceGetParcelAttributeProcedure,
			connect.WithSchema(parcelsServiceMethods.ByName("GetParcelAttribute")),
			connect.WithClientOptions(opts...),
		),
	}
}

// parcelsServiceClient implements ParcelsServiceClient.
type parcelsServiceClient struct {
	getParcelAttribute *connect.Client[v1.GetParcelAttributeRequest, v1.GetParcelAttributeResponse]
}

// GetParcelAttribute calls civil.mesh.parcels.v1.ParcelsService.GetParcelAttribute.
func (c *parcelsServiceClient) GetParcelAttribute(ctx context.Context, req *connect.Request[v1.GetParcelAttributeRequest]) (*connect.Response[v1.GetParcelAttributeResponse], error) {
	return c.getParcelAttribute.CallUnary(ctx, req)
}

// ParcelsServiceHandler is an implementation of the civil.mesh.parcels.v1.ParcelsService service.
type ParcelsServiceHandler interface {
	// Retrieves a specified attribute value for a given parcel.
	GetParcelAttribute(context.Context, *connect.Request[v1.GetParcelAttributeRequest]) (*connect.Response[v1.GetParcelAttributeResponse], error)
}

// NewParcelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewParcelsServiceHandler(svc ParcelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	parcelsServiceMethods := v1.File_civil_mesh_parcels_v1_parcels_proto.Services().ByName("ParcelsService").Methods()
	parcelsServiceGetParcelAttributeHandler := connect.NewUnaryHandler(
		ParcelsServiceGetParcelAttributeProcedure,
		svc.GetParcelAttribute,
		connect.WithSchema(parcelsServiceMethods.ByName("GetParcelAttribute")),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.mesh.parcels.v1.ParcelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ParcelsServiceGetParcelAttributeProcedure:
			parcelsServiceGetParcelAttributeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedParcelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedParcelsServiceHandler struct{}

func (UnimplementedParcelsServiceHandler) GetParcelAttribute(context.Context, *connect.Request[v1.GetParcelAttributeRequest]) (*connect.Response[v1.GetParcelAttributeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.mesh.parcels.v1.ParcelsService.GetParcelAttribute is not implemented"))
}
