// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: civil/public/valuations/v1/valuations.proto

package valuationsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/civil-labs/civil-api-go/civil/public/valuations/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ValuationServiceName is the fully-qualified name of the ValuationService service.
	ValuationServiceName = "civil.public.valuations.v1.ValuationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ValuationServiceGetValuationsProcedure is the fully-qualified name of the ValuationService's
	// GetValuations RPC.
	ValuationServiceGetValuationsProcedure = "/civil.public.valuations.v1.ValuationService/GetValuations"
)

// ValuationServiceClient is a client for the civil.public.valuations.v1.ValuationService service.
type ValuationServiceClient interface {
	GetValuations(context.Context, *connect.Request[v1.GetValuationsRequest]) (*connect.Response[v1.GetValuationsResponse], error)
}

// NewValuationServiceClient constructs a client for the civil.public.valuations.v1.ValuationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewValuationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ValuationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	valuationServiceMethods := v1.File_civil_public_valuations_v1_valuations_proto.Services().ByName("ValuationService").Methods()
	return &valuationServiceClient{
		getValuations: connect.NewClient[v1.GetValuationsRequest, v1.GetValuationsResponse](
			httpClient,
			baseURL+ValuationServiceGetValuationsProcedure,
			connect.WithSchema(valuationServiceMethods.ByName("GetValuations")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// valuationServiceClient implements ValuationServiceClient.
type valuationServiceClient struct {
	getValuations *connect.Client[v1.GetValuationsRequest, v1.GetValuationsResponse]
}

// GetValuations calls civil.public.valuations.v1.ValuationService.GetValuations.
func (c *valuationServiceClient) GetValuations(ctx context.Context, req *connect.Request[v1.GetValuationsRequest]) (*connect.Response[v1.GetValuationsResponse], error) {
	return c.getValuations.CallUnary(ctx, req)
}

// ValuationServiceHandler is an implementation of the civil.public.valuations.v1.ValuationService
// service.
type ValuationServiceHandler interface {
	GetValuations(context.Context, *connect.Request[v1.GetValuationsRequest]) (*connect.Response[v1.GetValuationsResponse], error)
}

// NewValuationServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewValuationServiceHandler(svc ValuationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	valuationServiceMethods := v1.File_civil_public_valuations_v1_valuations_proto.Services().ByName("ValuationService").Methods()
	valuationServiceGetValuationsHandler := connect.NewUnaryHandler(
		ValuationServiceGetValuationsProcedure,
		svc.GetValuations,
		connect.WithSchema(valuationServiceMethods.ByName("GetValuations")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/civil.public.valuations.v1.ValuationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ValuationServiceGetValuationsProcedure:
			valuationServiceGetValuationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedValuationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedValuationServiceHandler struct{}

func (UnimplementedValuationServiceHandler) GetValuations(context.Context, *connect.Request[v1.GetValuationsRequest]) (*connect.Response[v1.GetValuationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("civil.public.valuations.v1.ValuationService.GetValuations is not implemented"))
}
