// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: civil/public/improvements/v1/improvements.proto

package improvementsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImprovementType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImprovementType) Reset() {
	*x = ImprovementType{}
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprovementType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprovementType) ProtoMessage() {}

func (x *ImprovementType) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprovementType.ProtoReflect.Descriptor instead.
func (*ImprovementType) Descriptor() ([]byte, []int) {
	return file_civil_public_improvements_v1_improvements_proto_rawDescGZIP(), []int{0}
}

func (x *ImprovementType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImprovementType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImprovementType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImprovementType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetImprovementTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImprovementTypesRequest) Reset() {
	*x = GetImprovementTypesRequest{}
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementTypesRequest) ProtoMessage() {}

func (x *GetImprovementTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementTypesRequest.ProtoReflect.Descriptor instead.
func (*GetImprovementTypesRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_improvements_v1_improvements_proto_rawDescGZIP(), []int{1}
}

type GetImprovementTypesResponse struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ImprovementTypes map[string]*ImprovementType `protobuf:"bytes,1,rep,name=improvement_types,json=improvementTypes,proto3" json:"improvement_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetImprovementTypesResponse) Reset() {
	*x = GetImprovementTypesResponse{}
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementTypesResponse) ProtoMessage() {}

func (x *GetImprovementTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementTypesResponse.ProtoReflect.Descriptor instead.
func (*GetImprovementTypesResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_improvements_v1_improvements_proto_rawDescGZIP(), []int{2}
}

func (x *GetImprovementTypesResponse) GetImprovementTypes() map[string]*ImprovementType {
	if x != nil {
		return x.ImprovementTypes
	}
	return nil
}

type ImprovementCondition struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepcreciationModifier float32                `protobuf:"fixed32,3,opt,name=depcreciation_modifier,json=depcreciationModifier,proto3" json:"depcreciation_modifier,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ImprovementCondition) Reset() {
	*x = ImprovementCondition{}
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImprovementCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImprovementCondition) ProtoMessage() {}

func (x *ImprovementCondition) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImprovementCondition.ProtoReflect.Descriptor instead.
func (*ImprovementCondition) Descriptor() ([]byte, []int) {
	return file_civil_public_improvements_v1_improvements_proto_rawDescGZIP(), []int{3}
}

func (x *ImprovementCondition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImprovementCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImprovementCondition) GetDepcreciationModifier() float32 {
	if x != nil {
		return x.DepcreciationModifier
	}
	return 0
}

type GetImprovementConditionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImprovementConditionsRequest) Reset() {
	*x = GetImprovementConditionsRequest{}
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementConditionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementConditionsRequest) ProtoMessage() {}

func (x *GetImprovementConditionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementConditionsRequest.ProtoReflect.Descriptor instead.
func (*GetImprovementConditionsRequest) Descriptor() ([]byte, []int) {
	return file_civil_public_improvements_v1_improvements_proto_rawDescGZIP(), []int{4}
}

type GetImprovementConditionsResponse struct {
	state                 protoimpl.MessageState           `protogen:"open.v1"`
	ImprovementConditions map[string]*ImprovementCondition `protobuf:"bytes,1,rep,name=improvement_conditions,json=improvementConditions,proto3" json:"improvement_conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetImprovementConditionsResponse) Reset() {
	*x = GetImprovementConditionsResponse{}
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImprovementConditionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImprovementConditionsResponse) ProtoMessage() {}

func (x *GetImprovementConditionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_civil_public_improvements_v1_improvements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImprovementConditionsResponse.ProtoReflect.Descriptor instead.
func (*GetImprovementConditionsResponse) Descriptor() ([]byte, []int) {
	return file_civil_public_improvements_v1_improvements_proto_rawDescGZIP(), []int{5}
}

func (x *GetImprovementConditionsResponse) GetImprovementConditions() map[string]*ImprovementCondition {
	if x != nil {
		return x.ImprovementConditions
	}
	return nil
}

var File_civil_public_improvements_v1_improvements_proto protoreflect.FileDescriptor

const file_civil_public_improvements_v1_improvements_proto_rawDesc = "" +
	"\n" +
	"/civil/public/improvements/v1/improvements.proto\x12\x1ccivil.public.improvements.v1\"k\n" +
	"\x0fImprovementType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x1c\n" +
	"\x1aGetImprovementTypesRequest\"\x8f\x02\n" +
	"\x1bGetImprovementTypesResponse\x12|\n" +
	"\x11improvement_types\x18\x01 \x03(\v2O.civil.public.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntryR\x10improvementTypes\x1ar\n" +
	"\x15ImprovementTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.civil.public.improvements.v1.ImprovementTypeR\x05value:\x028\x01\"q\n" +
	"\x14ImprovementCondition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x16depcreciation_modifier\x18\x03 \x01(\x02R\x15depcreciationModifier\"!\n" +
	"\x1fGetImprovementConditionsRequest\"\xb3\x02\n" +
	" GetImprovementConditionsResponse\x12\x90\x01\n" +
	"\x16improvement_conditions\x18\x01 \x03(\v2Y.civil.public.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntryR\x15improvementConditions\x1a|\n" +
	"\x1aImprovementConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12H\n" +
	"\x05value\x18\x02 \x01(\v22.civil.public.improvements.v1.ImprovementConditionR\x05value:\x028\x012\xc7\x02\n" +
	"\x12ImprovementService\x12\x8f\x01\n" +
	"\x13GetImprovementTypes\x128.civil.public.improvements.v1.GetImprovementTypesRequest\x1a9.civil.public.improvements.v1.GetImprovementTypesResponse\"\x03\x90\x02\x01\x12\x9e\x01\n" +
	"\x18GetImprovementConditions\x12=.civil.public.improvements.v1.GetImprovementConditionsRequest\x1a>.civil.public.improvements.v1.GetImprovementConditionsResponse\"\x03\x90\x02\x01B\x9a\x02\n" +
	" com.civil.public.improvements.v1B\x11ImprovementsProtoP\x01ZNgithub.com/civil-labs/civil-api-go/civil/public/improvements/v1;improvementsv1\xa2\x02\x03CPI\xaa\x02\x1cCivil.Public.Improvements.V1\xca\x02\x1dCivil\\Public_\\Improvements\\V1\xe2\x02)Civil\\Public_\\Improvements\\V1\\GPBMetadata\xea\x02\x1fCivil::Public::Improvements::V1b\x06proto3"

var (
	file_civil_public_improvements_v1_improvements_proto_rawDescOnce sync.Once
	file_civil_public_improvements_v1_improvements_proto_rawDescData []byte
)

func file_civil_public_improvements_v1_improvements_proto_rawDescGZIP() []byte {
	file_civil_public_improvements_v1_improvements_proto_rawDescOnce.Do(func() {
		file_civil_public_improvements_v1_improvements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_civil_public_improvements_v1_improvements_proto_rawDesc), len(file_civil_public_improvements_v1_improvements_proto_rawDesc)))
	})
	return file_civil_public_improvements_v1_improvements_proto_rawDescData
}

var file_civil_public_improvements_v1_improvements_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_civil_public_improvements_v1_improvements_proto_goTypes = []any{
	(*ImprovementType)(nil),                  // 0: civil.public.improvements.v1.ImprovementType
	(*GetImprovementTypesRequest)(nil),       // 1: civil.public.improvements.v1.GetImprovementTypesRequest
	(*GetImprovementTypesResponse)(nil),      // 2: civil.public.improvements.v1.GetImprovementTypesResponse
	(*ImprovementCondition)(nil),             // 3: civil.public.improvements.v1.ImprovementCondition
	(*GetImprovementConditionsRequest)(nil),  // 4: civil.public.improvements.v1.GetImprovementConditionsRequest
	(*GetImprovementConditionsResponse)(nil), // 5: civil.public.improvements.v1.GetImprovementConditionsResponse
	nil,                                      // 6: civil.public.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntry
	nil,                                      // 7: civil.public.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntry
}
var file_civil_public_improvements_v1_improvements_proto_depIdxs = []int32{
	6, // 0: civil.public.improvements.v1.GetImprovementTypesResponse.improvement_types:type_name -> civil.public.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntry
	7, // 1: civil.public.improvements.v1.GetImprovementConditionsResponse.improvement_conditions:type_name -> civil.public.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntry
	0, // 2: civil.public.improvements.v1.GetImprovementTypesResponse.ImprovementTypesEntry.value:type_name -> civil.public.improvements.v1.ImprovementType
	3, // 3: civil.public.improvements.v1.GetImprovementConditionsResponse.ImprovementConditionsEntry.value:type_name -> civil.public.improvements.v1.ImprovementCondition
	1, // 4: civil.public.improvements.v1.ImprovementService.GetImprovementTypes:input_type -> civil.public.improvements.v1.GetImprovementTypesRequest
	4, // 5: civil.public.improvements.v1.ImprovementService.GetImprovementConditions:input_type -> civil.public.improvements.v1.GetImprovementConditionsRequest
	2, // 6: civil.public.improvements.v1.ImprovementService.GetImprovementTypes:output_type -> civil.public.improvements.v1.GetImprovementTypesResponse
	5, // 7: civil.public.improvements.v1.ImprovementService.GetImprovementConditions:output_type -> civil.public.improvements.v1.GetImprovementConditionsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_civil_public_improvements_v1_improvements_proto_init() }
func file_civil_public_improvements_v1_improvements_proto_init() {
	if File_civil_public_improvements_v1_improvements_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_civil_public_improvements_v1_improvements_proto_rawDesc), len(file_civil_public_improvements_v1_improvements_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_civil_public_improvements_v1_improvements_proto_goTypes,
		DependencyIndexes: file_civil_public_improvements_v1_improvements_proto_depIdxs,
		MessageInfos:      file_civil_public_improvements_v1_improvements_proto_msgTypes,
	}.Build()
	File_civil_public_improvements_v1_improvements_proto = out.File
	file_civil_public_improvements_v1_improvements_proto_goTypes = nil
	file_civil_public_improvements_v1_improvements_proto_depIdxs = nil
}
